# Generated from architecture/build-capabilities.json by check-build-capabilities.mjs.
# Do not edit this projection directly.

set(KUNGFU_KNOWN_BUILD_PROFILES "journal;embedded-minimal;embedded-sqlite;server;full")
set(KUNGFU_SUPPORTED_BUILD_PROFILES "journal;embedded-minimal;embedded-sqlite;full")
set(KUNGFU_BUILD_PROFILE "full" CACHE STRING "Kungfu supported Core build profile")
set_property(CACHE KUNGFU_BUILD_PROFILE PROPERTY STRINGS ${KUNGFU_SUPPORTED_BUILD_PROFILES})
if(NOT KUNGFU_BUILD_PROFILE IN_LIST KUNGFU_KNOWN_BUILD_PROFILES)
  message(FATAL_ERROR "unknown Kungfu build profile: ${KUNGFU_BUILD_PROFILE}; known=${KUNGFU_KNOWN_BUILD_PROFILES}")
endif()
if(NOT KUNGFU_BUILD_PROFILE IN_LIST KUNGFU_SUPPORTED_BUILD_PROFILES)
  message(FATAL_ERROR "Kungfu build profile ${KUNGFU_BUILD_PROFILE} is planned but not yet qualified; supported=${KUNGFU_SUPPORTED_BUILD_PROFILES}")
endif()

if(KUNGFU_BUILD_PROFILE STREQUAL "journal")
  set(KUNGFU_BUILD_COMPONENTS "journal-core")
  set(KUNGFU_BUILD_PROVIDERS "")
  set(KUNGFU_BUILD_PROJECTIONS "")
  set(KUNGFU_BUILD_BINDINGS "cxx")
  set(KUNGFU_BUILD_DEPENDENCY_ROOTS "fmt;nlohmann-json;spdlog;xxhash")
  set(KUNGFU_BUILD_LINK_DEPENDENCIES "fmt::fmt-header-only;nlohmann_json::nlohmann_json")
  set(KUNGFU_TARGET_KUNGFU_CONTRACTS_DEPENDENCIES "nlohmann_json::nlohmann_json")
  set(KUNGFU_TARGET_KUNGFU_LEDGER_SERVICES_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_STATE_QUERY_SERVICES_DEPENDENCIES "fmt::fmt-header-only")
  set(KUNGFU_TARGET_KUNGFU_STATE_CACHE_SERVICES_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_LIVE_SERVICES_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_STORAGE_SERVICES_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_EXTENSION_SERVICES_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_STORAGE_ADAPTERS_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_VIEW_ADAPTERS_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_PLATFORM_ADAPTERS_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_ABI_EXPORTS_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_COMPOSITION_DEPENDENCIES "")
elseif(KUNGFU_BUILD_PROFILE STREQUAL "embedded-minimal")
  set(KUNGFU_BUILD_COMPONENTS "journal-core;storage-provider-sdk")
  set(KUNGFU_BUILD_PROVIDERS "custom-content-store")
  set(KUNGFU_BUILD_PROJECTIONS "")
  set(KUNGFU_BUILD_BINDINGS "cxx")
  set(KUNGFU_BUILD_DEPENDENCY_ROOTS "fmt;nlohmann-json;spdlog;xxhash")
  set(KUNGFU_BUILD_LINK_DEPENDENCIES "fmt::fmt-header-only;nlohmann_json::nlohmann_json")
  set(KUNGFU_TARGET_KUNGFU_CONTRACTS_DEPENDENCIES "nlohmann_json::nlohmann_json")
  set(KUNGFU_TARGET_KUNGFU_LEDGER_SERVICES_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_STATE_QUERY_SERVICES_DEPENDENCIES "fmt::fmt-header-only")
  set(KUNGFU_TARGET_KUNGFU_STATE_CACHE_SERVICES_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_LIVE_SERVICES_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_STORAGE_SERVICES_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_EXTENSION_SERVICES_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_STORAGE_ADAPTERS_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_VIEW_ADAPTERS_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_PLATFORM_ADAPTERS_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_ABI_EXPORTS_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_COMPOSITION_DEPENDENCIES "")
elseif(KUNGFU_BUILD_PROFILE STREQUAL "embedded-sqlite")
  set(KUNGFU_BUILD_COMPONENTS "journal-core;runtime-contracts;runtime-services;runtime-adapters;composition")
  set(KUNGFU_BUILD_PROVIDERS "file-storage")
  set(KUNGFU_BUILD_PROJECTIONS "sqlite-projection;sqlite-state-cache;sqlite-query-acceleration")
  set(KUNGFU_BUILD_BINDINGS "cxx;c")
  set(KUNGFU_BUILD_DEPENDENCY_ROOTS "flatbuffers;fmt;nlohmann-json;nng;rxcpp;spdlog;sqlite;sqlite-orm;tabulate;xxhash")
  set(KUNGFU_BUILD_LINK_DEPENDENCIES "flatbuffers::flatbuffers;fmt::fmt-header-only;nlohmann_json::nlohmann_json;nng::nng;rxcpp::rxcpp;SQLite::SQLite3;tabulate::tabulate")
  set(KUNGFU_TARGET_KUNGFU_CONTRACTS_DEPENDENCIES "nlohmann_json::nlohmann_json;nng::nng;flatbuffers::flatbuffers;rxcpp::rxcpp;SQLite::SQLite3")
  set(KUNGFU_TARGET_KUNGFU_LEDGER_SERVICES_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_STATE_QUERY_SERVICES_DEPENDENCIES "fmt::fmt-header-only")
  set(KUNGFU_TARGET_KUNGFU_STATE_CACHE_SERVICES_DEPENDENCIES "SQLite::SQLite3")
  set(KUNGFU_TARGET_KUNGFU_LIVE_SERVICES_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_STORAGE_SERVICES_DEPENDENCIES "SQLite::SQLite3")
  set(KUNGFU_TARGET_KUNGFU_EXTENSION_SERVICES_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_STORAGE_ADAPTERS_DEPENDENCIES "SQLite::SQLite3")
  set(KUNGFU_TARGET_KUNGFU_VIEW_ADAPTERS_DEPENDENCIES "flatbuffers::flatbuffers")
  set(KUNGFU_TARGET_KUNGFU_PLATFORM_ADAPTERS_DEPENDENCIES "nng::nng;SQLite::SQLite3;tabulate::tabulate")
  set(KUNGFU_TARGET_KUNGFU_ABI_EXPORTS_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_COMPOSITION_DEPENDENCIES "")
elseif(KUNGFU_BUILD_PROFILE STREQUAL "server")
  set(KUNGFU_BUILD_COMPONENTS "journal-core;runtime-contracts;runtime-services;runtime-adapters;composition")
  set(KUNGFU_BUILD_PROVIDERS "file-storage;rocksdb-storage;rocksdb-live-kv")
  set(KUNGFU_BUILD_PROJECTIONS "sqlite-projection;sqlite-state-cache;sqlite-query-acceleration")
  set(KUNGFU_BUILD_BINDINGS "cxx;c;python;node")
  set(KUNGFU_BUILD_DEPENDENCY_ROOTS "flatbuffers;fmt;libnode;nlohmann-json;nng;pybind11;rocksdb;rxcpp;spdlog;sqlite;sqlite-orm;tabulate;xxhash")
  set(KUNGFU_BUILD_LINK_DEPENDENCIES "flatbuffers::flatbuffers;fmt::fmt-header-only;nlohmann_json::nlohmann_json;nng::nng;RocksDB::rocksdb;rxcpp::rxcpp;SQLite::SQLite3;tabulate::tabulate")
  set(KUNGFU_TARGET_KUNGFU_CONTRACTS_DEPENDENCIES "nlohmann_json::nlohmann_json;nng::nng;flatbuffers::flatbuffers;rxcpp::rxcpp;SQLite::SQLite3")
  set(KUNGFU_TARGET_KUNGFU_LEDGER_SERVICES_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_STATE_QUERY_SERVICES_DEPENDENCIES "fmt::fmt-header-only")
  set(KUNGFU_TARGET_KUNGFU_STATE_CACHE_SERVICES_DEPENDENCIES "SQLite::SQLite3")
  set(KUNGFU_TARGET_KUNGFU_LIVE_SERVICES_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_STORAGE_SERVICES_DEPENDENCIES "SQLite::SQLite3")
  set(KUNGFU_TARGET_KUNGFU_EXTENSION_SERVICES_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_STORAGE_ADAPTERS_DEPENDENCIES "SQLite::SQLite3;RocksDB::rocksdb")
  set(KUNGFU_TARGET_KUNGFU_VIEW_ADAPTERS_DEPENDENCIES "flatbuffers::flatbuffers")
  set(KUNGFU_TARGET_KUNGFU_PLATFORM_ADAPTERS_DEPENDENCIES "nng::nng;SQLite::SQLite3;tabulate::tabulate")
  set(KUNGFU_TARGET_KUNGFU_ABI_EXPORTS_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_COMPOSITION_DEPENDENCIES "")
elseif(KUNGFU_BUILD_PROFILE STREQUAL "full")
  set(KUNGFU_BUILD_COMPONENTS "journal-core;runtime-contracts;runtime-services;runtime-adapters;composition")
  set(KUNGFU_BUILD_PROVIDERS "file-storage;rocksdb-storage;rocksdb-live-kv")
  set(KUNGFU_BUILD_PROJECTIONS "sqlite-projection;sqlite-state-cache;sqlite-query-acceleration")
  set(KUNGFU_BUILD_BINDINGS "cxx;c;python;node;electron;wasm")
  set(KUNGFU_BUILD_DEPENDENCY_ROOTS "flatbuffers;fmt;libnode;nlohmann-json;nng;pybind11;rocksdb;rxcpp;spdlog;sqlite;sqlite-orm;tabulate;xxhash")
  set(KUNGFU_BUILD_LINK_DEPENDENCIES "flatbuffers::flatbuffers;fmt::fmt-header-only;nlohmann_json::nlohmann_json;nng::nng;RocksDB::rocksdb;rxcpp::rxcpp;SQLite::SQLite3;tabulate::tabulate")
  set(KUNGFU_TARGET_KUNGFU_CONTRACTS_DEPENDENCIES "nlohmann_json::nlohmann_json;nng::nng;flatbuffers::flatbuffers;rxcpp::rxcpp;SQLite::SQLite3")
  set(KUNGFU_TARGET_KUNGFU_LEDGER_SERVICES_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_STATE_QUERY_SERVICES_DEPENDENCIES "fmt::fmt-header-only")
  set(KUNGFU_TARGET_KUNGFU_STATE_CACHE_SERVICES_DEPENDENCIES "SQLite::SQLite3")
  set(KUNGFU_TARGET_KUNGFU_LIVE_SERVICES_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_STORAGE_SERVICES_DEPENDENCIES "SQLite::SQLite3")
  set(KUNGFU_TARGET_KUNGFU_EXTENSION_SERVICES_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_STORAGE_ADAPTERS_DEPENDENCIES "SQLite::SQLite3;RocksDB::rocksdb")
  set(KUNGFU_TARGET_KUNGFU_VIEW_ADAPTERS_DEPENDENCIES "flatbuffers::flatbuffers")
  set(KUNGFU_TARGET_KUNGFU_PLATFORM_ADAPTERS_DEPENDENCIES "nng::nng;SQLite::SQLite3;tabulate::tabulate")
  set(KUNGFU_TARGET_KUNGFU_ABI_EXPORTS_DEPENDENCIES "")
  set(KUNGFU_TARGET_KUNGFU_COMPOSITION_DEPENDENCIES "")
endif()

