# Generated from architecture/layers.json by check-layers.mjs.
# Do not edit this projection directly.

if(KUNGFU_WITH_CORE_TESTS)
  set(KUNGFU_PUBLIC_HEADER_GENERATED_DIR "${CMAKE_CURRENT_BINARY_DIR}/public-contract-headers")
  file(MAKE_DIRECTORY "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}")
  set(KUNGFU_PUBLIC_STABLE_VERSIONED_C_ABI_PROFILES "embedded-sqlite;full")
  if(KUNGFU_BUILD_PROFILE IN_LIST KUNGFU_PUBLIC_STABLE_VERSIONED_C_ABI_PROFILES)
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/stable-versioned-c-abi-0.c" "#include <kungfu/api.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/stable-versioned-c-abi-1.c" "#include <kungfu/initiative_assignment_api.h>\n")
    set(KUNGFU_PUBLIC_HEADERS_STABLE_VERSIONED_C_ABI_SOURCES "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/stable-versioned-c-abi-0.c" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/stable-versioned-c-abi-1.c")
    add_library(kungfu_public_headers_stable_versioned_c_abi OBJECT ${KUNGFU_PUBLIC_HEADERS_STABLE_VERSIONED_C_ABI_SOURCES})
    target_link_libraries(kungfu_public_headers_stable_versioned_c_abi PRIVATE ${KUNGFU_PUBLIC_ABI_TARGET})
  endif()
  set(KUNGFU_PUBLIC_LIBKUNGFU_CXX_SOURCE_SURFACE_PROFILES "embedded-sqlite;full")
  if(KUNGFU_BUILD_PROFILE IN_LIST KUNGFU_PUBLIC_LIBKUNGFU_CXX_SOURCE_SURFACE_PROFILES)
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-0.cpp" "#include <kungfu/api.hpp>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-1.cpp" "#include <kungfu/runtime/action/action_canonical_json.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-2.cpp" "#include <kungfu/runtime/action/action_contract_registry.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-3.cpp" "#include <kungfu/runtime/action/action_geometry.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-4.cpp" "#include <kungfu/runtime/action/action_runtime.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-5.cpp" "#include <kungfu/runtime/action/domain_profile.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-6.cpp" "#include <kungfu/runtime/action/profile_action.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-7.cpp" "#include <kungfu/runtime/action_recorder.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-8.cpp" "#include <kungfu/runtime/common.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-9.cpp" "#include <kungfu/runtime/crash_recovery.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-10.cpp" "#include <kungfu/runtime/durability.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-11.cpp" "#include <kungfu/runtime/durable_ingest.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-12.cpp" "#include <kungfu/runtime/facts/fact_admission.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-13.cpp" "#include <kungfu/runtime/io.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-14.cpp" "#include <kungfu/runtime/journal/tracer.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-15.cpp" "#include <kungfu/runtime/kfx/native_contract.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-16.cpp" "#include <kungfu/runtime/kfx/native_registry.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-17.cpp" "#include <kungfu/runtime/live/continuity.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-18.cpp" "#include <kungfu/runtime/live/coordinator.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-19.cpp" "#include <kungfu/runtime/live/identity.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-20.cpp" "#include <kungfu/runtime/live/key_value_store.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-21.cpp" "#include <kungfu/runtime/live/peer.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-22.cpp" "#include <kungfu/runtime/live/reactor.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-23.cpp" "#include <kungfu/runtime/live/route.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-24.cpp" "#include <kungfu/runtime/nanomsg/socket.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-25.cpp" "#include <kungfu/runtime/os.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-26.cpp" "#include <kungfu/runtime/profile/initiative_assignment_service.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-27.cpp" "#include <kungfu/runtime/profile/profile_lifecycle.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-28.cpp" "#include <kungfu/runtime/projection/flatbuffer.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-29.cpp" "#include <kungfu/runtime/projection/flatbuffer_schema_registry.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-30.cpp" "#include <kungfu/runtime/projection/hana_sqlite.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-31.cpp" "#include <kungfu/runtime/projection/sqlite_orm_ext.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-32.cpp" "#include <kungfu/runtime/projection_bootstrap.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-33.cpp" "#include <kungfu/runtime/query/fact_query.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-34.cpp" "#include <kungfu/runtime/query/saved_query_catalog.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-35.cpp" "#include <kungfu/runtime/rx.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-36.cpp" "#include <kungfu/runtime/sandbox/app_container.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-37.cpp" "#include <kungfu/runtime/schema/schema_compiler.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-38.cpp" "#include <kungfu/runtime/state_cache/manager.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-39.cpp" "#include <kungfu/runtime/state_cache/model.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-40.cpp" "#include <kungfu/runtime/state_cache/profile.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-41.cpp" "#include <kungfu/runtime/state_cache/store.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-42.cpp" "#include <kungfu/runtime/state_service.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-43.cpp" "#include <kungfu/runtime/state_shadow.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-44.cpp" "#include <kungfu/runtime/storage/binding_reflection.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-45.cpp" "#include <kungfu/runtime/storage/episode_manifest_projection.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-46.cpp" "#include <kungfu/runtime/storage/fact_kernel.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-47.cpp" "#include <kungfu/runtime/storage/hana_view.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-48.cpp" "#include <kungfu/runtime/storage/json_edge.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-49.cpp" "#include <kungfu/runtime/storage/manifest_catalog_projection.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-50.cpp" "#include <kungfu/runtime/storage/projection_content.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-51.cpp" "#include <kungfu/runtime/storage/projection_transaction.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-52.cpp" "#include <kungfu/runtime/storage/projection_types.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-53.cpp" "#include <kungfu/runtime/storage/service.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-54.cpp" "#include <kungfu/runtime/storage/source_registry_projection.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-55.cpp" "#include <kungfu/runtime/trust/assessment_runtime.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-56.cpp" "#include <kungfu/runtime/typed_state_projection.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-57.cpp" "#include <kungfu/runtime/util/stacktrace.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-58.cpp" "#include <kungfu/runtime/util/terminal.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-59.cpp" "#include <kungfu/sdk/generated/primitive_catalog_v2.hpp>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-60.cpp" "#include <kungfu/sdk/generated/runtime_action_v1.hpp>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-61.cpp" "#include <kungfu/sdk/generated/work_lifecycle_v1.hpp>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-62.cpp" "#include <kungfu/view/action_envelope.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-63.cpp" "#include <kungfu/view/pod.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-64.cpp" "#include <kungfu/view/schema.h>\n")
    set(KUNGFU_PUBLIC_HEADERS_LIBKUNGFU_CXX_SOURCE_SURFACE_SOURCES "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-0.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-1.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-2.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-3.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-4.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-5.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-6.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-7.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-8.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-9.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-10.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-11.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-12.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-13.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-14.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-15.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-16.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-17.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-18.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-19.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-20.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-21.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-22.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-23.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-24.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-25.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-26.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-27.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-28.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-29.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-30.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-31.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-32.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-33.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-34.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-35.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-36.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-37.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-38.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-39.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-40.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-41.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-42.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-43.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-44.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-45.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-46.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-47.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-48.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-49.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-50.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-51.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-52.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-53.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-54.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-55.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-56.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-57.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-58.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-59.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-60.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-61.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-62.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-63.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libkungfu-cxx-source-surface-64.cpp")
    add_library(kungfu_public_headers_libkungfu_cxx_source_surface OBJECT ${KUNGFU_PUBLIC_HEADERS_LIBKUNGFU_CXX_SOURCE_SURFACE_SOURCES})
    target_link_libraries(kungfu_public_headers_libkungfu_cxx_source_surface PRIVATE ${LIBKUNGFU_NAME})
    target_compile_features(kungfu_public_headers_libkungfu_cxx_source_surface PRIVATE cxx_std_20)
  endif()
  set(KUNGFU_PUBLIC_LIBYIJINJING_SOURCE_EMBEDDING_SURFACE_PROFILES "journal;embedded-minimal;embedded-sqlite;full")
  if(KUNGFU_BUILD_PROFILE IN_LIST KUNGFU_PUBLIC_LIBYIJINJING_SOURCE_EMBEDDING_SURFACE_PROFILES)
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-0.cpp" "#include <kungfu/common.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-1.cpp" "#include <kungfu/yijinjing/common.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-2.cpp" "#include <kungfu/yijinjing/hash.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-3.cpp" "#include <kungfu/yijinjing/io/advisory_file_lock.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-4.cpp" "#include <kungfu/yijinjing/journal/assemble.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-5.cpp" "#include <kungfu/yijinjing/journal/bus.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-6.cpp" "#include <kungfu/yijinjing/journal/common.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-7.cpp" "#include <kungfu/yijinjing/journal/frame.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-8.cpp" "#include <kungfu/yijinjing/journal/journal.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-9.cpp" "#include <kungfu/yijinjing/journal/layout_fingerprint.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-10.cpp" "#include <kungfu/yijinjing/journal/page.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-11.cpp" "#include <kungfu/yijinjing/log.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-12.cpp" "#include <kungfu/yijinjing/ownership.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-13.cpp" "#include <kungfu/yijinjing/platform/mmap.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-14.cpp" "#include <kungfu/yijinjing/schema/core.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-15.cpp" "#include <kungfu/yijinjing/schema/registry.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-16.cpp" "#include <kungfu/yijinjing/schema/types.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-17.cpp" "#include <kungfu/yijinjing/storage.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-18.cpp" "#include <kungfu/yijinjing/storage/common.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-19.cpp" "#include <kungfu/yijinjing/storage/content_hash.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-20.cpp" "#include <kungfu/yijinjing/storage/content_store.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-21.cpp" "#include <kungfu/yijinjing/storage/episode_manifest.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-22.cpp" "#include <kungfu/yijinjing/storage/episode_manifest_types.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-23.cpp" "#include <kungfu/yijinjing/storage/fact_ledger.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-24.cpp" "#include <kungfu/yijinjing/storage/manifest_catalog.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-25.cpp" "#include <kungfu/yijinjing/storage/manifest_catalog_types.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-26.cpp" "#include <kungfu/yijinjing/storage/provider_registry.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-27.cpp" "#include <kungfu/yijinjing/storage/source_registry.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-28.cpp" "#include <kungfu/yijinjing/storage/source_registry_types.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-29.cpp" "#include <kungfu/yijinjing/storage/sync_root.h>\n")
    file(WRITE "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-30.cpp" "#include <kungfu/yijinjing/time.h>\n")
    set(KUNGFU_PUBLIC_HEADERS_LIBYIJINJING_SOURCE_EMBEDDING_SURFACE_SOURCES "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-0.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-1.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-2.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-3.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-4.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-5.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-6.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-7.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-8.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-9.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-10.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-11.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-12.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-13.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-14.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-15.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-16.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-17.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-18.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-19.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-20.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-21.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-22.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-23.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-24.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-25.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-26.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-27.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-28.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-29.cpp" "${KUNGFU_PUBLIC_HEADER_GENERATED_DIR}/libyijinjing-source-embedding-surface-30.cpp")
    add_library(kungfu_public_headers_libyijinjing_source_embedding_surface OBJECT ${KUNGFU_PUBLIC_HEADERS_LIBYIJINJING_SOURCE_EMBEDDING_SURFACE_SOURCES})
    target_link_libraries(kungfu_public_headers_libyijinjing_source_embedding_surface PRIVATE yijinjing)
    target_compile_features(kungfu_public_headers_libyijinjing_source_embedding_surface PRIVATE cxx_std_20)
  endif()
endif()
