#  SPDX-License-Identifier: Apache-2.0

# Generate the declarative help manifest the Rust trunk renders for `kungfu
# --help` without waking a satellite (ADR-0046 stage 4).
#
# The command surface is the live click tree — this introspects it (names,
# short-help, help priorities, and the root group's options) rather than
# hand-authoring summaries, so the manifest is the single source of truth and
# cannot drift from the real CLI. The assemble leg (run-freeze.js) runs this once
# and writes the output to dist/kungfu/help-manifest.txt next to the front door.
#
# Output format (tab-separated; consumed by crates/trunk/src/help.rs):
#   VERSION <version>
#   PROJECTION <schema> <projection-root> <contract-root> <registry-root>
#   OPT     <flags>   <summary>
#   SECTION <id>      <title>     <summary>
#   CMD     <name>    <summary>   <priority> <section> <visibility>
#           <availability> <reason>
#   ROOTOPT <name>    <arity>     <envvar> <flags> <choices>

import click


def _clean(text):
    # Records are tab-separated and one per line; flatten any whitespace in help.
    return " ".join((text or "").split())


def _option_flags(option):
    flags = ", ".join(option.opts + option.secondary_opts)
    if not option.is_flag and option.nargs:
        flags = f"{flags} {option.make_metavar()}"
    return flags


def _root_envvar(option):
    """Project Click's root option into the native routing environment.

    The Python callback already uses ``KF_*`` as its root context contract.
    ``ENV_``-prefixed option names deliberately drop that marker, matching
    ``PrioritizedCommandGroup.pass_context`` and the root callback's
    ``KF_VERIFY_LOCATION`` behavior. Help/version are terminal root actions,
    not context values, so they carry no environment projection.
    """
    if option.name in {"help", "help_all", "help_section", "help_json", "version"}:
        return ""
    name = option.name[4:] if option.name.startswith("env_") else option.name
    return f"KF_{name.upper()}"


def build(group, version, *, projection=None):
    """Render the manifest for a click ``group`` (the root command tree).

    ``group`` is injected so the introspection is testable without importing the
    full runtime; ``main`` supplies the live ``kfc`` group and product version.
    """
    lines = [
        "# kungfu help manifest (generated by kungfu.cli.help_manifest; do not edit)",
        f"VERSION\t{version}",
    ]

    for param in group.params:
        if isinstance(param, click.Option) and not param.hidden:
            lines.append(f"OPT\t{_option_flags(param)}\t{_clean(param.help)}")
            arity = 0 if param.is_flag or param.count else param.nargs
            flags = ",".join(param.opts + param.secondary_opts)
            choices = (
                ",".join(str(choice) for choice in param.type.choices)
                if isinstance(param.type, click.Choice)
                else ""
            )
            lines.append(
                f"ROOTOPT\t{param.name}\t{arity}\t{_root_envvar(param)}"
                f"\t{flags}\t{choices}"
            )

    if projection is None:
        priorities = getattr(group, "help_priorities", {})
        for name, command in sorted(group.commands.items()):
            if getattr(command, "hidden", False):
                continue
            summary = _clean(command.get_short_help_str(limit=200))
            priority = priorities.get(name, 100)
            lines.append(f"CMD\t{name}\t{summary}\t{priority}")
    else:
        lines.append(
            f"PROJECTION\t{projection.get('schema', '')}"
            f"\t{projection.get('projectionRoot', '')}"
            f"\t{projection.get('contractRoot', '')}"
            f"\t{projection.get('registryRoot', '')}"
        )
        for section in projection["sections"]:
            lines.append(
                f"SECTION\t{section['id']}\t{_clean(section['title'])}"
                f"\t{_clean(section.get('summary'))}"
            )
        for command in projection["commands"]:
            availability = command.get("availability") or {}
            lines.append(
                f"CMD\t{command['name']}\t{_clean(command.get('summary'))}"
                f"\t{command.get('priority', 100)}\t{command['section']}"
                f"\t{command['visibility']}\t{availability.get('state', 'available')}"
                f"\t{_clean(availability.get('reason'))}"
            )

    return "\n".join(lines) + "\n"


def main():
    import sys

    import kungfu
    from kungfu.cli import help_projection
    from kungfu.cli.commands import kfc

    # Importing the registry attaches every top-level command to the `kfc` group.
    from kungfu.cli.commands import __registry__ as _registry  # noqa: F401

    sys.stdout.write(
        build(kfc, kungfu.__version__, projection=help_projection.build(kfc))
    )


if __name__ == "__main__":
    main()
