// @generated by scripts/generate-kfx-authoring-kit.mjs source_path=framework/api/src/capability/service-authz.ts
export type SandboxProfile = {
  base?: 'permissive' | 'restrictive';
  denyNetwork?: boolean;
  denyWrite?: boolean;
};
export type SandboxedCommand = {
  command: string;
  args: string[];
};
export type AppContainerSpec = {
  moniker: string;
  displayName: string;
  capabilities: string[];
  allowBroadWrite: boolean;
  allowLoopback: boolean;
};
export declare function windowsAppContainerSpec(
  profile?: SandboxProfile,
): AppContainerSpec;
export declare function isOsSandboxSupported(): boolean;
export declare function osSandboxCommand(
  command: string,
  args?: readonly string[],
  profile?: SandboxProfile,
): SandboxedCommand;
