# automatically generated by scripts/generate-rewind-reflection-python.mjs
# source: framework/core/src/python/kungfu/rewind/reflection.fbs
# do not modify

"""Compatibility facade for the split FlatBuffers reflection projection."""

import sys

from kungfu.rewind import reflection as _reflection

# flatc emits imports rooted at the declared ``reflection`` namespace. Keep
# the generated modules byte-for-byte canonical while resolving that namespace
# to their package-qualified installation location.
sys.modules["reflection"] = _reflection

from kungfu.rewind.reflection import AdvancedFeatures as _AdvancedFeatures  # noqa: E402
from kungfu.rewind.reflection import BaseType as _BaseType  # noqa: E402
from kungfu.rewind.reflection import Enum as _Enum  # noqa: E402
from kungfu.rewind.reflection import EnumVal as _EnumVal  # noqa: E402
from kungfu.rewind.reflection import Field as _Field  # noqa: E402
from kungfu.rewind.reflection import KeyValue as _KeyValue  # noqa: E402
from kungfu.rewind.reflection import Object as _Object  # noqa: E402
from kungfu.rewind.reflection import RPCCall as _RPCCall  # noqa: E402
from kungfu.rewind.reflection import Schema as _Schema  # noqa: E402
from kungfu.rewind.reflection import SchemaFile as _SchemaFile  # noqa: E402
from kungfu.rewind.reflection import Service as _Service  # noqa: E402
from kungfu.rewind.reflection import Type as _Type  # noqa: E402


def _export_legacy_surface(module):
    prefix = module.__name__.rsplit(".", 1)[-1]
    for name, value in vars(module).items():
        if name == prefix or name.startswith(prefix):
            value.__module__ = __name__
            globals()[name] = value


for _module in (
    _AdvancedFeatures,
    _BaseType,
    _Enum,
    _EnumVal,
    _Field,
    _KeyValue,
    _Object,
    _RPCCall,
    _Schema,
    _SchemaFile,
    _Service,
    _Type,
):
    _export_legacy_surface(_module)

# Static aliases keep the typed public consumers visible to mypy while the
# complete legacy surface remains projected by the generated-name loop above.
BaseType = _BaseType.BaseType
Schema = _Schema.Schema

# These names were also visible on flatc's former one-file module.
flatbuffers = _Schema.flatbuffers
import_numpy = _Schema.import_numpy
np = _Schema.np
