# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ApprovalDecision(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ApprovalDecision()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsApprovalDecision(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ApprovalDecision
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ApprovalDecision
    def RunId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ApprovalDecision
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ApprovalDecision
    def Decision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ApprovalDecision
    def Surface(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ApprovalDecision
    def DecidedBy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ApprovalDecision
    def Detail(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ApprovalDecision
    def Reason(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ApprovalDecisionStart(builder):
    builder.StartObject(7)

def Start(builder):
    ApprovalDecisionStart(builder)

def ApprovalDecisionAddRunId(builder, runId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(runId), 0)

def AddRunId(builder, runId):
    ApprovalDecisionAddRunId(builder, runId)

def ApprovalDecisionAddRequestId(builder, requestId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(requestId), 0)

def AddRequestId(builder, requestId):
    ApprovalDecisionAddRequestId(builder, requestId)

def ApprovalDecisionAddDecision(builder, decision):
    builder.PrependInt8Slot(2, decision, 0)

def AddDecision(builder, decision):
    ApprovalDecisionAddDecision(builder, decision)

def ApprovalDecisionAddSurface(builder, surface):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(surface), 0)

def AddSurface(builder, surface):
    ApprovalDecisionAddSurface(builder, surface)

def ApprovalDecisionAddDecidedBy(builder, decidedBy):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(decidedBy), 0)

def AddDecidedBy(builder, decidedBy):
    ApprovalDecisionAddDecidedBy(builder, decidedBy)

def ApprovalDecisionAddDetail(builder, detail):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(detail), 0)

def AddDetail(builder, detail):
    ApprovalDecisionAddDetail(builder, detail)

def ApprovalDecisionAddReason(builder, reason):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(reason), 0)

def AddReason(builder, reason):
    ApprovalDecisionAddReason(builder, reason)

def ApprovalDecisionEnd(builder):
    return builder.EndObject()

def End(builder):
    return ApprovalDecisionEnd(builder)
