# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

class Attribution(object):
    ExactRun = 0
    ExactSession = 1
    ObservedSessionDelta = 2
    ObservedWindow = 3
    ManualEstimate = 4
