# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CostSnapshot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CostSnapshot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCostSnapshot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CostSnapshot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CostSnapshot
    def RunId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CostSnapshot
    def WorkId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CostSnapshot
    def SessionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CostSnapshot
    def Layer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # CostSnapshot
    def Provider(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CostSnapshot
    def Surface(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CostSnapshot
    def Model(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CostSnapshot
    def Source(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CostSnapshot
    def Attribution(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # CostSnapshot
    def InputTokens(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # CostSnapshot
    def OutputTokens(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # CostSnapshot
    def CachedInputTokens(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # CostSnapshot
    def CacheCreationInputTokens(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # CostSnapshot
    def ReasoningTokens(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # CostSnapshot
    def CostUsd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # CostSnapshot
    def CostUsdKnown(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CostSnapshot
    def AmbiguousAttribution(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CostSnapshot
    def RawRef(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def CostSnapshotStart(builder):
    builder.StartObject(18)

def Start(builder):
    CostSnapshotStart(builder)

def CostSnapshotAddRunId(builder, runId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(runId), 0)

def AddRunId(builder, runId):
    CostSnapshotAddRunId(builder, runId)

def CostSnapshotAddWorkId(builder, workId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(workId), 0)

def AddWorkId(builder, workId):
    CostSnapshotAddWorkId(builder, workId)

def CostSnapshotAddSessionId(builder, sessionId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(sessionId), 0)

def AddSessionId(builder, sessionId):
    CostSnapshotAddSessionId(builder, sessionId)

def CostSnapshotAddLayer(builder, layer):
    builder.PrependInt8Slot(3, layer, 0)

def AddLayer(builder, layer):
    CostSnapshotAddLayer(builder, layer)

def CostSnapshotAddProvider(builder, provider):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(provider), 0)

def AddProvider(builder, provider):
    CostSnapshotAddProvider(builder, provider)

def CostSnapshotAddSurface(builder, surface):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(surface), 0)

def AddSurface(builder, surface):
    CostSnapshotAddSurface(builder, surface)

def CostSnapshotAddModel(builder, model):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(model), 0)

def AddModel(builder, model):
    CostSnapshotAddModel(builder, model)

def CostSnapshotAddSource(builder, source):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(source), 0)

def AddSource(builder, source):
    CostSnapshotAddSource(builder, source)

def CostSnapshotAddAttribution(builder, attribution):
    builder.PrependInt8Slot(8, attribution, 0)

def AddAttribution(builder, attribution):
    CostSnapshotAddAttribution(builder, attribution)

def CostSnapshotAddInputTokens(builder, inputTokens):
    builder.PrependInt64Slot(9, inputTokens, 0)

def AddInputTokens(builder, inputTokens):
    CostSnapshotAddInputTokens(builder, inputTokens)

def CostSnapshotAddOutputTokens(builder, outputTokens):
    builder.PrependInt64Slot(10, outputTokens, 0)

def AddOutputTokens(builder, outputTokens):
    CostSnapshotAddOutputTokens(builder, outputTokens)

def CostSnapshotAddCachedInputTokens(builder, cachedInputTokens):
    builder.PrependInt64Slot(11, cachedInputTokens, 0)

def AddCachedInputTokens(builder, cachedInputTokens):
    CostSnapshotAddCachedInputTokens(builder, cachedInputTokens)

def CostSnapshotAddCacheCreationInputTokens(builder, cacheCreationInputTokens):
    builder.PrependInt64Slot(12, cacheCreationInputTokens, 0)

def AddCacheCreationInputTokens(builder, cacheCreationInputTokens):
    CostSnapshotAddCacheCreationInputTokens(builder, cacheCreationInputTokens)

def CostSnapshotAddReasoningTokens(builder, reasoningTokens):
    builder.PrependInt64Slot(13, reasoningTokens, 0)

def AddReasoningTokens(builder, reasoningTokens):
    CostSnapshotAddReasoningTokens(builder, reasoningTokens)

def CostSnapshotAddCostUsd(builder, costUsd):
    builder.PrependFloat64Slot(14, costUsd, 0.0)

def AddCostUsd(builder, costUsd):
    CostSnapshotAddCostUsd(builder, costUsd)

def CostSnapshotAddCostUsdKnown(builder, costUsdKnown):
    builder.PrependBoolSlot(15, costUsdKnown, 0)

def AddCostUsdKnown(builder, costUsdKnown):
    CostSnapshotAddCostUsdKnown(builder, costUsdKnown)

def CostSnapshotAddAmbiguousAttribution(builder, ambiguousAttribution):
    builder.PrependBoolSlot(16, ambiguousAttribution, 0)

def AddAmbiguousAttribution(builder, ambiguousAttribution):
    CostSnapshotAddAmbiguousAttribution(builder, ambiguousAttribution)

def CostSnapshotAddRawRef(builder, rawRef):
    builder.PrependUOffsetTRelativeSlot(17, flatbuffers.number_types.UOffsetTFlags.py_type(rawRef), 0)

def AddRawRef(builder, rawRef):
    CostSnapshotAddRawRef(builder, rawRef)

def CostSnapshotEnd(builder):
    return builder.EndObject()

def End(builder):
    return CostSnapshotEnd(builder)
