# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ModelResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ModelResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsModelResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ModelResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ModelResponse
    def RunId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ModelResponse
    def SpanId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ModelResponse
    def Layer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ModelResponse
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ModelResponse
    def ResponseBody(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ModelResponse
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ModelResponse
    def FinishReason(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ModelResponse
    def InputTokens(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ModelResponse
    def OutputTokens(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ModelResponse
    def LatencyNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def ModelResponseStart(builder):
    builder.StartObject(10)

def Start(builder):
    ModelResponseStart(builder)

def ModelResponseAddRunId(builder, runId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(runId), 0)

def AddRunId(builder, runId):
    ModelResponseAddRunId(builder, runId)

def ModelResponseAddSpanId(builder, spanId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(spanId), 0)

def AddSpanId(builder, spanId):
    ModelResponseAddSpanId(builder, spanId)

def ModelResponseAddLayer(builder, layer):
    builder.PrependInt8Slot(2, layer, 0)

def AddLayer(builder, layer):
    ModelResponseAddLayer(builder, layer)

def ModelResponseAddStatus(builder, status):
    builder.PrependInt8Slot(3, status, 0)

def AddStatus(builder, status):
    ModelResponseAddStatus(builder, status)

def ModelResponseAddResponseBody(builder, responseBody):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(responseBody), 0)

def AddResponseBody(builder, responseBody):
    ModelResponseAddResponseBody(builder, responseBody)

def ModelResponseAddError(builder, error):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def AddError(builder, error):
    ModelResponseAddError(builder, error)

def ModelResponseAddFinishReason(builder, finishReason):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(finishReason), 0)

def AddFinishReason(builder, finishReason):
    ModelResponseAddFinishReason(builder, finishReason)

def ModelResponseAddInputTokens(builder, inputTokens):
    builder.PrependInt64Slot(7, inputTokens, 0)

def AddInputTokens(builder, inputTokens):
    ModelResponseAddInputTokens(builder, inputTokens)

def ModelResponseAddOutputTokens(builder, outputTokens):
    builder.PrependInt64Slot(8, outputTokens, 0)

def AddOutputTokens(builder, outputTokens):
    ModelResponseAddOutputTokens(builder, outputTokens)

def ModelResponseAddLatencyNs(builder, latencyNs):
    builder.PrependInt64Slot(9, latencyNs, 0)

def AddLatencyNs(builder, latencyNs):
    ModelResponseAddLatencyNs(builder, latencyNs)

def ModelResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return ModelResponseEnd(builder)
