# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ModelRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ModelRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsModelRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ModelRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ModelRequest
    def RunId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ModelRequest
    def SpanId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ModelRequest
    def ParentSpanId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ModelRequest
    def Layer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ModelRequest
    def Provider(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ModelRequest
    def Model(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ModelRequest
    def RequestBody(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ModelRequest
    def Attempt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ModelRequestStart(builder):
    builder.StartObject(8)

def Start(builder):
    ModelRequestStart(builder)

def ModelRequestAddRunId(builder, runId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(runId), 0)

def AddRunId(builder, runId):
    ModelRequestAddRunId(builder, runId)

def ModelRequestAddSpanId(builder, spanId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(spanId), 0)

def AddSpanId(builder, spanId):
    ModelRequestAddSpanId(builder, spanId)

def ModelRequestAddParentSpanId(builder, parentSpanId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(parentSpanId), 0)

def AddParentSpanId(builder, parentSpanId):
    ModelRequestAddParentSpanId(builder, parentSpanId)

def ModelRequestAddLayer(builder, layer):
    builder.PrependInt8Slot(3, layer, 0)

def AddLayer(builder, layer):
    ModelRequestAddLayer(builder, layer)

def ModelRequestAddProvider(builder, provider):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(provider), 0)

def AddProvider(builder, provider):
    ModelRequestAddProvider(builder, provider)

def ModelRequestAddModel(builder, model):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(model), 0)

def AddModel(builder, model):
    ModelRequestAddModel(builder, model)

def ModelRequestAddRequestBody(builder, requestBody):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(requestBody), 0)

def AddRequestBody(builder, requestBody):
    ModelRequestAddRequestBody(builder, requestBody)

def ModelRequestAddAttempt(builder, attempt):
    builder.PrependUint32Slot(7, attempt, 0)

def AddAttempt(builder, attempt):
    ModelRequestAddAttempt(builder, attempt)

def ModelRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return ModelRequestEnd(builder)
