# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RetryMarker(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RetryMarker()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRetryMarker(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RetryMarker
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RetryMarker
    def RunId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RetryMarker
    def SpanId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RetryMarker
    def RetryOfSpanId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RetryMarker
    def Attempt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # RetryMarker
    def Reason(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def RetryMarkerStart(builder):
    builder.StartObject(5)

def Start(builder):
    RetryMarkerStart(builder)

def RetryMarkerAddRunId(builder, runId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(runId), 0)

def AddRunId(builder, runId):
    RetryMarkerAddRunId(builder, runId)

def RetryMarkerAddSpanId(builder, spanId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(spanId), 0)

def AddSpanId(builder, spanId):
    RetryMarkerAddSpanId(builder, spanId)

def RetryMarkerAddRetryOfSpanId(builder, retryOfSpanId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(retryOfSpanId), 0)

def AddRetryOfSpanId(builder, retryOfSpanId):
    RetryMarkerAddRetryOfSpanId(builder, retryOfSpanId)

def RetryMarkerAddAttempt(builder, attempt):
    builder.PrependUint32Slot(3, attempt, 0)

def AddAttempt(builder, attempt):
    RetryMarkerAddAttempt(builder, attempt)

def RetryMarkerAddReason(builder, reason):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(reason), 0)

def AddReason(builder, reason):
    RetryMarkerAddReason(builder, reason)

def RetryMarkerEnd(builder):
    return builder.EndObject()

def End(builder):
    return RetryMarkerEnd(builder)
