# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RunBegin(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RunBegin()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRunBegin(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RunBegin
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RunBegin
    def RunId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunBegin
    def Command(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunBegin
    def Runtime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunBegin
    def SupervisorVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunBegin
    def SchemaVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def RunBeginStart(builder):
    builder.StartObject(5)

def Start(builder):
    RunBeginStart(builder)

def RunBeginAddRunId(builder, runId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(runId), 0)

def AddRunId(builder, runId):
    RunBeginAddRunId(builder, runId)

def RunBeginAddCommand(builder, command):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(command), 0)

def AddCommand(builder, command):
    RunBeginAddCommand(builder, command)

def RunBeginAddRuntime(builder, runtime):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(runtime), 0)

def AddRuntime(builder, runtime):
    RunBeginAddRuntime(builder, runtime)

def RunBeginAddSupervisorVersion(builder, supervisorVersion):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(supervisorVersion), 0)

def AddSupervisorVersion(builder, supervisorVersion):
    RunBeginAddSupervisorVersion(builder, supervisorVersion)

def RunBeginAddSchemaVersion(builder, schemaVersion):
    builder.PrependUint32Slot(4, schemaVersion, 0)

def AddSchemaVersion(builder, schemaVersion):
    RunBeginAddSchemaVersion(builder, schemaVersion)

def RunBeginEnd(builder):
    return builder.EndObject()

def End(builder):
    return RunBeginEnd(builder)
