# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RunEnd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RunEnd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRunEnd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RunEnd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RunEnd
    def RunId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunEnd
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # RunEnd
    def ExitCode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def RunEndStart(builder):
    builder.StartObject(3)

def Start(builder):
    RunEndStart(builder)

def RunEndAddRunId(builder, runId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(runId), 0)

def AddRunId(builder, runId):
    RunEndAddRunId(builder, runId)

def RunEndAddStatus(builder, status):
    builder.PrependInt8Slot(1, status, 0)

def AddStatus(builder, status):
    RunEndAddStatus(builder, status)

def RunEndAddExitCode(builder, exitCode):
    builder.PrependInt32Slot(2, exitCode, 0)

def AddExitCode(builder, exitCode):
    RunEndAddExitCode(builder, exitCode)

def RunEndEnd(builder):
    return builder.EndObject()

def End(builder):
    return RunEndEnd(builder)
