# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RunProgress(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RunProgress()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRunProgress(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RunProgress
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RunProgress
    def RunId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunProgress
    def Phase(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunProgress
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunProgress
    def Severity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunProgress
    def Pct(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RunProgress
    def Detail(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunProgress
    def Signal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunProgress
    def NextAction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunProgress
    def WorkspaceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunProgress
    def ProfileId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunProgress
    def ProfileRoot(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunProgress
    def EntityType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunProgress
    def EntityId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunProgress
    def EntityRoot(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def RunProgressStart(builder):
    builder.StartObject(14)

def Start(builder):
    RunProgressStart(builder)

def RunProgressAddRunId(builder, runId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(runId), 0)

def AddRunId(builder, runId):
    RunProgressAddRunId(builder, runId)

def RunProgressAddPhase(builder, phase):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(phase), 0)

def AddPhase(builder, phase):
    RunProgressAddPhase(builder, phase)

def RunProgressAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder, message):
    RunProgressAddMessage(builder, message)

def RunProgressAddSeverity(builder, severity):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(severity), 0)

def AddSeverity(builder, severity):
    RunProgressAddSeverity(builder, severity)

def RunProgressAddPct(builder, pct):
    builder.PrependInt32Slot(4, pct, 0)

def AddPct(builder, pct):
    RunProgressAddPct(builder, pct)

def RunProgressAddDetail(builder, detail):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(detail), 0)

def AddDetail(builder, detail):
    RunProgressAddDetail(builder, detail)

def RunProgressAddSignal(builder, signal):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(signal), 0)

def AddSignal(builder, signal):
    RunProgressAddSignal(builder, signal)

def RunProgressAddNextAction(builder, nextAction):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(nextAction), 0)

def AddNextAction(builder, nextAction):
    RunProgressAddNextAction(builder, nextAction)

def RunProgressAddWorkspaceId(builder, workspaceId):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(workspaceId), 0)

def AddWorkspaceId(builder, workspaceId):
    RunProgressAddWorkspaceId(builder, workspaceId)

def RunProgressAddProfileId(builder, profileId):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(profileId), 0)

def AddProfileId(builder, profileId):
    RunProgressAddProfileId(builder, profileId)

def RunProgressAddProfileRoot(builder, profileRoot):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(profileRoot), 0)

def AddProfileRoot(builder, profileRoot):
    RunProgressAddProfileRoot(builder, profileRoot)

def RunProgressAddEntityType(builder, entityType):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(entityType), 0)

def AddEntityType(builder, entityType):
    RunProgressAddEntityType(builder, entityType)

def RunProgressAddEntityId(builder, entityId):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(entityId), 0)

def AddEntityId(builder, entityId):
    RunProgressAddEntityId(builder, entityId)

def RunProgressAddEntityRoot(builder, entityRoot):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(entityRoot), 0)

def AddEntityRoot(builder, entityRoot):
    RunProgressAddEntityRoot(builder, entityRoot)

def RunProgressEnd(builder):
    return builder.EndObject()

def End(builder):
    return RunProgressEnd(builder)
