# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ToolCall(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ToolCall()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsToolCall(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ToolCall
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ToolCall
    def RunId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ToolCall
    def SpanId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ToolCall
    def ParentSpanId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ToolCall
    def Layer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ToolCall
    def ToolName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ToolCall
    def Input(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ToolCallStart(builder):
    builder.StartObject(6)

def Start(builder):
    ToolCallStart(builder)

def ToolCallAddRunId(builder, runId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(runId), 0)

def AddRunId(builder, runId):
    ToolCallAddRunId(builder, runId)

def ToolCallAddSpanId(builder, spanId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(spanId), 0)

def AddSpanId(builder, spanId):
    ToolCallAddSpanId(builder, spanId)

def ToolCallAddParentSpanId(builder, parentSpanId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(parentSpanId), 0)

def AddParentSpanId(builder, parentSpanId):
    ToolCallAddParentSpanId(builder, parentSpanId)

def ToolCallAddLayer(builder, layer):
    builder.PrependInt8Slot(3, layer, 0)

def AddLayer(builder, layer):
    ToolCallAddLayer(builder, layer)

def ToolCallAddToolName(builder, toolName):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(toolName), 0)

def AddToolName(builder, toolName):
    ToolCallAddToolName(builder, toolName)

def ToolCallAddInput(builder, input):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(input), 0)

def AddInput(builder, input):
    ToolCallAddInput(builder, input)

def ToolCallEnd(builder):
    return builder.EndObject()

def End(builder):
    return ToolCallEnd(builder)
