# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ToolResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ToolResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsToolResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ToolResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ToolResult
    def RunId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ToolResult
    def SpanId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ToolResult
    def Layer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ToolResult
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ToolResult
    def Output(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ToolResult
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ToolResult
    def LatencyNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def ToolResultStart(builder):
    builder.StartObject(7)

def Start(builder):
    ToolResultStart(builder)

def ToolResultAddRunId(builder, runId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(runId), 0)

def AddRunId(builder, runId):
    ToolResultAddRunId(builder, runId)

def ToolResultAddSpanId(builder, spanId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(spanId), 0)

def AddSpanId(builder, spanId):
    ToolResultAddSpanId(builder, spanId)

def ToolResultAddLayer(builder, layer):
    builder.PrependInt8Slot(2, layer, 0)

def AddLayer(builder, layer):
    ToolResultAddLayer(builder, layer)

def ToolResultAddStatus(builder, status):
    builder.PrependInt8Slot(3, status, 0)

def AddStatus(builder, status):
    ToolResultAddStatus(builder, status)

def ToolResultAddOutput(builder, output):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(output), 0)

def AddOutput(builder, output):
    ToolResultAddOutput(builder, output)

def ToolResultAddError(builder, error):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def AddError(builder, error):
    ToolResultAddError(builder, error)

def ToolResultAddLatencyNs(builder, latencyNs):
    builder.PrependInt64Slot(6, latencyNs, 0)

def AddLatencyNs(builder, latencyNs):
    ToolResultAddLatencyNs(builder, latencyNs)

def ToolResultEnd(builder):
    return builder.EndObject()

def End(builder):
    return ToolResultEnd(builder)
