from __future__ import annotations
import pykungfu.yijinjing.enums
import pykungfu.yijinjing.types
import typing
import typing_extensions
__all__: list[str] = ['CONTENT_HASH_ALGORITHM_BLAKE3', 'CONTENT_HASH_ALGORITHM_SHA256', 'DEFAULT_FRAME_CHECKSUM_ALGORITHM', 'DEFAULT_FRAME_INTEGRITY_VERSION', 'FAST_HASH_ALGORITHM', 'FRAME_CHECKSUM_ALGORITHM_CRC32C', 'FRAME_CHECKSUM_ALGORITHM_FNV1A64', 'FRAME_INTEGRITY_VERSION_V1', 'FRAME_INTEGRITY_VERSION_V2', 'PUBLISH', 'PULL', 'PUSH', 'REPLY', 'REQUEST', 'SUBSCRIBE', 'action_record_options', 'action_record_receipt', 'action_recorder', 'apprentice', 'assemble', 'bus', 'calendar_day_start', 'checksum_payload', 'color_print', 'compile_schema', 'compute_content_hash', 'compute_content_hash_value', 'copy_sink', 'emit_log', 'event', 'fast_hash_32', 'fast_hash_str_32', 'format_content_hash', 'frame', 'frame_checksum_algorithm_for_integrity_version', 'frame_integrity_version_for_checksum_algorithm', 'get_page_path', 'hash_32', 'hash_str_32', 'history_window_start', 'in_color_terminal', 'io_device', 'is_supported_content_hash_algorithm', 'is_supported_frame_checksum_algorithm', 'location', 'locator', 'master', 'nano_hashed', 'next_minute', 'next_session_boundary', 'noop_publisher', 'normalize_content_hash_algorithm', 'now_in_nano', 'null_sink', 'observer', 'parse_content_hash', 'profile', 'protocol', 'publisher', 'reader', 'session_builder', 'session_finder', 'session_window_start', 'setup_log', 'sink', 'socket', 'strfnow', 'strftime', 'strptime', 'thread_id', 'today_start', 'verify_content_hash', 'writer']
class action_record_options:
    chain_to_last: bool
    data_type: pykungfu.yijinjing.enums.FrameDataType
    gen_time: int
    parent_frame_uid: int
    stream_id: int
    trigger_time: int
    def __init__(self) -> None:
        ...
class action_record_receipt:
    @property
    def carrier_type(self) -> int:
        ...
    @property
    def checksum_algorithm(self) -> str:
        ...
    @property
    def data_length(self) -> int:
        ...
    @property
    def data_type(self) -> int:
        ...
    @property
    def dest(self) -> int:
        ...
    @property
    def frame_checksum(self) -> int:
        ...
    @property
    def frame_uid(self) -> int:
        ...
    @property
    def gen_time(self) -> int:
        ...
    @property
    def initial_source(self) -> int:
        ...
    @property
    def integrity_version(self) -> int:
        ...
    @property
    def payload_checksum(self) -> int:
        ...
    @property
    def source(self) -> int:
        ...
    @property
    def stream_id(self) -> int:
        ...
    @property
    def trigger_frame_uid(self) -> int:
        ...
    @property
    def trigger_time(self) -> int:
        ...
class action_recorder:
    def __init__(self, runtime_dir: str, group: str, name: str, dest_id: int = 0, stream_id: int = 0) -> None:
        ...
    def mark(self, carrier_type: int, options: action_record_options = ...) -> action_record_receipt:
        ...
    def record_bytes(self, carrier_type: int, payload: bytes, options: action_record_options = ...) -> action_record_receipt:
        ...
    def record_json(self, carrier_type: int, json_payload: str, options: action_record_options = ...) -> action_record_receipt:
        ...
    @property
    def last_frame_uid(self) -> int:
        ...
class apprentice:
    def __init__(self, home: location, low_latency: bool = False, arguments: str = '{}') -> None:
        ...
    def get_begin_time(self) -> int:
        ...
    def get_end_time(self) -> int:
        ...
    def get_home_uid(self) -> int:
        ...
    def get_home_uname(self) -> str:
        ...
    def get_location(self, arg0: int) -> location:
        ...
    def get_writer(self, arg0: int) -> writer:
        ...
    def has_writer(self, arg0: int) -> bool:
        ...
    def is_live(self) -> bool:
        ...
    def is_started(self) -> bool:
        ...
    def now(self) -> int:
        ...
    def on_exit(self) -> None:
        ...
    def pre_setup(self) -> None:
        ...
    def run(self, step_limit: int = 0) -> None:
        ...
    def set_begin_time(self, arg0: int) -> None:
        ...
    def set_end_time(self, arg0: int) -> None:
        ...
    def setup(self) -> bool:
        ...
    def step(self, arg0: int) -> None:
        ...
    @property
    def home(self) -> location:
        ...
    @property
    def io_device(self) -> io_device:
        ...
    @property
    def live(self) -> bool:
        ...
class assemble:
    @typing.overload
    def __init__(self, locators: list[locator], mode: str = '*', role: str = '*', group: str = '*', name: str = '*') -> None:
        ...
    @typing.overload
    def __init__(self, source_location: location, dest_id: int, assemble_mode: int = 1, from_time: int = 0) -> None:
        ...
    def __plus__(self, arg0: assemble) -> assemble:
        ...
    def __rshift__(self, arg0: sink) -> None:
        ...
    def read_bytes(self, carrier_type: int, end_time: int = 9223372036854775807) -> list[tuple[pykungfu.yijinjing.types.frame_header, list[int]]]:
        ...
    def read_headers(self, carrier_type: int, end_time: int = 9223372036854775807) -> list[pykungfu.yijinjing.types.frame_header]:
        ...
class bus:
    def __init__(self, arg0: bool) -> None:
        ...
    def on_load_page(self) -> None:
        ...
class copy_sink(sink):
    def __init__(self, arg0: locator) -> None:
        ...
    def put(self, arg0: location, arg1: int, arg2: frame) -> None:
        ...
class event:
    def to_string(self) -> str:
        ...
    @property
    def carrier_type(self) -> int:
        ...
    @property
    def data_as_byte_array(self) -> list[int]:
        ...
    @property
    def data_as_bytes(self) -> str:
        ...
    @property
    def data_as_string(self) -> str:
        ...
    @property
    def data_length(self) -> int:
        ...
    @property
    def data_type(self) -> int:
        ...
    @property
    def dest(self) -> int:
        ...
    @property
    def frame_uid(self) -> int:
        ...
    @property
    def gen_time(self) -> int:
        ...
    @property
    def initial_source(self) -> int:
        ...
    @property
    def is_json(self) -> bool:
        ...
    @property
    def source(self) -> int:
        ...
    @property
    def stream_id(self) -> int:
        ...
    @property
    def trigger_frame_uid(self) -> int:
        ...
    @property
    def trigger_time(self) -> int:
        ...
class frame(event):
    def has_data(self) -> bool:
        ...
    @property
    def frame_length(self) -> int:
        ...
class io_device:
    def __init__(self, home: location, low_latency: bool = False, lazy: bool = True) -> None:
        ...
    def is_usable(self) -> bool:
        ...
    def open_reader(self, arg0: location, arg1: int) -> reader:
        ...
    def open_reader_to_subscribe(self) -> reader:
        ...
    def open_writer(self, arg0: int, arg1: int) -> writer:
        ...
    def setup(self) -> bool:
        ...
    @property
    def bus(self) -> bus:
        ...
    @property
    def home(self) -> location:
        ...
    @property
    def live_home(self) -> location:
        ...
    @property
    def observer(self) -> observer:
        ...
    @property
    def publisher(self) -> publisher:
        ...
class location:
    def __init__(self, m: pykungfu.yijinjing.enums.mode, c: pykungfu.yijinjing.enums.location_role, g: str, n: str, l: ..., default_seed: int = 42) -> None:
        ...
    def __repr__(self) -> str:
        ...
    @typing.overload
    def to(self, arg0: pykungfu.yijinjing.types.Config) -> pykungfu.yijinjing.types.Config:
        ...
    @typing.overload
    def to(self, arg0: pykungfu.yijinjing.types.Register) -> pykungfu.yijinjing.types.Register:
        ...
    @typing.overload
    def to(self, arg0: pykungfu.yijinjing.types.Deregister) -> pykungfu.yijinjing.types.Deregister:
        ...
    @typing.overload
    def to(self, arg0: pykungfu.yijinjing.types.Location) -> pykungfu.yijinjing.types.Location:
        ...
    @property
    def group(self) -> str:
        ...
    @property
    def locator(self) -> ...:
        ...
    @property
    def mode(self) -> pykungfu.yijinjing.enums.mode:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def role(self) -> pykungfu.yijinjing.enums.location_role:
        ...
    @property
    def uid(self) -> int:
        ...
    @property
    def uname(self) -> str:
        ...
class locator:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: str) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: str, arg1: pykungfu.yijinjing.enums.mode) -> None:
        ...
    @typing.overload
    def __init__(self, mode: pykungfu.yijinjing.enums.mode, tags: list[str] = []) -> None:
        ...
    def get_env(self, arg0: str) -> str:
        ...
    def get_root(self) -> str:
        ...
    def has_env(self, arg0: str) -> bool:
        ...
    def layout_dir(self, arg0: location, arg1: pykungfu.yijinjing.enums.layout, arg2: bool) -> str:
        ...
    def layout_file(self, arg0: location, arg1: pykungfu.yijinjing.enums.layout, arg2: str) -> str:
        ...
    def list_location_dest(self, arg0: location) -> list[int]:
        ...
    def list_locations(self, role: str = '*', group: str = '*', name: str = '*', mode: str = '*') -> list[location]:
        ...
    def list_page_id(self, arg0: location, arg1: int) -> list[int]:
        ...
class master:
    def __init__(self, home: location, low_latency: bool = False) -> None:
        ...
    def check_register(self, arg0: int, arg1: pykungfu.yijinjing.types.Register) -> bool:
        ...
    def deregister_app(self, arg0: int, arg1: int) -> None:
        ...
    def get_begin_time(self) -> int:
        ...
    def get_end_time(self) -> int:
        ...
    def get_home_uid(self) -> int:
        ...
    def get_home_uname(self) -> str:
        ...
    def is_live(self) -> bool:
        ...
    def now(self) -> int:
        ...
    def on_exit(self) -> None:
        ...
    def on_interval_check(self, arg0: int) -> None:
        ...
    def on_register(self, arg0: int, arg1: pykungfu.yijinjing.types.Register) -> None:
        ...
    def pre_setup(self) -> None:
        ...
    def run(self, step_limit: int = 0) -> None:
        ...
    def setup(self) -> bool:
        ...
    def step(self, arg0: int) -> None:
        ...
    @property
    def home(self) -> location:
        ...
    @property
    def io_device(self) -> io_device:
        ...
    @property
    def live(self) -> bool:
        ...
class noop_publisher(publisher):
    def __init__(self) -> None:
        ...
class null_sink(sink):
    def __init__(self) -> None:
        ...
class observer:
    def get_notice(self) -> str:
        ...
    def wait(self) -> bool:
        ...
class profile:
    def __init__(self, arg0: locator) -> None:
        ...
    @typing.overload
    def get(self, arg0: pykungfu.yijinjing.types.Config) -> pykungfu.yijinjing.types.Config:
        ...
    @typing.overload
    def get(self, arg0: pykungfu.yijinjing.types.Location) -> pykungfu.yijinjing.types.Location:
        ...
    @typing.overload
    def get_all(self, arg0: pykungfu.yijinjing.types.Config) -> list[pykungfu.yijinjing.types.Config]:
        ...
    @typing.overload
    def get_all(self, arg0: pykungfu.yijinjing.types.Location) -> list[pykungfu.yijinjing.types.Location]:
        ...
    @typing.overload
    def remove(self, arg0: pykungfu.yijinjing.types.Config) -> None:
        ...
    @typing.overload
    def remove(self, arg0: pykungfu.yijinjing.types.Location) -> None:
        ...
    @typing.overload
    def set(self, arg0: pykungfu.yijinjing.types.Config) -> None:
        ...
    @typing.overload
    def set(self, arg0: pykungfu.yijinjing.types.Location) -> None:
        ...
class protocol:
    """
    Nanomsg Protocol

    Members:

      REPLY

      REQUEST

      PUSH

      PULL

      PUBLISH

      SUBSCRIBE
    """
    PUBLISH: typing.ClassVar[protocol]  # value = <protocol.PUBLISH: 4>
    PULL: typing.ClassVar[protocol]  # value = <protocol.PULL: 3>
    PUSH: typing.ClassVar[protocol]  # value = <protocol.PUSH: 2>
    REPLY: typing.ClassVar[protocol]  # value = <protocol.REPLY: 0>
    REQUEST: typing.ClassVar[protocol]  # value = <protocol.REQUEST: 1>
    SUBSCRIBE: typing.ClassVar[protocol]  # value = <protocol.SUBSCRIBE: 5>
    __members__: typing.ClassVar[dict[str, protocol]]  # value = {'REPLY': <protocol.REPLY: 0>, 'REQUEST': <protocol.REQUEST: 1>, 'PUSH': <protocol.PUSH: 2>, 'PULL': <protocol.PULL: 3>, 'PUBLISH': <protocol.PUBLISH: 4>, 'SUBSCRIBE': <protocol.SUBSCRIBE: 5>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __ge__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __gt__(self, other: typing.Any) -> bool:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __le__(self, other: typing.Any) -> bool:
        ...
    def __lt__(self, other: typing.Any) -> bool:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class publisher:
    def notify(self) -> int:
        ...
    def publish(self, arg0: str, arg1: int, arg2: bool) -> int:
        ...
class reader:
    @typing.overload
    def __init__(self, arg0: bool, arg1: bool, arg2: ...) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: reader) -> None:
        ...
    def current_frame(self) -> frame:
        ...
    def data_available(self) -> bool:
        ...
    def disjoin(self, arg0: location) -> None:
        ...
    def disjoin_channel(self, arg0: location, arg1: int) -> None:
        ...
    def join(self, location: location, dest_id: int, from_time: int, page_size: int = 0, priority: pykungfu.yijinjing.enums.Priority = ...) -> None:
        ...
    def next(self) -> None:
        ...
    def seek_to_time(self, arg0: int) -> None:
        ...
    def subscribe(self, arg0: location, arg1: int, arg2: int, arg3: int, arg4: pykungfu.yijinjing.enums.Priority) -> None:
        ...
class session_builder(session_finder):
    def __init__(self, arg0: io_device) -> None:
        ...
    def rebuild_index_db(self) -> None:
        ...
    def update_index_db(self) -> None:
        ...
class session_finder:
    def __init__(self, arg0: io_device) -> None:
        ...
    def find_sessions(self, from_: int = 0, to: int = 9223372036854775807) -> list[pykungfu.yijinjing.types.Session]:
        ...
    def find_sessions_for(self, source: location, from_: int = 0, to: int = 9223372036854775807) -> list[pykungfu.yijinjing.types.Session]:
        ...
class sink:
    def __init__(self) -> None:
        ...
    def close(self) -> None:
        ...
    def find_page_size(self, arg0: location, arg1: int) -> int:
        ...
    def put(self, arg0: location, arg1: int, arg2: frame) -> None:
        ...
    @property
    def bus(self) -> bus:
        ...
    @property
    def publisher(self) -> publisher:
        ...
class socket:
    def __init__(self, protocol: protocol) -> None:
        ...
    def close(self) -> None:
        ...
    def dial(self, url: str, flags: int = 0) -> int:
        ...
    @typing.overload
    def getsockopt(self, option: str) -> int:
        ...
    @typing.overload
    def getsockopt(self, option: str) -> int:
        ...
    def last_message(self) -> str:
        ...
    def listen(self, url: str, flags: int = 0) -> int:
        ...
    def recv(self, flags: int = 0) -> str:
        ...
    def send(self, msg: str, flags: int = 0, no_exception: bool = False) -> int:
        ...
    @typing.overload
    def setsockopt(self, option: str, value: str) -> None:
        ...
    @typing.overload
    def setsockopt(self, option: str, value: int) -> None:
        ...
    @typing.overload
    def setsockopt(self, option: str, value: int) -> None:
        ...
class writer:
    def __init__(self, arg0: location, arg1: int, arg2: bool, arg3: publisher, arg4: bool, arg5: bus, arg6: int) -> None:
        ...
    def copy_frame(self, arg0: frame) -> None:
        ...
    def current_frame_uid(self) -> int:
        ...
    def get_dest(self) -> int:
        ...
    def get_location(self) -> location:
        ...
    def mark(self, arg0: int, arg1: int) -> None:
        ...
    def mark_at(self, arg0: int, arg1: int, arg2: int) -> None:
        ...
    def write_bytes(self, arg0: int, arg1: int, arg2: list[int], arg3: int) -> None:
        ...
def calendar_day_start(arg0: int) -> int:
    ...
def checksum_payload(payload: typing_extensions.Buffer, algorithm: str = 'crc32c') -> int:
    ...
def color_print(arg0: str, arg1: str) -> None:
    ...
def compile_schema(fbs_text: str, sandboxed: bool = False) -> tuple:
    ...
def compute_content_hash(payload: typing_extensions.Buffer, algorithm: str = 'sha256') -> str:
    ...
def compute_content_hash_value(payload: typing_extensions.Buffer, algorithm: str = 'sha256') -> str:
    ...
def emit_log(arg0: str, arg1: int, arg2: str, arg3: str, arg4: int, arg5: str) -> None:
    ...
def fast_hash_32(key: int, length: int, seed: int = 42) -> int:
    ...
def fast_hash_str_32(key: str, seed: int = 42) -> int:
    ...
def format_content_hash(algorithm: str, value: str) -> str:
    ...
def frame_checksum_algorithm_for_integrity_version(integrity_version: int) -> str:
    ...
def frame_integrity_version_for_checksum_algorithm(algorithm: str) -> int:
    ...
def get_page_path(arg0: ..., arg1: int, arg2: int) -> str:
    ...
def hash_32(key: int, length: int, seed: int = 42) -> int:
    ...
def hash_str_32(key: str, seed: int = 42) -> int:
    ...
def history_window_start() -> int:
    ...
def in_color_terminal() -> bool:
    ...
def is_supported_content_hash_algorithm(algorithm: str) -> bool:
    ...
def is_supported_frame_checksum_algorithm(algorithm: str) -> bool:
    ...
def nano_hashed(arg0: int) -> int:
    ...
def next_minute(arg0: int) -> int:
    ...
def next_session_boundary(arg0: int) -> int:
    ...
def normalize_content_hash_algorithm(algorithm: str) -> str:
    ...
def now_in_nano() -> int:
    ...
def parse_content_hash(formatted: str) -> tuple:
    ...
def session_window_start() -> int:
    ...
def setup_log(arg0: ..., arg1: str) -> str:
    ...
def strfnow(format: str = '%F %T.%N') -> str:
    ...
def strftime(nanotime: int, format: str = '%F %T.%N') -> str:
    ...
def strptime(timestr: str, format: str = '%F %T.%N') -> int:
    ...
def thread_id() -> int:
    ...
def today_start() -> int:
    ...
def verify_content_hash(payload: typing_extensions.Buffer, expected: str, algorithm: str = '') -> bool:
    ...
CONTENT_HASH_ALGORITHM_BLAKE3: str = 'blake3'
CONTENT_HASH_ALGORITHM_SHA256: str = 'sha256'
DEFAULT_FRAME_CHECKSUM_ALGORITHM: str = 'crc32c'
DEFAULT_FRAME_INTEGRITY_VERSION: int = 2
FAST_HASH_ALGORITHM: str = 'murmur3'
FRAME_CHECKSUM_ALGORITHM_CRC32C: str = 'crc32c'
FRAME_CHECKSUM_ALGORITHM_FNV1A64: str = 'fnv1a64'
FRAME_INTEGRITY_VERSION_V1: int = 1
FRAME_INTEGRITY_VERSION_V2: int = 2
PUBLISH: protocol  # value = <protocol.PUBLISH: 4>
PULL: protocol  # value = <protocol.PULL: 3>
PUSH: protocol  # value = <protocol.PUSH: 2>
REPLY: protocol  # value = <protocol.REPLY: 0>
REQUEST: protocol  # value = <protocol.REQUEST: 1>
SUBSCRIBE: protocol  # value = <protocol.SUBSCRIBE: 5>
