# SPDX-License-Identifier: Apache-2.0

"""Compatibility facade for Dogfood Feedback domain responsibilities."""

from __future__ import annotations

# Preserve the historical module import surface while implementations live in
# bounded responsibility modules.
import re
import time
from collections.abc import Iterable, Mapping
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from kungfu import workspace_federation
from kungfu.storage import service as storage_service
from kungfu.workspace import WorkspaceIdentity, semantic_root

from ._dogfood_records import (
    ALLOWED_DISPOSITIONS,
    CANONICAL_IMPACTS,
    CONSIDERATION_SCHEMA,
    CONSIDERATION_STAGES,
    CONSIDERATION_SURFACE_ID,
    CONTRACT_VERSION,
    CONTRACT_WORLD_ID,
    DIMENSIONS,
    DIMENSION_WEIGHTS,
    FINDING_SCHEMA,
    FINDING_SURFACE_ID,
    GATE_SCHEMA,
    HARD_CLASSES,
    HEALTH_SCHEMA,
    IMPACT_ALIASES,
    ISSUE_PROPOSAL_SCHEMA,
    ISSUE_SCHEMA,
    ISSUE_SURFACE_ID,
    ISSUE_TRANSITIONS,
    LOOKUP_SCHEMA,
    POLICY_VERSION,
    PROFILE_ID,
    QUERY_SCHEMA,
    RECONCILIATION_SCHEMA,
    RUNTIME_SURFACES,
    SOURCE_ID,
    STARVATION_SCHEMA,
    _ROOT,
    _SENSITIVE_KEY,
    _STABLE_ID,
    _content_root,
    _dimension_map,
    _normalize_impact,
    _observation_id,
    _one_record,
    _parse_time,
    _privacy_safe,
    _put,
    _records,
    _root,
    _source,
    _stable_id,
    _text,
    _utc_now,
    capabilities,
)
from ._dogfood_policy import (
    _assignment_dimensions,
    _candidate_relevance,
    consideration_gate,
    evaluate_starvation,
    health_projection,
    record_consideration,
    relevance_query,
    starvation_projection,
)
from ._dogfood_query import (
    _component,
    _dimension_tokens,
    _finding_cluster,
    _finding_cluster_score,
    _logical_finding_key,
    federated_query,
    local_lookup,
    local_projection,
    propose_issue,
    reconcile_issue,
)
from ._dogfood_records import admit_issue, capture_finding, transition_issue

__all__ = [
    "ALLOWED_DISPOSITIONS",
    "Any",
    "CANONICAL_IMPACTS",
    "CONSIDERATION_SCHEMA",
    "CONSIDERATION_STAGES",
    "CONSIDERATION_SURFACE_ID",
    "CONTRACT_VERSION",
    "CONTRACT_WORLD_ID",
    "DIMENSIONS",
    "DIMENSION_WEIGHTS",
    "FINDING_SCHEMA",
    "FINDING_SURFACE_ID",
    "GATE_SCHEMA",
    "HARD_CLASSES",
    "HEALTH_SCHEMA",
    "IMPACT_ALIASES",
    "ISSUE_PROPOSAL_SCHEMA",
    "ISSUE_SCHEMA",
    "ISSUE_SURFACE_ID",
    "ISSUE_TRANSITIONS",
    "Iterable",
    "LOOKUP_SCHEMA",
    "Mapping",
    "POLICY_VERSION",
    "PROFILE_ID",
    "Path",
    "QUERY_SCHEMA",
    "RECONCILIATION_SCHEMA",
    "RUNTIME_SURFACES",
    "SOURCE_ID",
    "STARVATION_SCHEMA",
    "WorkspaceIdentity",
    "_ROOT",
    "_SENSITIVE_KEY",
    "_STABLE_ID",
    "_assignment_dimensions",
    "_candidate_relevance",
    "_component",
    "_content_root",
    "_dimension_map",
    "_dimension_tokens",
    "_finding_cluster",
    "_finding_cluster_score",
    "_logical_finding_key",
    "_normalize_impact",
    "_observation_id",
    "_one_record",
    "_parse_time",
    "_privacy_safe",
    "_put",
    "_records",
    "_root",
    "_source",
    "_stable_id",
    "_text",
    "_utc_now",
    "admit_issue",
    "capabilities",
    "capture_finding",
    "consideration_gate",
    "datetime",
    "evaluate_starvation",
    "federated_query",
    "health_projection",
    "local_lookup",
    "local_projection",
    "propose_issue",
    "re",
    "reconcile_issue",
    "record_consideration",
    "relevance_query",
    "semantic_root",
    "starvation_projection",
    "storage_service",
    "time",
    "timezone",
    "transition_issue",
    "workspace_federation",
]
