# SPDX-License-Identifier: Apache-2.0

"""Stable facade for runtime image and Product Release Cut responsibilities."""

from __future__ import annotations

import copy as copy
import re as re
import shutil as shutil
from collections.abc import Sequence as Sequence

from kungfu.coordination import locks as coordination_locks  # noqa: F401

from kungfu._runtime_upgrade.common import (
    hashlib as hashlib,
    json as json,
    os as os,
    time as time,
    Mapping as Mapping,
    Path as Path,
    Any as Any,
    MANIFEST_SCHEMA as MANIFEST_SCHEMA,
    IMAGE_SCHEMA as IMAGE_SCHEMA,
    REFERENCE_SCHEMA as REFERENCE_SCHEMA,
    PLAN_SCHEMA as PLAN_SCHEMA,
    RECEIPT_SCHEMA as RECEIPT_SCHEMA,
    GC_PLAN_SCHEMA as GC_PLAN_SCHEMA,
    MESSAGE_SCHEMA as MESSAGE_SCHEMA,
    LEGACY_BOOTSTRAP_MODE as LEGACY_BOOTSTRAP_MODE,
    UpgradeError as UpgradeError,
    _contract as _contract,
    _validate as _validate,
    _canonical as _canonical,
    _stable_id as _stable_id,
    manifest_digest as manifest_digest,
    tree_digest as tree_digest,
    inventory_root as inventory_root,
    _state_root as _state_root,
    _image_root as _image_root,
    _write_json as _write_json,
    _read_json as _read_json,
)
from kungfu._runtime_upgrade.release_cut import (
    RELEASE_CUT_SCHEMA as RELEASE_CUT_SCHEMA,
    PLATFORM_SLICE_SCHEMA as PLATFORM_SLICE_SCHEMA,
    CUT_TRANSITION_SCHEMA as CUT_TRANSITION_SCHEMA,
    CUT_DECISION_SCHEMA as CUT_DECISION_SCHEMA,
    _ROOT as _ROOT,
    _SEMVER as _SEMVER,
    _PLATFORMS as _PLATFORMS,
    _ARCHITECTURES as _ARCHITECTURES,
    _RELATIONS as _RELATIONS,
    _PUBLIC_AUTHORIZATIONS as _PUBLIC_AUTHORIZATIONS,
    _LOCAL_AUTHORIZATIONS as _LOCAL_AUTHORIZATIONS,
    _MANIFEST_CUT_FIELDS as _MANIFEST_CUT_FIELDS,
    ReleaseCutError as ReleaseCutError,
    canonical_json_bytes as canonical_json_bytes,
    content_root as content_root,
    manifest_identity_root as manifest_identity_root,
    _require_exact_fields as _require_exact_fields,
    _require_string as _require_string,
    _require_root as _require_root,
    _root_list as _root_list,
    validate_platform_slice as validate_platform_slice,
    finish_platform_slice as finish_platform_slice,
    validate_release_cut as validate_release_cut,
    finish_release_cut as finish_release_cut,
    validate_cut_transition as validate_cut_transition,
    finish_cut_transition as finish_cut_transition,
    build_shifu_local_transition as build_shifu_local_transition,
    is_legacy_bootstrap as is_legacy_bootstrap,
    legacy_coordinate as legacy_coordinate,
    image_coordinate as image_coordinate,
    legacy_selection_is_bound as legacy_selection_is_bound,
    manifest_compatibility as manifest_compatibility,
    shifu_local_transition as shifu_local_transition,
    image_selection as image_selection,
    legacy_selection as legacy_selection,
    legacy_recovery_transition as legacy_recovery_transition,
    decide_cut_transition as decide_cut_transition,
)
from kungfu._runtime_upgrade.image_lifecycle import (
    runtime_identity as runtime_identity,
    validate_manifest as validate_manifest,
    user_message as user_message,
    is_public_release_cut as is_public_release_cut,
    release_check_impact as release_check_impact,
    plan_install as plan_install,
    _quarantine_record as _quarantine_record,
    install_image as install_image,
    list_images as list_images,
    _contains as _contains,
    compatibility as compatibility,
    plan_upgrade as plan_upgrade,
    _pin_path as _pin_path,
    active_image as active_image,
    references_from_runtime_status as references_from_runtime_status,
    stage_upgrade as stage_upgrade,
    reconcile_upgrade as reconcile_upgrade,
    pinned_entry_command as pinned_entry_command,
    pinned_environment as pinned_environment,
    image_from_environment as image_from_environment,
    plan_gc as plan_gc,
    apply_gc as apply_gc,
)


for _facade_callable in (
    UpgradeError,
    _contract,
    _validate,
    _canonical,
    _stable_id,
    manifest_digest,
    runtime_identity,
    tree_digest,
    inventory_root,
    _state_root,
    _image_root,
    _write_json,
    _read_json,
    validate_manifest,
    user_message,
    is_public_release_cut,
    release_check_impact,
    plan_install,
    _quarantine_record,
    install_image,
    list_images,
    _contains,
    compatibility,
    plan_upgrade,
    _pin_path,
    active_image,
    references_from_runtime_status,
    stage_upgrade,
    reconcile_upgrade,
    pinned_entry_command,
    pinned_environment,
    image_from_environment,
    plan_gc,
    apply_gc,
    ReleaseCutError,
    canonical_json_bytes,
    content_root,
    manifest_identity_root,
    _require_exact_fields,
    _require_string,
    _require_root,
    _root_list,
    validate_platform_slice,
    finish_platform_slice,
    validate_release_cut,
    finish_release_cut,
    validate_cut_transition,
    finish_cut_transition,
    build_shifu_local_transition,
    is_legacy_bootstrap,
    legacy_coordinate,
    image_coordinate,
    legacy_selection_is_bound,
    manifest_compatibility,
    shifu_local_transition,
    image_selection,
    legacy_selection,
    legacy_recovery_transition,
    decide_cut_transition,
):
    _facade_callable.__module__ = __name__
del _facade_callable
