// SPDX-License-Identifier: Apache-2.0
// born-FB Asset schema(R3 一 schema 同驱 journal 载荷 + SQLite 投影)。Order/Trade/Position 同法第四类型(账本资金 state)。
// char-array/enum 表示口径(2026-06-21):enum class:int8_t→FB enum:byte(INTEGER) 镜像 longfist enums.h。
// 全字段镜像 longfist::types::Asset(types.h:95-151,40 字段);字段名严格对齐以保 SQLite 投影列与既有 sqlite_orm 一致。
// enum:LedgerCategory 经 include position.fbs 复用——避免与 position_fb_builder 同 TU(ledger.cpp 同时 include
// position/asset 两 builder)时 FB enum ODR 冲突(position.fbs 已 include order.fbs)。
// 单主键 holder_uid(types.h:96)标 (pk)。演进规则:尾部追加、不重排/删 id、不复用、agent 消息禁 required。
include "position.fbs";

namespace kungfu.longfist.fb;

table Asset {
  update_time:long;
  holder_uid:uint (pk);
  ledger_category:LedgerCategory;
  initial_equity:double;
  static_equity:double;
  dynamic_equity:double;
  realized_pnl:double;
  unrealized_pnl:double;
  market_value:double;
  long_market_value:double;
  short_market_value:double;
  margin:double;
  long_margin:double;
  short_margin:double;
  accumulated_fee:double;
  intraday_fee:double;
  frozen_cash:double;
  frozen_margin:double;
  frozen_fee:double;
  position_pnl:double;
  close_pnl:double;
  avail:double;
  long_avail:double;
  short_avail:double;
  total_asset:double;
  avail_margin:double;
  long_debt:double;
  short_cash:double;
  margin_interest:double;
  settlement:double;
  credit:double;
  collateral_ratio:double;
  total_debt:double;
  net_assets:double;
  long_total_debt:double;
  short_total_debt:double;
  gage_buy_fund_available:double;
  credit_buy_fund_available:double;
  buyredeliver_fund_available:double;
  directrepay_fund_available:double;
}
root_type Asset;
