// SPDX-License-Identifier: Apache-2.0
// born-FB Order schema(R3 一 schema 同驱 journal 载荷 + SQLite 投影)。
// char-array/enum 表示口径(2026-06-21):array<char,N>→string(TEXT)、enum class:int8_t→FB enum:byte(INTEGER) 镜像 longfist enums.h。
// 全字段镜像 longfist::types::Order(types.h:266-302);字段名严格对齐以保 SQLite 投影列与既有 sqlite_orm 一致。
// 演进规则:尾部追加、不重排/删 id、不复用、agent 消息禁 required。
namespace kungfu.longfist.fb;

attribute "pk";
attribute "ts";
attribute "status";

enum OrderStatus : byte {
  Unknown = 0, Submitted = 1, Pending = 2, Cancelled = 3, Error = 4, Filled = 5,
  PartialFilledNotActive = 6, PartialFilledActive = 7, Lost = 8, Cancelling = 9,
  Pause = 10, PendingSettlement = 11
}
enum InstrumentType : byte {
  Unknown = 0, Stock = 1, StockOption = 2, TechStock = 3, Future = 4, Bond = 5,
  Fund = 6, Index = 7, Repo = 8, Crypto = 9, CryptoFuture = 10, CryptoUFuture = 11
}
enum Side : byte {
  Buy = 0, Sell = 1, Lock = 2, Unlock = 3, Exec = 4, Drop = 5, Purchase = 6, Redemption = 7,
  Split = 8, Merge = 9, MarginTrade = 10, ShortSell = 11, RepayMargin = 12, RepayStock = 13,
  CashRepayMargin = 14, StockRepayStock = 15, SurplusStockTransfer = 16, GuaranteeStockTransferIn = 17,
  GuaranteeStockTransferOut = 18, GuaranteeStockBuy = 19, GuaranteeStockSell = 20, Unknown = 99
}
enum Offset : byte { Open = 0, Close = 1, CloseToday = 2, CloseYesterday = 3 }
enum HedgeFlag : byte { Speculation = 0, Arbitrage = 1, Hedge = 2, Covered = 3 }
enum PriceType : byte {
  Limit = 0, Any = 1, FakBest5 = 2, ForwardBest = 3, ReverseBest = 4, Fak = 5, Fok = 6,
  EnhancedLimit = 7, AtAuctionLimit = 8, AtAuction = 9, Unknown = 10
}
enum VolumeCondition : byte { Any = 0, Min = 1, All = 2 }
enum TimeCondition : byte { IOC = 0, GFD = 1, GTC = 2, GFS = 3, GTD = 4, GFA = 5, Unknown = 6 }

table Order {
  order_id:ulong (pk);
  external_order_id:string;
  parent_id:ulong;
  insert_time:long;
  update_time:long;
  restore_time:long (ts);
  trading_day:string;
  instrument_id:string;
  exchange_id:string;
  contract_id:string;
  instrument_type:InstrumentType;
  limit_price:double;
  frozen_price:double;
  volume:double;
  volume_left:double;
  tax:double;
  commission:double;
  status:OrderStatus (status);
  error_id:int;
  error_msg:string;
  is_swap:bool;
  side:Side;
  offset:Offset;
  hedge_flag:HedgeFlag;
  price_type:PriceType;
  volume_condition:VolumeCondition;
  time_condition:TimeCondition;
}
root_type Order;
