// SPDX-License-Identifier: Apache-2.0
// born-FB Trade schema(R3 一 schema 同驱 journal 载荷 + SQLite 投影)。Order 同法第二类型(证模式可推广)。
// char-array/enum 表示口径(2026-06-21):array<char,N>→string(TEXT)、enum class:int8_t→FB enum:byte(INTEGER) 镜像 longfist enums.h。
// 全字段镜像 longfist::types::Trade(types.h:304-332);字段名严格对齐以保 SQLite 投影列与既有 sqlite_orm 一致。
// enum(InstrumentType/Side/Offset/HedgeFlag)经 include order.fbs 复用——避免重复定义,使同 TU(matcher.cpp)同时
// include order/trade 两 builder 时 FB enum 不 ODR 冲突。
// 演进规则:尾部追加、不重排/删 id、不复用、agent 消息禁 required。
include "order.fbs";

namespace kungfu.longfist.fb;

table Trade {
  trade_id:ulong (pk);
  order_id:ulong;
  parent_order_id:ulong;
  external_order_id:string;
  external_trade_id:string;
  trade_time:long;
  restore_time:long (ts);
  trading_day:string;
  instrument_id:string;
  exchange_id:string;
  contract_id:string;
  instrument_type:InstrumentType;
  side:Side;
  offset:Offset;
  hedge_flag:HedgeFlag;
  price:double;
  volume:double;
  tax:double;
  commission:double;
}
root_type Trade;
