# SPDX-License-Identifier: Apache-2.0

"""Stable Work Control runtime facade.

Implementations are partitioned by state/contract, Assignment/relations, and
lifecycle responsibility while this module preserves the established import surface.
"""

from ._work_control_state import (
    CONTRACT_WORLD_ID as CONTRACT_WORLD_ID,
    CONTRACT_VERSION as CONTRACT_VERSION,
    INITIATIVE_SURFACE_ID as INITIATIVE_SURFACE_ID,
    ASSIGNMENT_SURFACE_ID as ASSIGNMENT_SURFACE_ID,
    CLAIM_SURFACE_ID as CLAIM_SURFACE_ID,
    RELATION_SURFACE_ID as RELATION_SURFACE_ID,
    REVIEW_SURFACE_ID as REVIEW_SURFACE_ID,
    USER_FACT_SOURCE_ID as USER_FACT_SOURCE_ID,
    AGENT_FACT_SOURCE_ID as AGENT_FACT_SOURCE_ID,
    _T as _T,
    _BOUND_WORK_CONTROL_SOURCE as _BOUND_WORK_CONTROL_SOURCE,
    _INACTIVE_PROJECTION_READ as _INACTIVE_PROJECTION_READ,
    FACT_SURFACES as FACT_SURFACES,
    PROGRESS_CLAIM as PROGRESS_CLAIM,
    PROGRESS_PURPOSE as PROGRESS_PURPOSE,
    COST_STATE_PROOF_PROFILE_ID as COST_STATE_PROOF_PROFILE_ID,
    COST_STATE_PROOF_PROFILE_VERSION as COST_STATE_PROOF_PROFILE_VERSION,
    WORK_CONTROL_PROFILE_ID as WORK_CONTROL_PROFILE_ID,
    WORK_CONTROL_PROFILE_VERSION as WORK_CONTROL_PROFILE_VERSION,
    WORK_CONTROL_REDUCER as WORK_CONTROL_REDUCER,
    WORK_CONTROL_QUESTIONS as WORK_CONTROL_QUESTIONS,
    ATTRIBUTION_NAMES as ATTRIBUTION_NAMES,
    PROGRESS_POLICY as PROGRESS_POLICY,
    COMPLETION_CLAIM as COMPLETION_CLAIM,
    COMPLETION_PURPOSE as COMPLETION_PURPOSE,
    INDEPENDENT_REVIEW as INDEPENDENT_REVIEW,
    CONTINUATION_DECISION as CONTINUATION_DECISION,
    ASSIGNMENT_EXECUTION_CLAIM as ASSIGNMENT_EXECUTION_CLAIM,
    ASSIGNMENT_PHASE_TRANSITION as ASSIGNMENT_PHASE_TRANSITION,
    ASSIGNMENT_RELATION_EVENT as ASSIGNMENT_RELATION_EVENT,
    ASSIGNMENT_RELATION_EVENTS as ASSIGNMENT_RELATION_EVENTS,
    ASSIGNMENT_PHASES as ASSIGNMENT_PHASES,
    REVIEW_VERDICTS as REVIEW_VERDICTS,
    CONTINUATION_ACTIONS as CONTINUATION_ACTIONS,
    ROOT_ID as ROOT_ID,
    GIT_OBJECT_ID as GIT_OBJECT_ID,
    COMPLETION_POLICY as COMPLETION_POLICY,
    SURFACE_BY_KIND as SURFACE_BY_KIND,
    SURFACE_AUTHORITIES as SURFACE_AUTHORITIES,
    STABLE_ID as STABLE_ID,
    _record_schema as _record_schema,
    capabilities as capabilities,
    _canonical_json as _canonical_json,
    _sha256_root as _sha256_root,
    _source_time_nanos as _source_time_nanos,
    work_control_profile_source as work_control_profile_source,
    _with_profile_source as _with_profile_source,
    _RETIRED_ATLAS_SOURCE as _RETIRED_ATLAS_SOURCE,
    _RETIRED_ATLAS_SURFACES as _RETIRED_ATLAS_SURFACES,
    _retained_source_authority_compatibility as _retained_source_authority_compatibility,
    contract_materialization_plan as contract_materialization_plan,
    ensure_profile_contract as ensure_profile_contract,
    _profile_context as _profile_context,
    _ensure_contract as _ensure_contract,
    _episode_root as _episode_root,
    _declaration_refs as _declaration_refs,
    _selected_subjects as _selected_subjects,
    build_state_query as build_state_query,
    _runtime_query_definition as _runtime_query_definition,
    _batched_state_query as _batched_state_query,
    query_state as query_state,
    _native_source as _native_source,
    _stable_id as _stable_id,
    _native_observation_id as _native_observation_id,
    _put_native_fact as _put_native_fact,
    list_domain_records as list_domain_records,
    list_initiatives as list_initiatives,
    list_assignments as list_assignments,
    _root_id as _root_id,
    authority_status as authority_status,
    _ensure_native_write_allowed as _ensure_native_write_allowed,
)
from ._work_control_assignment import (
    create_initiative as create_initiative,
    _local_work_ref as _local_work_ref,
    _validated_work_ref as _validated_work_ref,
    create_assignment as create_assignment,
    list_assignment_relation_events as list_assignment_relation_events,
    assignment_relations as assignment_relations,
    append_assignment_relation_event as append_assignment_relation_event,
    claim_assignment_execution as claim_assignment_execution,
)
from ._work_control_lifecycle import (
    resolve_canonical_state as resolve_canonical_state,
    assignment_orchestration_status as assignment_orchestration_status,
    advance_assignment_phase as advance_assignment_phase,
    _verified_episode as _verified_episode,
    _tracked_completion_evidence as _tracked_completion_evidence,
    _require_semantic_completion as _require_semantic_completion,
    claim_completion as claim_completion,
)
