#  SPDX-License-Identifier: Apache-2.0

import sys

import click

from kungfu.cli.commands import kfc
from kungfu.rewind.managed_cli import run_and_report
from kungfu.rewind.managed_run import managed_providers

managed_run_command_context = kfc.pass_context()


@kfc.command(
    help_priority=3,
    help=(
        "run a provider under management and report its cost: "
        "kungfu managed-run --provider claude --prompt <task>"
    ),
)
@click.option(
    "--provider",
    required=True,
    type=click.Choice(managed_providers()),
    help="which provider CLI to run under management",
)
@click.option("--prompt", required=True, help="the task to run")
@click.option(
    "--work-id",
    type=str,
    default=None,
    help="work item this run belongs to, when known",
)
@click.option(
    "--skill-path",
    "skill_paths",
    multiple=True,
    type=click.Path(exists=True),
    help="skill directory or skill root to advertise to the agent",
)
@click.option("--skill-profile", type=str, default=None, help="skill context profile")
@click.option("--agent", type=str, default=None, help="agent label for skill context")
@click.option(
    "--skill-context-file",
    type=click.Path(exists=True),
    default=None,
    help="prebuilt skill context envelope generated by a manager",
)
@click.option(
    "--no-skill-context",
    is_flag=True,
    help="disable Kungfu Skill context injection",
)
@click.option(
    "--print-response",
    is_flag=True,
    help="print the provider response text after the managed-run report",
)
@managed_run_command_context
def managed_run(
    ctx,
    provider,
    prompt,
    work_id,
    skill_paths,
    skill_profile,
    agent,
    skill_context_file,
    no_skill_context,
    print_response,
):
    sys.exit(
        run_and_report(
            provider,
            prompt,
            runtime_dir=ctx.runtime_dir,
            work_id=work_id,
            home=ctx.home,
            skill_paths=list(skill_paths),
            skill_profile=skill_profile,
            agent=agent,
            skill_context=not no_skill_context,
            skill_context_file=skill_context_file,
            print_response=print_response,
        )
    )
