// @generated by scripts/generate-kfx-authoring-kit.mjs source_path=framework/api/src/capability/service-authz.ts
import type { KfxHostContribution } from './kfx-host.js';
import type { SandboxProfile } from './sandbox-launcher.js';
export type ServiceAuthorization = KfxHostContribution['authorization'];
export type ServiceLanding =
  | {
      tier: 'co-resident';
    }
  | {
      tier: 'sandbox';
      profile: SandboxProfile;
      networkConsent: boolean;
    };
export declare function resolveServiceLanding(
  authorization: ServiceAuthorization,
): ServiceLanding;
export declare const KFX_SERVICE_HOST_SCHEMA: 'kungfu.kfx.service-host/v1';
export declare const KFX_SERVICE_RECEIPT_SCHEMA: 'kungfu.kfx.service-host-receipt/v1';
export type KfxServiceLifecycleState =
  | 'installed'
  | 'dormant'
  | 'starting'
  | 'ready'
  | 'draining'
  | 'stopped'
  | 'crashed'
  | 'deactivated'
  | 'uninstalled';
export type KfxServiceDiagnosticCode =
  | 'KF_KFX_SERVICE_CONTRACT_UNSUPPORTED'
  | 'KF_KFX_SERVICE_LIFECYCLE_INVALID'
  | 'KF_KFX_SERVICE_UNQUALIFIED'
  | 'KF_KFX_SERVICE_UNAUTHORIZED'
  | 'KF_KFX_SERVICE_DEPENDENCY_DORMANT'
  | 'KF_KFX_LISTENER_DISABLED'
  | 'KF_KFX_LISTENER_POLICY_REJECTED'
  | 'KF_KFX_WEBHOOK_METHOD_UNSUPPORTED'
  | 'KF_KFX_WEBHOOK_PATH_UNSUPPORTED'
  | 'KF_KFX_WEBHOOK_UNSIGNED'
  | 'KF_KFX_WEBHOOK_AUTHENTICATION_FAILED'
  | 'KF_KFX_WEBHOOK_REPLAYED'
  | 'KF_KFX_WEBHOOK_OVERSIZED'
  | 'KF_KFX_WEBHOOK_RATE_EXCEEDED'
  | 'KF_KFX_WEBHOOK_QUEUE_FULL'
  | 'KF_KFX_WEBHOOK_TIMEOUT'
  | 'KF_KFX_WEBHOOK_NORMALIZATION_FAILED';
export type KfxServiceHostDeclaration = {
  schema: typeof KFX_SERVICE_HOST_SCHEMA;
  contractVersion: 1;
  lifecycle: {
    restartPolicy: 'never' | 'on-failure';
    readinessTimeoutMs: number;
    drainTimeoutMs: number;
    shutdownTimeoutMs: number;
  };
  webhook: {
    listener: {
      mode: 'disabled' | 'loopback' | 'explicit';
      bindAddress?: string;
      port?: number;
      path: string;
      methods: Array<'POST' | 'PUT'>;
    };
    credentials: Array<{
      handle: string;
      purpose: 'webhook-signature-verification';
      algorithms: Array<'hmac-sha256' | 'ed25519'>;
    }>;
    intake: {
      maxPayloadBytes: number;
      maxQueueDepth: number;
      maxInflight: number;
      maxRequestsPerWindow: number;
      rateWindowMs: number;
      handlerTimeoutMs: number;
      replayWindowMs: number;
    };
  };
};
export type KfxServiceDependencyEvidence = {
  providerId: string;
  version: string;
  installed: boolean;
  qualified: boolean;
  authorized: boolean;
  compatible: boolean;
};
export type KfxServiceAuthorityEvidence = {
  packageKey: string;
  packageVersion: string;
  kfdRoot: string | null;
  warrantRoot: string | null;
  passportRoot: string | null;
  authorizationRoot: string | null;
  capabilityGrantRoot: string | null;
  dependencyRoot: string | null;
  qualified: boolean;
  authorized: boolean;
  grantedCapabilities: string[];
  dependencies: KfxServiceDependencyEvidence[];
};
export type KfxWebhookRequest = {
  method: string;
  path: string;
  headers: Readonly<Record<string, string>>;
  body: Uint8Array;
  signature: string | null;
  replayKey: string | null;
};
export type KfxCredentialVerifyRequest = {
  handle: string;
  algorithm: 'hmac-sha256' | 'ed25519';
  body: Uint8Array;
  signature: string;
  headers: Readonly<Record<string, string>>;
};
export type KfxCredentialBroker = {
  verify(request: KfxCredentialVerifyRequest): Promise<boolean>;
};
export type KfxWebhookHandler<Event> = {
  credentialHandle: string;
  algorithm: 'hmac-sha256' | 'ed25519';
  normalize(request: {
    method: string;
    path: string;
    headers: Readonly<Record<string, string>>;
    body: Uint8Array;
  }): Promise<Event>;
  onEvent(event: Event): Promise<void>;
};
export type KfxServiceReceipt = {
  schema: typeof KFX_SERVICE_RECEIPT_SCHEMA;
  sequence: number;
  operation: string;
  outcome: 'applied' | 'refused';
  state: KfxServiceLifecycleState;
  generation: number;
  packageVersion: string;
  code: KfxServiceDiagnosticCode | null;
  evidence: {
    kfdRoot: string | null;
    warrantRoot: string | null;
    passportRoot: string | null;
    authorizationRoot: string | null;
    capabilityGrantRoot: string | null;
    dependencyRoot: string | null;
  };
  details: Record<string, boolean | number | string | null>;
  receiptRoot: string;
};
export type KfxWebhookIntakeResult<Event> = {
  accepted: boolean;
  event?: Event;
  receipt: KfxServiceReceipt;
};
type Clock = {
  now(): number;
};
export declare function validateKfxServiceHostDeclaration(
  declaration: KfxServiceHostDeclaration,
): void;
export declare class KfxServiceWebhookHost<Event> {
  private readonly declaration;
  private evidence;
  private readonly broker;
  private readonly handler;
  private readonly clock;
  private stateValue;
  private version;
  private generationValue;
  private sequence;
  private inflight;
  private readonly replay;
  private readonly rate;
  constructor(
    declaration: KfxServiceHostDeclaration,
    evidence: KfxServiceAuthorityEvidence,
    broker: KfxCredentialBroker,
    handler: KfxWebhookHandler<Event>,
    clock?: Clock,
  );
  get state(): KfxServiceLifecycleState;
  get generation(): number;
  private receipt;
  private refuse;
  private dependenciesEligible;
  private authorityCode;
  private listenerCode;
  start(): KfxServiceReceipt;
  ready(): KfxServiceReceipt;
  drain(): KfxServiceReceipt;
  stop(): KfxServiceReceipt;
  crash(): KfxServiceReceipt;
  restart(): KfxServiceReceipt;
  upgrade(
    nextVersion: string,
    evidence: KfxServiceAuthorityEvidence,
  ): KfxServiceReceipt;
  rollback(
    previousVersion: string,
    evidence: KfxServiceAuthorityEvidence,
  ): KfxServiceReceipt;
  deactivate(): KfxServiceReceipt;
  uninstall(): KfxServiceReceipt;
  updateDependencies(
    dependencies: KfxServiceDependencyEvidence[],
    dependencyRoot: string | null,
  ): KfxServiceReceipt;
  private pruneWindows;
  intake(request: KfxWebhookRequest): Promise<KfxWebhookIntakeResult<Event>>;
}
