// @generated by scripts/generate-kfx-authoring-kit.mjs source_path=framework/api/src/capability/service-authz.ts
export type KfLocator =
  | {
      runtimeDir: string;
    }
  | {
      home: string;
      runtime?: string;
    };
export declare function resolveRuntimeDir(locator: KfLocator): string;
export declare const ROLE_NAMES: readonly [
  'source',
  'sink',
  'actor',
  'system',
  'service',
];
export declare const MODE_NAMES: readonly [
  'live',
  'data',
  'replay',
  'backtest',
];
export type KfRole = (typeof ROLE_NAMES)[number];
export type KfMode = (typeof MODE_NAMES)[number];
export declare function roleName(value: number | string): string;
export declare function modeName(value: number | string): string;
export type KfLocation = {
  role: KfRole | string;
  namespace: string;
  name: string;
  mode: KfMode | string;
};
export declare function bigintSafe(_key: string, value: unknown): unknown;
export declare function toSerializable<T>(value: T): unknown;
export type LedgerRecord = {
  genTime: bigint;
  triggerTime: bigint;
  carrierType: number;
  frameUid: bigint;
  triggerFrameUid: bigint;
  streamId: bigint;
  source: number;
  initialSource: number;
  dest: number;
  dataLength: number;
  dataType: number;
  integrityVersion?: number;
  payloadChecksum?: bigint;
  frameChecksum?: bigint;
};
export type RecordFilter = {
  carrierType?: number;
  sinceNanos?: bigint;
  limit?: number;
};
export type ReplayAnchor = {
  episodeId: bigint;
  locationUid: number;
  beginTime: bigint;
  endTime: bigint;
  frameCount: bigint;
  lastFrameUid: bigint;
  closed: boolean;
};
export type LiveHealth = {
  joined: boolean;
  live: boolean;
  usable: boolean;
};
export type Subscription = {
  stop: () => void;
};
export type KfNativeFrame = {
  genTime: () => bigint;
  triggerTime: () => bigint;
  frameUid: () => bigint;
  triggerFrameUid: () => bigint;
  streamId: () => bigint;
  carrierType: () => number;
  source: () => number;
  initialSource: () => number;
  dest: () => number;
  dataLength: () => number;
  dataType: () => number;
  dataBytes: () => Uint8Array;
};
export type KfActionEnvelope = {
  version: number;
  action_type: string;
  schema_ref: {
    id: string;
    version: number;
  };
  payload?: {
    encoding: number;
    data: Uint8Array;
    hash_algorithm: string;
    hash: string;
    byte_len: bigint;
    content_type: string;
    state: string;
  };
};
export type KfNativeBinding = {
  Schema?: new () => {
    types: Record<string, () => Record<string, unknown>>;
  };
  Assemble: new (
    runtimeDirs: string[],
  ) => {
    dataAvailable: () => boolean;
    next: () => void;
    currentFrame: () => KfNativeFrame;
  };
  ActionRecorder?: new (
    runtimeDir: string,
    namespace: string,
    name: string,
    destId?: number,
    streamId?: bigint | number,
  ) => {
    recordBytes: (
      carrierType: number,
      payload: Uint8Array,
      options?: {
        genTime?: bigint | number;
        triggerTime?: bigint | number;
        parentFrameUid?: bigint | number;
        streamId?: bigint | number;
        chainToLast?: boolean;
      },
    ) => LedgerRecord;
    recordJson: (
      carrierType: number,
      jsonPayload: string,
      options?: {
        genTime?: bigint | number;
        triggerTime?: bigint | number;
        parentFrameUid?: bigint | number;
        streamId?: bigint | number;
        chainToLast?: boolean;
      },
    ) => LedgerRecord;
    recordAction: (
      value: Record<string, unknown>,
      options?: {
        genTime?: bigint | number;
        triggerTime?: bigint | number;
        parentFrameUid?: bigint | number;
        streamId?: bigint | number;
        chainToLast?: boolean;
      },
    ) => LedgerRecord;
    mark: (
      carrierType: number,
      options?: {
        genTime?: bigint | number;
        triggerTime?: bigint | number;
        parentFrameUid?: bigint | number;
        streamId?: bigint | number;
        chainToLast?: boolean;
      },
    ) => LedgerRecord;
    lastFrameUid: () => bigint;
  };
  decodeActionEnvelope: (value: Uint8Array) => KfActionEnvelope | null;
  encodeActionEnvelope: (value: Record<string, unknown>) => Uint8Array;
  verifyFlatbufferPayload: (
    schemaBfbs: Uint8Array,
    payload: Uint8Array,
    objectName?: string,
  ) => boolean;
  storageEpisodeListTyped: (
    runtimeDir: string,
    options?: {
      location_uid?: number;
      limit?: bigint | number;
    },
  ) => {
    episodes: unknown[];
  };
  ConfigStore: new (
    runtimeDir: string,
  ) => {
    setConfig: (
      role: string,
      namespace: string,
      name: string,
      mode: string,
      value: string,
    ) => boolean;
    removeConfig: (
      role: string,
      namespace: string,
      name: string,
      mode: string,
    ) => boolean;
    getAllConfig: () => Record<string, Record<string, unknown>>;
  };
  IODevice: new (
    location: Record<string, string>,
    runtimeDir: string,
  ) => {
    getAllLocations: () => Record<string, Record<string, unknown>>;
  };
  Watcher: new (
    runtimeDir: string,
    name: string,
    bypassRestore: boolean,
    millisecondsSleepAfterStep: number,
    captureCustom?: boolean,
  ) => {
    isUsable: () => boolean;
    isLive: () => boolean;
    isStarted: () => boolean;
    start: () => void;
    getLocation: (uid?: number | string) => Record<string, unknown> | undefined;
    issueRawPublic: (carrierType: number, data: Buffer) => boolean;
    requestReadFromPublic: (
      location: Record<string, unknown>,
      fromTime: bigint,
    ) => boolean;
    drainCustomData: () => {
      dropped: bigint;
      frames: Array<{
        genTime: bigint;
        triggerTime: bigint;
        frameUid: bigint;
        carrierType: number;
        source: number;
        dest: number;
        data: Buffer;
      }>;
    };
    runtimeStats: () => {
      schema: 'kungfu.node-watcher-runtime-stats/v1';
      threadModel: 'dedicated-native-thread';
      running: boolean;
      stopRequested: boolean;
      bridgeQueueCapacity: number;
      bridgeQueueDepth: number;
      stepCount: bigint;
      stepMeanNanos: bigint;
      stepMaxNanos: bigint;
      workerLockWaitMeanNanos: bigint;
      workerLockWaitMaxNanos: bigint;
      snapshotLockWaitMeanNanos: bigint;
      snapshotLockWaitMaxNanos: bigint;
      snapshotHoldMeanNanos: bigint;
      snapshotHoldMaxNanos: bigint;
      snapshotRequests: bigint;
      snapshotDeliveries: bigint;
      snapshotCoalesced: bigint;
      bridgeFailures: bigint;
      customQueueBytes: bigint;
      customQueueFrames: bigint;
      customQueueCapacityBytes: bigint;
      customFramesDropped: bigint;
    };
    quit: () => void;
  };
  formatTime?: (nano: bigint, format?: string) => string;
};
