# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GoalSnapshot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GoalSnapshot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGoalSnapshot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GoalSnapshot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GoalSnapshot
    def ImportId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GoalSnapshot
    def GoalId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GoalSnapshot
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GoalSnapshot
    def Title(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GoalSnapshot
    def OwnerAgent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GoalSnapshot
    def MissionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GoalSnapshot
    def Lens(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GoalSnapshot
    def MissionStage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GoalSnapshot
    def SourceBranch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GoalSnapshot
    def WorktreePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GoalSnapshot
    def ExternalRepoPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GoalSnapshot
    def ExternalBranch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GoalSnapshot
    def ExternalHead(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GoalSnapshot
    def ExternalReadyRef(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GoalSnapshot
    def LatestMarker(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GoalSnapshot
    def Summary(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GoalSnapshot
    def NextAction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GoalSnapshot
    def Archived(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def GoalSnapshotStart(builder):
    builder.StartObject(18)

def Start(builder):
    GoalSnapshotStart(builder)

def GoalSnapshotAddImportId(builder, importId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(importId), 0)

def AddImportId(builder, importId):
    GoalSnapshotAddImportId(builder, importId)

def GoalSnapshotAddGoalId(builder, goalId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(goalId), 0)

def AddGoalId(builder, goalId):
    GoalSnapshotAddGoalId(builder, goalId)

def GoalSnapshotAddStatus(builder, status):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(status), 0)

def AddStatus(builder, status):
    GoalSnapshotAddStatus(builder, status)

def GoalSnapshotAddTitle(builder, title):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(title), 0)

def AddTitle(builder, title):
    GoalSnapshotAddTitle(builder, title)

def GoalSnapshotAddOwnerAgent(builder, ownerAgent):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(ownerAgent), 0)

def AddOwnerAgent(builder, ownerAgent):
    GoalSnapshotAddOwnerAgent(builder, ownerAgent)

def GoalSnapshotAddMissionId(builder, missionId):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(missionId), 0)

def AddMissionId(builder, missionId):
    GoalSnapshotAddMissionId(builder, missionId)

def GoalSnapshotAddLens(builder, lens):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(lens), 0)

def AddLens(builder, lens):
    GoalSnapshotAddLens(builder, lens)

def GoalSnapshotAddMissionStage(builder, missionStage):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(missionStage), 0)

def AddMissionStage(builder, missionStage):
    GoalSnapshotAddMissionStage(builder, missionStage)

def GoalSnapshotAddSourceBranch(builder, sourceBranch):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(sourceBranch), 0)

def AddSourceBranch(builder, sourceBranch):
    GoalSnapshotAddSourceBranch(builder, sourceBranch)

def GoalSnapshotAddWorktreePath(builder, worktreePath):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(worktreePath), 0)

def AddWorktreePath(builder, worktreePath):
    GoalSnapshotAddWorktreePath(builder, worktreePath)

def GoalSnapshotAddExternalRepoPath(builder, externalRepoPath):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(externalRepoPath), 0)

def AddExternalRepoPath(builder, externalRepoPath):
    GoalSnapshotAddExternalRepoPath(builder, externalRepoPath)

def GoalSnapshotAddExternalBranch(builder, externalBranch):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(externalBranch), 0)

def AddExternalBranch(builder, externalBranch):
    GoalSnapshotAddExternalBranch(builder, externalBranch)

def GoalSnapshotAddExternalHead(builder, externalHead):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(externalHead), 0)

def AddExternalHead(builder, externalHead):
    GoalSnapshotAddExternalHead(builder, externalHead)

def GoalSnapshotAddExternalReadyRef(builder, externalReadyRef):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(externalReadyRef), 0)

def AddExternalReadyRef(builder, externalReadyRef):
    GoalSnapshotAddExternalReadyRef(builder, externalReadyRef)

def GoalSnapshotAddLatestMarker(builder, latestMarker):
    builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(latestMarker), 0)

def AddLatestMarker(builder, latestMarker):
    GoalSnapshotAddLatestMarker(builder, latestMarker)

def GoalSnapshotAddSummary(builder, summary):
    builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(summary), 0)

def AddSummary(builder, summary):
    GoalSnapshotAddSummary(builder, summary)

def GoalSnapshotAddNextAction(builder, nextAction):
    builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(nextAction), 0)

def AddNextAction(builder, nextAction):
    GoalSnapshotAddNextAction(builder, nextAction)

def GoalSnapshotAddArchived(builder, archived):
    builder.PrependBoolSlot(17, archived, 0)

def AddArchived(builder, archived):
    GoalSnapshotAddArchived(builder, archived)

def GoalSnapshotEnd(builder):
    return builder.EndObject()

def End(builder):
    return GoalSnapshotEnd(builder)
