# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ImportBegin(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ImportBegin()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsImportBegin(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ImportBegin
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ImportBegin
    def ImportId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ImportBegin
    def RepoRoot(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ImportBegin
    def RepoHead(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ImportBegin
    def SchemaVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ImportBeginStart(builder):
    builder.StartObject(4)

def Start(builder):
    ImportBeginStart(builder)

def ImportBeginAddImportId(builder, importId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(importId), 0)

def AddImportId(builder, importId):
    ImportBeginAddImportId(builder, importId)

def ImportBeginAddRepoRoot(builder, repoRoot):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(repoRoot), 0)

def AddRepoRoot(builder, repoRoot):
    ImportBeginAddRepoRoot(builder, repoRoot)

def ImportBeginAddRepoHead(builder, repoHead):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(repoHead), 0)

def AddRepoHead(builder, repoHead):
    ImportBeginAddRepoHead(builder, repoHead)

def ImportBeginAddSchemaVersion(builder, schemaVersion):
    builder.PrependUint32Slot(3, schemaVersion, 0)

def AddSchemaVersion(builder, schemaVersion):
    ImportBeginAddSchemaVersion(builder, schemaVersion)

def ImportBeginEnd(builder):
    return builder.EndObject()

def End(builder):
    return ImportBeginEnd(builder)
