# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ImportEnd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ImportEnd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsImportEnd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ImportEnd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ImportEnd
    def ImportId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ImportEnd
    def Missions(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ImportEnd
    def Goals(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ImportEnd
    def Markers(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ImportEnd
    def Warnings(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ImportEndStart(builder):
    builder.StartObject(5)

def Start(builder):
    ImportEndStart(builder)

def ImportEndAddImportId(builder, importId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(importId), 0)

def AddImportId(builder, importId):
    ImportEndAddImportId(builder, importId)

def ImportEndAddMissions(builder, missions):
    builder.PrependUint32Slot(1, missions, 0)

def AddMissions(builder, missions):
    ImportEndAddMissions(builder, missions)

def ImportEndAddGoals(builder, goals):
    builder.PrependUint32Slot(2, goals, 0)

def AddGoals(builder, goals):
    ImportEndAddGoals(builder, goals)

def ImportEndAddMarkers(builder, markers):
    builder.PrependUint32Slot(3, markers, 0)

def AddMarkers(builder, markers):
    ImportEndAddMarkers(builder, markers)

def ImportEndAddWarnings(builder, warnings):
    builder.PrependUint32Slot(4, warnings, 0)

def AddWarnings(builder, warnings):
    ImportEndAddWarnings(builder, warnings)

def ImportEndEnd(builder):
    return builder.EndObject()

def End(builder):
    return ImportEndEnd(builder)
