# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MarkerSnapshot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MarkerSnapshot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMarkerSnapshot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MarkerSnapshot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MarkerSnapshot
    def ImportId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MarkerSnapshot
    def Branch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MarkerSnapshot
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MarkerSnapshot
    def Ready(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # MarkerSnapshot
    def ReadyScope(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MarkerSnapshot
    def KeepSourceWorktree(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # MarkerSnapshot
    def WorktreePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MarkerSnapshot
    def Summary(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MarkerSnapshot
    def Risk(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MarkerSnapshot
    def MarkerPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def MarkerSnapshotStart(builder):
    builder.StartObject(10)

def Start(builder):
    MarkerSnapshotStart(builder)

def MarkerSnapshotAddImportId(builder, importId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(importId), 0)

def AddImportId(builder, importId):
    MarkerSnapshotAddImportId(builder, importId)

def MarkerSnapshotAddBranch(builder, branch):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(branch), 0)

def AddBranch(builder, branch):
    MarkerSnapshotAddBranch(builder, branch)

def MarkerSnapshotAddStatus(builder, status):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(status), 0)

def AddStatus(builder, status):
    MarkerSnapshotAddStatus(builder, status)

def MarkerSnapshotAddReady(builder, ready):
    builder.PrependBoolSlot(3, ready, 0)

def AddReady(builder, ready):
    MarkerSnapshotAddReady(builder, ready)

def MarkerSnapshotAddReadyScope(builder, readyScope):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(readyScope), 0)

def AddReadyScope(builder, readyScope):
    MarkerSnapshotAddReadyScope(builder, readyScope)

def MarkerSnapshotAddKeepSourceWorktree(builder, keepSourceWorktree):
    builder.PrependBoolSlot(5, keepSourceWorktree, 0)

def AddKeepSourceWorktree(builder, keepSourceWorktree):
    MarkerSnapshotAddKeepSourceWorktree(builder, keepSourceWorktree)

def MarkerSnapshotAddWorktreePath(builder, worktreePath):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(worktreePath), 0)

def AddWorktreePath(builder, worktreePath):
    MarkerSnapshotAddWorktreePath(builder, worktreePath)

def MarkerSnapshotAddSummary(builder, summary):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(summary), 0)

def AddSummary(builder, summary):
    MarkerSnapshotAddSummary(builder, summary)

def MarkerSnapshotAddRisk(builder, risk):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(risk), 0)

def AddRisk(builder, risk):
    MarkerSnapshotAddRisk(builder, risk)

def MarkerSnapshotAddMarkerPath(builder, markerPath):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(markerPath), 0)

def AddMarkerPath(builder, markerPath):
    MarkerSnapshotAddMarkerPath(builder, markerPath)

def MarkerSnapshotEnd(builder):
    return builder.EndObject()

def End(builder):
    return MarkerSnapshotEnd(builder)
