# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MissionSnapshot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MissionSnapshot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMissionSnapshot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MissionSnapshot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MissionSnapshot
    def ImportId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MissionSnapshot
    def MissionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MissionSnapshot
    def Title(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MissionSnapshot
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MissionSnapshot
    def ActiveLens(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MissionSnapshot
    def StageName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MissionSnapshot
    def NextReview(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MissionSnapshot
    def NextAction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def MissionSnapshotStart(builder):
    builder.StartObject(8)

def Start(builder):
    MissionSnapshotStart(builder)

def MissionSnapshotAddImportId(builder, importId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(importId), 0)

def AddImportId(builder, importId):
    MissionSnapshotAddImportId(builder, importId)

def MissionSnapshotAddMissionId(builder, missionId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(missionId), 0)

def AddMissionId(builder, missionId):
    MissionSnapshotAddMissionId(builder, missionId)

def MissionSnapshotAddTitle(builder, title):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(title), 0)

def AddTitle(builder, title):
    MissionSnapshotAddTitle(builder, title)

def MissionSnapshotAddStatus(builder, status):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(status), 0)

def AddStatus(builder, status):
    MissionSnapshotAddStatus(builder, status)

def MissionSnapshotAddActiveLens(builder, activeLens):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(activeLens), 0)

def AddActiveLens(builder, activeLens):
    MissionSnapshotAddActiveLens(builder, activeLens)

def MissionSnapshotAddStageName(builder, stageName):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(stageName), 0)

def AddStageName(builder, stageName):
    MissionSnapshotAddStageName(builder, stageName)

def MissionSnapshotAddNextReview(builder, nextReview):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(nextReview), 0)

def AddNextReview(builder, nextReview):
    MissionSnapshotAddNextReview(builder, nextReview)

def MissionSnapshotAddNextAction(builder, nextAction):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(nextAction), 0)

def AddNextAction(builder, nextAction):
    MissionSnapshotAddNextAction(builder, nextAction)

def MissionSnapshotEnd(builder):
    return builder.EndObject()

def End(builder):
    return MissionSnapshotEnd(builder)
