// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ACTIONENVELOPE_KUNGFU_ACTION_FB_H_
#define FLATBUFFERS_GENERATED_ACTIONENVELOPE_KUNGFU_ACTION_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace kungfu {
namespace action {
namespace fb {

struct SchemaRef;
struct SchemaRefBuilder;
struct SchemaRefT;

struct Actor;
struct ActorBuilder;
struct ActorT;

struct Session;
struct SessionBuilder;
struct SessionT;

struct Source;
struct SourceBuilder;
struct SourceT;

struct Batch;
struct BatchBuilder;
struct BatchT;

struct Journal;
struct JournalBuilder;
struct JournalT;

struct Payload;
struct PayloadBuilder;
struct PayloadT;

struct ActionEnvelope;
struct ActionEnvelopeBuilder;
struct ActionEnvelopeT;

enum class PayloadEncoding : uint8_t {
  NONE = 0,
  FLATBUFFERS = 1,
  JSON = 2,
  CONTENT_REFERENCE = 3,
  OPAQUE = 4,
  MIN = NONE,
  MAX = OPAQUE
};

inline const PayloadEncoding (&EnumValuesPayloadEncoding())[5] {
  static const PayloadEncoding values[] = {
    PayloadEncoding::NONE,
    PayloadEncoding::FLATBUFFERS,
    PayloadEncoding::JSON,
    PayloadEncoding::CONTENT_REFERENCE,
    PayloadEncoding::OPAQUE
  };
  return values;
}

inline const char * const *EnumNamesPayloadEncoding() {
  static const char * const names[6] = {
    "NONE",
    "FLATBUFFERS",
    "JSON",
    "CONTENT_REFERENCE",
    "OPAQUE",
    nullptr
  };
  return names;
}

inline const char *EnumNamePayloadEncoding(PayloadEncoding e) {
  if (::flatbuffers::IsOutRange(e, PayloadEncoding::NONE, PayloadEncoding::OPAQUE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPayloadEncoding()[index];
}

struct SchemaRefT : public ::flatbuffers::NativeTable {
  typedef SchemaRef TableType;
  std::string id{};
  uint32_t version = 1;
};

struct SchemaRef FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SchemaRefT NativeTableType;
  typedef SchemaRefBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_VERSION = 6
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  uint32_t version() const {
    return GetField<uint32_t>(VT_VERSION, 1);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           verifier.EndTable();
  }
  SchemaRefT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SchemaRefT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SchemaRef> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SchemaRefT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SchemaRefBuilder {
  typedef SchemaRef Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(SchemaRef::VT_ID, id);
  }
  void add_version(uint32_t version) {
    fbb_.AddElement<uint32_t>(SchemaRef::VT_VERSION, version, 1);
  }
  explicit SchemaRefBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SchemaRef> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SchemaRef>(end);
    fbb_.Required(o, SchemaRef::VT_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<SchemaRef> CreateSchemaRef(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    uint32_t version = 1) {
  SchemaRefBuilder builder_(_fbb);
  builder_.add_version(version);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SchemaRef> CreateSchemaRefDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    uint32_t version = 1) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  return kungfu::action::fb::CreateSchemaRef(
      _fbb,
      id__,
      version);
}

::flatbuffers::Offset<SchemaRef> CreateSchemaRef(::flatbuffers::FlatBufferBuilder &_fbb, const SchemaRefT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ActorT : public ::flatbuffers::NativeTable {
  typedef Actor TableType;
  std::string id{};
  std::string kind{};
  std::string storage_source_id{};
  std::string source_type{};
};

struct Actor FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ActorT NativeTableType;
  typedef ActorBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_KIND = 6,
    VT_STORAGE_SOURCE_ID = 8,
    VT_SOURCE_TYPE = 10
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *kind() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KIND);
  }
  const ::flatbuffers::String *storage_source_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_STORAGE_SOURCE_ID);
  }
  const ::flatbuffers::String *source_type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_TYPE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_KIND) &&
           verifier.VerifyString(kind()) &&
           VerifyOffset(verifier, VT_STORAGE_SOURCE_ID) &&
           verifier.VerifyString(storage_source_id()) &&
           VerifyOffset(verifier, VT_SOURCE_TYPE) &&
           verifier.VerifyString(source_type()) &&
           verifier.EndTable();
  }
  ActorT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ActorT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Actor> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ActorT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ActorBuilder {
  typedef Actor Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(Actor::VT_ID, id);
  }
  void add_kind(::flatbuffers::Offset<::flatbuffers::String> kind) {
    fbb_.AddOffset(Actor::VT_KIND, kind);
  }
  void add_storage_source_id(::flatbuffers::Offset<::flatbuffers::String> storage_source_id) {
    fbb_.AddOffset(Actor::VT_STORAGE_SOURCE_ID, storage_source_id);
  }
  void add_source_type(::flatbuffers::Offset<::flatbuffers::String> source_type) {
    fbb_.AddOffset(Actor::VT_SOURCE_TYPE, source_type);
  }
  explicit ActorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Actor> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Actor>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Actor> CreateActor(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> kind = 0,
    ::flatbuffers::Offset<::flatbuffers::String> storage_source_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> source_type = 0) {
  ActorBuilder builder_(_fbb);
  builder_.add_source_type(source_type);
  builder_.add_storage_source_id(storage_source_id);
  builder_.add_kind(kind);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Actor> CreateActorDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *kind = nullptr,
    const char *storage_source_id = nullptr,
    const char *source_type = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto kind__ = kind ? _fbb.CreateString(kind) : 0;
  auto storage_source_id__ = storage_source_id ? _fbb.CreateString(storage_source_id) : 0;
  auto source_type__ = source_type ? _fbb.CreateString(source_type) : 0;
  return kungfu::action::fb::CreateActor(
      _fbb,
      id__,
      kind__,
      storage_source_id__,
      source_type__);
}

::flatbuffers::Offset<Actor> CreateActor(::flatbuffers::FlatBufferBuilder &_fbb, const ActorT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SessionT : public ::flatbuffers::NativeTable {
  typedef Session TableType;
  std::string run_id{};
  std::string import_id{};
};

struct Session FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SessionT NativeTableType;
  typedef SessionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RUN_ID = 4,
    VT_IMPORT_ID = 6
  };
  const ::flatbuffers::String *run_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RUN_ID);
  }
  const ::flatbuffers::String *import_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_IMPORT_ID);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_RUN_ID) &&
           verifier.VerifyString(run_id()) &&
           VerifyOffset(verifier, VT_IMPORT_ID) &&
           verifier.VerifyString(import_id()) &&
           verifier.EndTable();
  }
  SessionT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SessionT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Session> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SessionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SessionBuilder {
  typedef Session Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_run_id(::flatbuffers::Offset<::flatbuffers::String> run_id) {
    fbb_.AddOffset(Session::VT_RUN_ID, run_id);
  }
  void add_import_id(::flatbuffers::Offset<::flatbuffers::String> import_id) {
    fbb_.AddOffset(Session::VT_IMPORT_ID, import_id);
  }
  explicit SessionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Session> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Session>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Session> CreateSession(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> run_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> import_id = 0) {
  SessionBuilder builder_(_fbb);
  builder_.add_import_id(import_id);
  builder_.add_run_id(run_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Session> CreateSessionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *run_id = nullptr,
    const char *import_id = nullptr) {
  auto run_id__ = run_id ? _fbb.CreateString(run_id) : 0;
  auto import_id__ = import_id ? _fbb.CreateString(import_id) : 0;
  return kungfu::action::fb::CreateSession(
      _fbb,
      run_id__,
      import_id__);
}

::flatbuffers::Offset<Session> CreateSession(::flatbuffers::FlatBufferBuilder &_fbb, const SessionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SourceT : public ::flatbuffers::NativeTable {
  typedef Source TableType;
  std::string kind{};
  std::string source_id{};
  std::string source_path{};
  std::string source_time{};
  uint32_t schema_version = 0;
};

struct Source FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SourceT NativeTableType;
  typedef SourceBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KIND = 4,
    VT_SOURCE_ID = 6,
    VT_SOURCE_PATH = 8,
    VT_SOURCE_TIME = 10,
    VT_SCHEMA_VERSION = 12
  };
  const ::flatbuffers::String *kind() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KIND);
  }
  const ::flatbuffers::String *source_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_ID);
  }
  const ::flatbuffers::String *source_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_PATH);
  }
  const ::flatbuffers::String *source_time() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_TIME);
  }
  uint32_t schema_version() const {
    return GetField<uint32_t>(VT_SCHEMA_VERSION, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KIND) &&
           verifier.VerifyString(kind()) &&
           VerifyOffset(verifier, VT_SOURCE_ID) &&
           verifier.VerifyString(source_id()) &&
           VerifyOffset(verifier, VT_SOURCE_PATH) &&
           verifier.VerifyString(source_path()) &&
           VerifyOffset(verifier, VT_SOURCE_TIME) &&
           verifier.VerifyString(source_time()) &&
           VerifyField<uint32_t>(verifier, VT_SCHEMA_VERSION, 4) &&
           verifier.EndTable();
  }
  SourceT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SourceT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Source> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SourceT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SourceBuilder {
  typedef Source Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_kind(::flatbuffers::Offset<::flatbuffers::String> kind) {
    fbb_.AddOffset(Source::VT_KIND, kind);
  }
  void add_source_id(::flatbuffers::Offset<::flatbuffers::String> source_id) {
    fbb_.AddOffset(Source::VT_SOURCE_ID, source_id);
  }
  void add_source_path(::flatbuffers::Offset<::flatbuffers::String> source_path) {
    fbb_.AddOffset(Source::VT_SOURCE_PATH, source_path);
  }
  void add_source_time(::flatbuffers::Offset<::flatbuffers::String> source_time) {
    fbb_.AddOffset(Source::VT_SOURCE_TIME, source_time);
  }
  void add_schema_version(uint32_t schema_version) {
    fbb_.AddElement<uint32_t>(Source::VT_SCHEMA_VERSION, schema_version, 0);
  }
  explicit SourceBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Source> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Source>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Source> CreateSource(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> kind = 0,
    ::flatbuffers::Offset<::flatbuffers::String> source_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> source_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> source_time = 0,
    uint32_t schema_version = 0) {
  SourceBuilder builder_(_fbb);
  builder_.add_schema_version(schema_version);
  builder_.add_source_time(source_time);
  builder_.add_source_path(source_path);
  builder_.add_source_id(source_id);
  builder_.add_kind(kind);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Source> CreateSourceDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *kind = nullptr,
    const char *source_id = nullptr,
    const char *source_path = nullptr,
    const char *source_time = nullptr,
    uint32_t schema_version = 0) {
  auto kind__ = kind ? _fbb.CreateString(kind) : 0;
  auto source_id__ = source_id ? _fbb.CreateString(source_id) : 0;
  auto source_path__ = source_path ? _fbb.CreateString(source_path) : 0;
  auto source_time__ = source_time ? _fbb.CreateString(source_time) : 0;
  return kungfu::action::fb::CreateSource(
      _fbb,
      kind__,
      source_id__,
      source_path__,
      source_time__,
      schema_version);
}

::flatbuffers::Offset<Source> CreateSource(::flatbuffers::FlatBufferBuilder &_fbb, const SourceT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct BatchT : public ::flatbuffers::NativeTable {
  typedef Batch TableType;
  std::string repo_root{};
  std::string repo_head{};
  uint32_t schema_version = 0;
  uint64_t missions = 0;
  uint64_t goals = 0;
  uint64_t markers = 0;
  uint64_t warnings = 0;
};

struct Batch FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BatchT NativeTableType;
  typedef BatchBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REPO_ROOT = 4,
    VT_REPO_HEAD = 6,
    VT_SCHEMA_VERSION = 8,
    VT_MISSIONS = 10,
    VT_GOALS = 12,
    VT_MARKERS = 14,
    VT_WARNINGS = 16
  };
  const ::flatbuffers::String *repo_root() const {
    return GetPointer<const ::flatbuffers::String *>(VT_REPO_ROOT);
  }
  const ::flatbuffers::String *repo_head() const {
    return GetPointer<const ::flatbuffers::String *>(VT_REPO_HEAD);
  }
  uint32_t schema_version() const {
    return GetField<uint32_t>(VT_SCHEMA_VERSION, 0);
  }
  uint64_t missions() const {
    return GetField<uint64_t>(VT_MISSIONS, 0);
  }
  uint64_t goals() const {
    return GetField<uint64_t>(VT_GOALS, 0);
  }
  uint64_t markers() const {
    return GetField<uint64_t>(VT_MARKERS, 0);
  }
  uint64_t warnings() const {
    return GetField<uint64_t>(VT_WARNINGS, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_REPO_ROOT) &&
           verifier.VerifyString(repo_root()) &&
           VerifyOffset(verifier, VT_REPO_HEAD) &&
           verifier.VerifyString(repo_head()) &&
           VerifyField<uint32_t>(verifier, VT_SCHEMA_VERSION, 4) &&
           VerifyField<uint64_t>(verifier, VT_MISSIONS, 8) &&
           VerifyField<uint64_t>(verifier, VT_GOALS, 8) &&
           VerifyField<uint64_t>(verifier, VT_MARKERS, 8) &&
           VerifyField<uint64_t>(verifier, VT_WARNINGS, 8) &&
           verifier.EndTable();
  }
  BatchT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BatchT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Batch> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BatchT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BatchBuilder {
  typedef Batch Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_repo_root(::flatbuffers::Offset<::flatbuffers::String> repo_root) {
    fbb_.AddOffset(Batch::VT_REPO_ROOT, repo_root);
  }
  void add_repo_head(::flatbuffers::Offset<::flatbuffers::String> repo_head) {
    fbb_.AddOffset(Batch::VT_REPO_HEAD, repo_head);
  }
  void add_schema_version(uint32_t schema_version) {
    fbb_.AddElement<uint32_t>(Batch::VT_SCHEMA_VERSION, schema_version, 0);
  }
  void add_missions(uint64_t missions) {
    fbb_.AddElement<uint64_t>(Batch::VT_MISSIONS, missions, 0);
  }
  void add_goals(uint64_t goals) {
    fbb_.AddElement<uint64_t>(Batch::VT_GOALS, goals, 0);
  }
  void add_markers(uint64_t markers) {
    fbb_.AddElement<uint64_t>(Batch::VT_MARKERS, markers, 0);
  }
  void add_warnings(uint64_t warnings) {
    fbb_.AddElement<uint64_t>(Batch::VT_WARNINGS, warnings, 0);
  }
  explicit BatchBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Batch> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Batch>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Batch> CreateBatch(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> repo_root = 0,
    ::flatbuffers::Offset<::flatbuffers::String> repo_head = 0,
    uint32_t schema_version = 0,
    uint64_t missions = 0,
    uint64_t goals = 0,
    uint64_t markers = 0,
    uint64_t warnings = 0) {
  BatchBuilder builder_(_fbb);
  builder_.add_warnings(warnings);
  builder_.add_markers(markers);
  builder_.add_goals(goals);
  builder_.add_missions(missions);
  builder_.add_schema_version(schema_version);
  builder_.add_repo_head(repo_head);
  builder_.add_repo_root(repo_root);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Batch> CreateBatchDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *repo_root = nullptr,
    const char *repo_head = nullptr,
    uint32_t schema_version = 0,
    uint64_t missions = 0,
    uint64_t goals = 0,
    uint64_t markers = 0,
    uint64_t warnings = 0) {
  auto repo_root__ = repo_root ? _fbb.CreateString(repo_root) : 0;
  auto repo_head__ = repo_head ? _fbb.CreateString(repo_head) : 0;
  return kungfu::action::fb::CreateBatch(
      _fbb,
      repo_root__,
      repo_head__,
      schema_version,
      missions,
      goals,
      markers,
      warnings);
}

::flatbuffers::Offset<Batch> CreateBatch(::flatbuffers::FlatBufferBuilder &_fbb, const BatchT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct JournalT : public ::flatbuffers::NativeTable {
  typedef Journal TableType;
  uint64_t frame_uid = 0;
  uint64_t trigger_frame_uid = 0;
  uint64_t stream_id = 0;
  int64_t gen_time = 0;
  int64_t trigger_time = 0;
  int32_t carrier_type = 1000;
  uint32_t source = 0;
  uint32_t initial_source = 0;
  uint32_t dest = 0;
  uint32_t data_length = 0;
  int8_t data_type = 0;
  uint32_t integrity_version = 0;
  std::string checksum_algorithm{};
  uint64_t payload_checksum = 0;
  uint64_t frame_checksum = 0;
};

struct Journal FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef JournalT NativeTableType;
  typedef JournalBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FRAME_UID = 4,
    VT_TRIGGER_FRAME_UID = 6,
    VT_STREAM_ID = 8,
    VT_GEN_TIME = 10,
    VT_TRIGGER_TIME = 12,
    VT_CARRIER_TYPE = 14,
    VT_SOURCE = 16,
    VT_INITIAL_SOURCE = 18,
    VT_DEST = 20,
    VT_DATA_LENGTH = 22,
    VT_DATA_TYPE = 24,
    VT_INTEGRITY_VERSION = 26,
    VT_CHECKSUM_ALGORITHM = 28,
    VT_PAYLOAD_CHECKSUM = 30,
    VT_FRAME_CHECKSUM = 32
  };
  uint64_t frame_uid() const {
    return GetField<uint64_t>(VT_FRAME_UID, 0);
  }
  uint64_t trigger_frame_uid() const {
    return GetField<uint64_t>(VT_TRIGGER_FRAME_UID, 0);
  }
  uint64_t stream_id() const {
    return GetField<uint64_t>(VT_STREAM_ID, 0);
  }
  int64_t gen_time() const {
    return GetField<int64_t>(VT_GEN_TIME, 0);
  }
  int64_t trigger_time() const {
    return GetField<int64_t>(VT_TRIGGER_TIME, 0);
  }
  int32_t carrier_type() const {
    return GetField<int32_t>(VT_CARRIER_TYPE, 1000);
  }
  uint32_t source() const {
    return GetField<uint32_t>(VT_SOURCE, 0);
  }
  uint32_t initial_source() const {
    return GetField<uint32_t>(VT_INITIAL_SOURCE, 0);
  }
  uint32_t dest() const {
    return GetField<uint32_t>(VT_DEST, 0);
  }
  uint32_t data_length() const {
    return GetField<uint32_t>(VT_DATA_LENGTH, 0);
  }
  int8_t data_type() const {
    return GetField<int8_t>(VT_DATA_TYPE, 0);
  }
  uint32_t integrity_version() const {
    return GetField<uint32_t>(VT_INTEGRITY_VERSION, 0);
  }
  const ::flatbuffers::String *checksum_algorithm() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CHECKSUM_ALGORITHM);
  }
  uint64_t payload_checksum() const {
    return GetField<uint64_t>(VT_PAYLOAD_CHECKSUM, 0);
  }
  uint64_t frame_checksum() const {
    return GetField<uint64_t>(VT_FRAME_CHECKSUM, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_FRAME_UID, 8) &&
           VerifyField<uint64_t>(verifier, VT_TRIGGER_FRAME_UID, 8) &&
           VerifyField<uint64_t>(verifier, VT_STREAM_ID, 8) &&
           VerifyField<int64_t>(verifier, VT_GEN_TIME, 8) &&
           VerifyField<int64_t>(verifier, VT_TRIGGER_TIME, 8) &&
           VerifyField<int32_t>(verifier, VT_CARRIER_TYPE, 4) &&
           VerifyField<uint32_t>(verifier, VT_SOURCE, 4) &&
           VerifyField<uint32_t>(verifier, VT_INITIAL_SOURCE, 4) &&
           VerifyField<uint32_t>(verifier, VT_DEST, 4) &&
           VerifyField<uint32_t>(verifier, VT_DATA_LENGTH, 4) &&
           VerifyField<int8_t>(verifier, VT_DATA_TYPE, 1) &&
           VerifyField<uint32_t>(verifier, VT_INTEGRITY_VERSION, 4) &&
           VerifyOffset(verifier, VT_CHECKSUM_ALGORITHM) &&
           verifier.VerifyString(checksum_algorithm()) &&
           VerifyField<uint64_t>(verifier, VT_PAYLOAD_CHECKSUM, 8) &&
           VerifyField<uint64_t>(verifier, VT_FRAME_CHECKSUM, 8) &&
           verifier.EndTable();
  }
  JournalT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(JournalT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Journal> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const JournalT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct JournalBuilder {
  typedef Journal Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_frame_uid(uint64_t frame_uid) {
    fbb_.AddElement<uint64_t>(Journal::VT_FRAME_UID, frame_uid, 0);
  }
  void add_trigger_frame_uid(uint64_t trigger_frame_uid) {
    fbb_.AddElement<uint64_t>(Journal::VT_TRIGGER_FRAME_UID, trigger_frame_uid, 0);
  }
  void add_stream_id(uint64_t stream_id) {
    fbb_.AddElement<uint64_t>(Journal::VT_STREAM_ID, stream_id, 0);
  }
  void add_gen_time(int64_t gen_time) {
    fbb_.AddElement<int64_t>(Journal::VT_GEN_TIME, gen_time, 0);
  }
  void add_trigger_time(int64_t trigger_time) {
    fbb_.AddElement<int64_t>(Journal::VT_TRIGGER_TIME, trigger_time, 0);
  }
  void add_carrier_type(int32_t carrier_type) {
    fbb_.AddElement<int32_t>(Journal::VT_CARRIER_TYPE, carrier_type, 1000);
  }
  void add_source(uint32_t source) {
    fbb_.AddElement<uint32_t>(Journal::VT_SOURCE, source, 0);
  }
  void add_initial_source(uint32_t initial_source) {
    fbb_.AddElement<uint32_t>(Journal::VT_INITIAL_SOURCE, initial_source, 0);
  }
  void add_dest(uint32_t dest) {
    fbb_.AddElement<uint32_t>(Journal::VT_DEST, dest, 0);
  }
  void add_data_length(uint32_t data_length) {
    fbb_.AddElement<uint32_t>(Journal::VT_DATA_LENGTH, data_length, 0);
  }
  void add_data_type(int8_t data_type) {
    fbb_.AddElement<int8_t>(Journal::VT_DATA_TYPE, data_type, 0);
  }
  void add_integrity_version(uint32_t integrity_version) {
    fbb_.AddElement<uint32_t>(Journal::VT_INTEGRITY_VERSION, integrity_version, 0);
  }
  void add_checksum_algorithm(::flatbuffers::Offset<::flatbuffers::String> checksum_algorithm) {
    fbb_.AddOffset(Journal::VT_CHECKSUM_ALGORITHM, checksum_algorithm);
  }
  void add_payload_checksum(uint64_t payload_checksum) {
    fbb_.AddElement<uint64_t>(Journal::VT_PAYLOAD_CHECKSUM, payload_checksum, 0);
  }
  void add_frame_checksum(uint64_t frame_checksum) {
    fbb_.AddElement<uint64_t>(Journal::VT_FRAME_CHECKSUM, frame_checksum, 0);
  }
  explicit JournalBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Journal> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Journal>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Journal> CreateJournal(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t frame_uid = 0,
    uint64_t trigger_frame_uid = 0,
    uint64_t stream_id = 0,
    int64_t gen_time = 0,
    int64_t trigger_time = 0,
    int32_t carrier_type = 1000,
    uint32_t source = 0,
    uint32_t initial_source = 0,
    uint32_t dest = 0,
    uint32_t data_length = 0,
    int8_t data_type = 0,
    uint32_t integrity_version = 0,
    ::flatbuffers::Offset<::flatbuffers::String> checksum_algorithm = 0,
    uint64_t payload_checksum = 0,
    uint64_t frame_checksum = 0) {
  JournalBuilder builder_(_fbb);
  builder_.add_frame_checksum(frame_checksum);
  builder_.add_payload_checksum(payload_checksum);
  builder_.add_trigger_time(trigger_time);
  builder_.add_gen_time(gen_time);
  builder_.add_stream_id(stream_id);
  builder_.add_trigger_frame_uid(trigger_frame_uid);
  builder_.add_frame_uid(frame_uid);
  builder_.add_checksum_algorithm(checksum_algorithm);
  builder_.add_integrity_version(integrity_version);
  builder_.add_data_length(data_length);
  builder_.add_dest(dest);
  builder_.add_initial_source(initial_source);
  builder_.add_source(source);
  builder_.add_carrier_type(carrier_type);
  builder_.add_data_type(data_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Journal> CreateJournalDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t frame_uid = 0,
    uint64_t trigger_frame_uid = 0,
    uint64_t stream_id = 0,
    int64_t gen_time = 0,
    int64_t trigger_time = 0,
    int32_t carrier_type = 1000,
    uint32_t source = 0,
    uint32_t initial_source = 0,
    uint32_t dest = 0,
    uint32_t data_length = 0,
    int8_t data_type = 0,
    uint32_t integrity_version = 0,
    const char *checksum_algorithm = nullptr,
    uint64_t payload_checksum = 0,
    uint64_t frame_checksum = 0) {
  auto checksum_algorithm__ = checksum_algorithm ? _fbb.CreateString(checksum_algorithm) : 0;
  return kungfu::action::fb::CreateJournal(
      _fbb,
      frame_uid,
      trigger_frame_uid,
      stream_id,
      gen_time,
      trigger_time,
      carrier_type,
      source,
      initial_source,
      dest,
      data_length,
      data_type,
      integrity_version,
      checksum_algorithm__,
      payload_checksum,
      frame_checksum);
}

::flatbuffers::Offset<Journal> CreateJournal(::flatbuffers::FlatBufferBuilder &_fbb, const JournalT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct PayloadT : public ::flatbuffers::NativeTable {
  typedef Payload TableType;
  kungfu::action::fb::PayloadEncoding encoding = kungfu::action::fb::PayloadEncoding::NONE;
  std::vector<uint8_t> data{};
  std::string hash_algorithm{};
  std::string hash{};
  uint64_t byte_len = 0;
  std::string content_type{};
  std::string state{};
};

struct Payload FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PayloadT NativeTableType;
  typedef PayloadBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENCODING = 4,
    VT_DATA = 6,
    VT_HASH_ALGORITHM = 8,
    VT_HASH = 10,
    VT_BYTE_LEN = 12,
    VT_CONTENT_TYPE = 14,
    VT_STATE = 16
  };
  kungfu::action::fb::PayloadEncoding encoding() const {
    return static_cast<kungfu::action::fb::PayloadEncoding>(GetField<uint8_t>(VT_ENCODING, 0));
  }
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  const ::flatbuffers::String *hash_algorithm() const {
    return GetPointer<const ::flatbuffers::String *>(VT_HASH_ALGORITHM);
  }
  const ::flatbuffers::String *hash() const {
    return GetPointer<const ::flatbuffers::String *>(VT_HASH);
  }
  uint64_t byte_len() const {
    return GetField<uint64_t>(VT_BYTE_LEN, 0);
  }
  const ::flatbuffers::String *content_type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CONTENT_TYPE);
  }
  const ::flatbuffers::String *state() const {
    return GetPointer<const ::flatbuffers::String *>(VT_STATE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_ENCODING, 1) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           VerifyOffset(verifier, VT_HASH_ALGORITHM) &&
           verifier.VerifyString(hash_algorithm()) &&
           VerifyOffset(verifier, VT_HASH) &&
           verifier.VerifyString(hash()) &&
           VerifyField<uint64_t>(verifier, VT_BYTE_LEN, 8) &&
           VerifyOffset(verifier, VT_CONTENT_TYPE) &&
           verifier.VerifyString(content_type()) &&
           VerifyOffset(verifier, VT_STATE) &&
           verifier.VerifyString(state()) &&
           verifier.EndTable();
  }
  PayloadT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PayloadT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Payload> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PayloadT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PayloadBuilder {
  typedef Payload Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_encoding(kungfu::action::fb::PayloadEncoding encoding) {
    fbb_.AddElement<uint8_t>(Payload::VT_ENCODING, static_cast<uint8_t>(encoding), 0);
  }
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(Payload::VT_DATA, data);
  }
  void add_hash_algorithm(::flatbuffers::Offset<::flatbuffers::String> hash_algorithm) {
    fbb_.AddOffset(Payload::VT_HASH_ALGORITHM, hash_algorithm);
  }
  void add_hash(::flatbuffers::Offset<::flatbuffers::String> hash) {
    fbb_.AddOffset(Payload::VT_HASH, hash);
  }
  void add_byte_len(uint64_t byte_len) {
    fbb_.AddElement<uint64_t>(Payload::VT_BYTE_LEN, byte_len, 0);
  }
  void add_content_type(::flatbuffers::Offset<::flatbuffers::String> content_type) {
    fbb_.AddOffset(Payload::VT_CONTENT_TYPE, content_type);
  }
  void add_state(::flatbuffers::Offset<::flatbuffers::String> state) {
    fbb_.AddOffset(Payload::VT_STATE, state);
  }
  explicit PayloadBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Payload> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Payload>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Payload> CreatePayload(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    kungfu::action::fb::PayloadEncoding encoding = kungfu::action::fb::PayloadEncoding::NONE,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0,
    ::flatbuffers::Offset<::flatbuffers::String> hash_algorithm = 0,
    ::flatbuffers::Offset<::flatbuffers::String> hash = 0,
    uint64_t byte_len = 0,
    ::flatbuffers::Offset<::flatbuffers::String> content_type = 0,
    ::flatbuffers::Offset<::flatbuffers::String> state = 0) {
  PayloadBuilder builder_(_fbb);
  builder_.add_byte_len(byte_len);
  builder_.add_state(state);
  builder_.add_content_type(content_type);
  builder_.add_hash(hash);
  builder_.add_hash_algorithm(hash_algorithm);
  builder_.add_data(data);
  builder_.add_encoding(encoding);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Payload> CreatePayloadDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    kungfu::action::fb::PayloadEncoding encoding = kungfu::action::fb::PayloadEncoding::NONE,
    const std::vector<uint8_t> *data = nullptr,
    const char *hash_algorithm = nullptr,
    const char *hash = nullptr,
    uint64_t byte_len = 0,
    const char *content_type = nullptr,
    const char *state = nullptr) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  auto hash_algorithm__ = hash_algorithm ? _fbb.CreateString(hash_algorithm) : 0;
  auto hash__ = hash ? _fbb.CreateString(hash) : 0;
  auto content_type__ = content_type ? _fbb.CreateString(content_type) : 0;
  auto state__ = state ? _fbb.CreateString(state) : 0;
  return kungfu::action::fb::CreatePayload(
      _fbb,
      encoding,
      data__,
      hash_algorithm__,
      hash__,
      byte_len,
      content_type__,
      state__);
}

::flatbuffers::Offset<Payload> CreatePayload(::flatbuffers::FlatBufferBuilder &_fbb, const PayloadT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ActionEnvelopeT : public ::flatbuffers::NativeTable {
  typedef ActionEnvelope TableType;
  uint16_t version = 1;
  std::string action_type{};
  std::unique_ptr<kungfu::action::fb::SchemaRefT> schema_ref{};
  std::unique_ptr<kungfu::action::fb::ActorT> actor{};
  std::unique_ptr<kungfu::action::fb::SessionT> session{};
  std::unique_ptr<kungfu::action::fb::SourceT> source{};
  std::unique_ptr<kungfu::action::fb::BatchT> batch{};
  std::unique_ptr<kungfu::action::fb::JournalT> journal{};
  std::unique_ptr<kungfu::action::fb::PayloadT> payload{};
  ActionEnvelopeT() = default;
  ActionEnvelopeT(const ActionEnvelopeT &o);
  ActionEnvelopeT(ActionEnvelopeT&&) FLATBUFFERS_NOEXCEPT = default;
  ActionEnvelopeT &operator=(ActionEnvelopeT o) FLATBUFFERS_NOEXCEPT;
};

struct ActionEnvelope FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ActionEnvelopeT NativeTableType;
  typedef ActionEnvelopeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_ACTION_TYPE = 6,
    VT_SCHEMA_REF = 8,
    VT_ACTOR = 10,
    VT_SESSION = 12,
    VT_SOURCE = 14,
    VT_BATCH = 16,
    VT_JOURNAL = 18,
    VT_PAYLOAD = 20
  };
  uint16_t version() const {
    return GetField<uint16_t>(VT_VERSION, 1);
  }
  const ::flatbuffers::String *action_type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACTION_TYPE);
  }
  const kungfu::action::fb::SchemaRef *schema_ref() const {
    return GetPointer<const kungfu::action::fb::SchemaRef *>(VT_SCHEMA_REF);
  }
  const kungfu::action::fb::Actor *actor() const {
    return GetPointer<const kungfu::action::fb::Actor *>(VT_ACTOR);
  }
  const kungfu::action::fb::Session *session() const {
    return GetPointer<const kungfu::action::fb::Session *>(VT_SESSION);
  }
  const kungfu::action::fb::Source *source() const {
    return GetPointer<const kungfu::action::fb::Source *>(VT_SOURCE);
  }
  const kungfu::action::fb::Batch *batch() const {
    return GetPointer<const kungfu::action::fb::Batch *>(VT_BATCH);
  }
  const kungfu::action::fb::Journal *journal() const {
    return GetPointer<const kungfu::action::fb::Journal *>(VT_JOURNAL);
  }
  const kungfu::action::fb::Payload *payload() const {
    return GetPointer<const kungfu::action::fb::Payload *>(VT_PAYLOAD);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_VERSION, 2) &&
           VerifyOffsetRequired(verifier, VT_ACTION_TYPE) &&
           verifier.VerifyString(action_type()) &&
           VerifyOffsetRequired(verifier, VT_SCHEMA_REF) &&
           verifier.VerifyTable(schema_ref()) &&
           VerifyOffset(verifier, VT_ACTOR) &&
           verifier.VerifyTable(actor()) &&
           VerifyOffset(verifier, VT_SESSION) &&
           verifier.VerifyTable(session()) &&
           VerifyOffset(verifier, VT_SOURCE) &&
           verifier.VerifyTable(source()) &&
           VerifyOffset(verifier, VT_BATCH) &&
           verifier.VerifyTable(batch()) &&
           VerifyOffset(verifier, VT_JOURNAL) &&
           verifier.VerifyTable(journal()) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyTable(payload()) &&
           verifier.EndTable();
  }
  ActionEnvelopeT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ActionEnvelopeT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ActionEnvelope> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ActionEnvelopeT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ActionEnvelopeBuilder {
  typedef ActionEnvelope Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_version(uint16_t version) {
    fbb_.AddElement<uint16_t>(ActionEnvelope::VT_VERSION, version, 1);
  }
  void add_action_type(::flatbuffers::Offset<::flatbuffers::String> action_type) {
    fbb_.AddOffset(ActionEnvelope::VT_ACTION_TYPE, action_type);
  }
  void add_schema_ref(::flatbuffers::Offset<kungfu::action::fb::SchemaRef> schema_ref) {
    fbb_.AddOffset(ActionEnvelope::VT_SCHEMA_REF, schema_ref);
  }
  void add_actor(::flatbuffers::Offset<kungfu::action::fb::Actor> actor) {
    fbb_.AddOffset(ActionEnvelope::VT_ACTOR, actor);
  }
  void add_session(::flatbuffers::Offset<kungfu::action::fb::Session> session) {
    fbb_.AddOffset(ActionEnvelope::VT_SESSION, session);
  }
  void add_source(::flatbuffers::Offset<kungfu::action::fb::Source> source) {
    fbb_.AddOffset(ActionEnvelope::VT_SOURCE, source);
  }
  void add_batch(::flatbuffers::Offset<kungfu::action::fb::Batch> batch) {
    fbb_.AddOffset(ActionEnvelope::VT_BATCH, batch);
  }
  void add_journal(::flatbuffers::Offset<kungfu::action::fb::Journal> journal) {
    fbb_.AddOffset(ActionEnvelope::VT_JOURNAL, journal);
  }
  void add_payload(::flatbuffers::Offset<kungfu::action::fb::Payload> payload) {
    fbb_.AddOffset(ActionEnvelope::VT_PAYLOAD, payload);
  }
  explicit ActionEnvelopeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ActionEnvelope> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ActionEnvelope>(end);
    fbb_.Required(o, ActionEnvelope::VT_ACTION_TYPE);
    fbb_.Required(o, ActionEnvelope::VT_SCHEMA_REF);
    return o;
  }
};

inline ::flatbuffers::Offset<ActionEnvelope> CreateActionEnvelope(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t version = 1,
    ::flatbuffers::Offset<::flatbuffers::String> action_type = 0,
    ::flatbuffers::Offset<kungfu::action::fb::SchemaRef> schema_ref = 0,
    ::flatbuffers::Offset<kungfu::action::fb::Actor> actor = 0,
    ::flatbuffers::Offset<kungfu::action::fb::Session> session = 0,
    ::flatbuffers::Offset<kungfu::action::fb::Source> source = 0,
    ::flatbuffers::Offset<kungfu::action::fb::Batch> batch = 0,
    ::flatbuffers::Offset<kungfu::action::fb::Journal> journal = 0,
    ::flatbuffers::Offset<kungfu::action::fb::Payload> payload = 0) {
  ActionEnvelopeBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_journal(journal);
  builder_.add_batch(batch);
  builder_.add_source(source);
  builder_.add_session(session);
  builder_.add_actor(actor);
  builder_.add_schema_ref(schema_ref);
  builder_.add_action_type(action_type);
  builder_.add_version(version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ActionEnvelope> CreateActionEnvelopeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t version = 1,
    const char *action_type = nullptr,
    ::flatbuffers::Offset<kungfu::action::fb::SchemaRef> schema_ref = 0,
    ::flatbuffers::Offset<kungfu::action::fb::Actor> actor = 0,
    ::flatbuffers::Offset<kungfu::action::fb::Session> session = 0,
    ::flatbuffers::Offset<kungfu::action::fb::Source> source = 0,
    ::flatbuffers::Offset<kungfu::action::fb::Batch> batch = 0,
    ::flatbuffers::Offset<kungfu::action::fb::Journal> journal = 0,
    ::flatbuffers::Offset<kungfu::action::fb::Payload> payload = 0) {
  auto action_type__ = action_type ? _fbb.CreateString(action_type) : 0;
  return kungfu::action::fb::CreateActionEnvelope(
      _fbb,
      version,
      action_type__,
      schema_ref,
      actor,
      session,
      source,
      batch,
      journal,
      payload);
}

::flatbuffers::Offset<ActionEnvelope> CreateActionEnvelope(::flatbuffers::FlatBufferBuilder &_fbb, const ActionEnvelopeT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline SchemaRefT *SchemaRef::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SchemaRefT>(new SchemaRefT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SchemaRef::UnPackTo(SchemaRefT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = id(); if (_e) _o->id = _e->str(); }
  { auto _e = version(); _o->version = _e; }
}

inline ::flatbuffers::Offset<SchemaRef> SchemaRef::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SchemaRefT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSchemaRef(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SchemaRef> CreateSchemaRef(::flatbuffers::FlatBufferBuilder &_fbb, const SchemaRefT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SchemaRefT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _id = _fbb.CreateString(_o->id);
  auto _version = _o->version;
  return kungfu::action::fb::CreateSchemaRef(
      _fbb,
      _id,
      _version);
}

inline ActorT *Actor::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ActorT>(new ActorT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Actor::UnPackTo(ActorT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = id(); if (_e) _o->id = _e->str(); }
  { auto _e = kind(); if (_e) _o->kind = _e->str(); }
  { auto _e = storage_source_id(); if (_e) _o->storage_source_id = _e->str(); }
  { auto _e = source_type(); if (_e) _o->source_type = _e->str(); }
}

inline ::flatbuffers::Offset<Actor> Actor::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ActorT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateActor(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Actor> CreateActor(::flatbuffers::FlatBufferBuilder &_fbb, const ActorT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ActorT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _id = _o->id.empty() ? 0 : _fbb.CreateString(_o->id);
  auto _kind = _o->kind.empty() ? 0 : _fbb.CreateString(_o->kind);
  auto _storage_source_id = _o->storage_source_id.empty() ? 0 : _fbb.CreateString(_o->storage_source_id);
  auto _source_type = _o->source_type.empty() ? 0 : _fbb.CreateString(_o->source_type);
  return kungfu::action::fb::CreateActor(
      _fbb,
      _id,
      _kind,
      _storage_source_id,
      _source_type);
}

inline SessionT *Session::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SessionT>(new SessionT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Session::UnPackTo(SessionT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = run_id(); if (_e) _o->run_id = _e->str(); }
  { auto _e = import_id(); if (_e) _o->import_id = _e->str(); }
}

inline ::flatbuffers::Offset<Session> Session::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SessionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSession(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Session> CreateSession(::flatbuffers::FlatBufferBuilder &_fbb, const SessionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SessionT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _run_id = _o->run_id.empty() ? 0 : _fbb.CreateString(_o->run_id);
  auto _import_id = _o->import_id.empty() ? 0 : _fbb.CreateString(_o->import_id);
  return kungfu::action::fb::CreateSession(
      _fbb,
      _run_id,
      _import_id);
}

inline SourceT *Source::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SourceT>(new SourceT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Source::UnPackTo(SourceT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = kind(); if (_e) _o->kind = _e->str(); }
  { auto _e = source_id(); if (_e) _o->source_id = _e->str(); }
  { auto _e = source_path(); if (_e) _o->source_path = _e->str(); }
  { auto _e = source_time(); if (_e) _o->source_time = _e->str(); }
  { auto _e = schema_version(); _o->schema_version = _e; }
}

inline ::flatbuffers::Offset<Source> Source::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SourceT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSource(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Source> CreateSource(::flatbuffers::FlatBufferBuilder &_fbb, const SourceT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SourceT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _kind = _o->kind.empty() ? 0 : _fbb.CreateString(_o->kind);
  auto _source_id = _o->source_id.empty() ? 0 : _fbb.CreateString(_o->source_id);
  auto _source_path = _o->source_path.empty() ? 0 : _fbb.CreateString(_o->source_path);
  auto _source_time = _o->source_time.empty() ? 0 : _fbb.CreateString(_o->source_time);
  auto _schema_version = _o->schema_version;
  return kungfu::action::fb::CreateSource(
      _fbb,
      _kind,
      _source_id,
      _source_path,
      _source_time,
      _schema_version);
}

inline BatchT *Batch::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BatchT>(new BatchT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Batch::UnPackTo(BatchT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = repo_root(); if (_e) _o->repo_root = _e->str(); }
  { auto _e = repo_head(); if (_e) _o->repo_head = _e->str(); }
  { auto _e = schema_version(); _o->schema_version = _e; }
  { auto _e = missions(); _o->missions = _e; }
  { auto _e = goals(); _o->goals = _e; }
  { auto _e = markers(); _o->markers = _e; }
  { auto _e = warnings(); _o->warnings = _e; }
}

inline ::flatbuffers::Offset<Batch> Batch::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BatchT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBatch(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Batch> CreateBatch(::flatbuffers::FlatBufferBuilder &_fbb, const BatchT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BatchT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _repo_root = _o->repo_root.empty() ? 0 : _fbb.CreateString(_o->repo_root);
  auto _repo_head = _o->repo_head.empty() ? 0 : _fbb.CreateString(_o->repo_head);
  auto _schema_version = _o->schema_version;
  auto _missions = _o->missions;
  auto _goals = _o->goals;
  auto _markers = _o->markers;
  auto _warnings = _o->warnings;
  return kungfu::action::fb::CreateBatch(
      _fbb,
      _repo_root,
      _repo_head,
      _schema_version,
      _missions,
      _goals,
      _markers,
      _warnings);
}

inline JournalT *Journal::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<JournalT>(new JournalT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Journal::UnPackTo(JournalT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = frame_uid(); _o->frame_uid = _e; }
  { auto _e = trigger_frame_uid(); _o->trigger_frame_uid = _e; }
  { auto _e = stream_id(); _o->stream_id = _e; }
  { auto _e = gen_time(); _o->gen_time = _e; }
  { auto _e = trigger_time(); _o->trigger_time = _e; }
  { auto _e = carrier_type(); _o->carrier_type = _e; }
  { auto _e = source(); _o->source = _e; }
  { auto _e = initial_source(); _o->initial_source = _e; }
  { auto _e = dest(); _o->dest = _e; }
  { auto _e = data_length(); _o->data_length = _e; }
  { auto _e = data_type(); _o->data_type = _e; }
  { auto _e = integrity_version(); _o->integrity_version = _e; }
  { auto _e = checksum_algorithm(); if (_e) _o->checksum_algorithm = _e->str(); }
  { auto _e = payload_checksum(); _o->payload_checksum = _e; }
  { auto _e = frame_checksum(); _o->frame_checksum = _e; }
}

inline ::flatbuffers::Offset<Journal> Journal::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const JournalT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateJournal(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Journal> CreateJournal(::flatbuffers::FlatBufferBuilder &_fbb, const JournalT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const JournalT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _frame_uid = _o->frame_uid;
  auto _trigger_frame_uid = _o->trigger_frame_uid;
  auto _stream_id = _o->stream_id;
  auto _gen_time = _o->gen_time;
  auto _trigger_time = _o->trigger_time;
  auto _carrier_type = _o->carrier_type;
  auto _source = _o->source;
  auto _initial_source = _o->initial_source;
  auto _dest = _o->dest;
  auto _data_length = _o->data_length;
  auto _data_type = _o->data_type;
  auto _integrity_version = _o->integrity_version;
  auto _checksum_algorithm = _o->checksum_algorithm.empty() ? 0 : _fbb.CreateString(_o->checksum_algorithm);
  auto _payload_checksum = _o->payload_checksum;
  auto _frame_checksum = _o->frame_checksum;
  return kungfu::action::fb::CreateJournal(
      _fbb,
      _frame_uid,
      _trigger_frame_uid,
      _stream_id,
      _gen_time,
      _trigger_time,
      _carrier_type,
      _source,
      _initial_source,
      _dest,
      _data_length,
      _data_type,
      _integrity_version,
      _checksum_algorithm,
      _payload_checksum,
      _frame_checksum);
}

inline PayloadT *Payload::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<PayloadT>(new PayloadT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Payload::UnPackTo(PayloadT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = encoding(); _o->encoding = _e; }
  { auto _e = data(); if (_e) { _o->data.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->data.begin()); } }
  { auto _e = hash_algorithm(); if (_e) _o->hash_algorithm = _e->str(); }
  { auto _e = hash(); if (_e) _o->hash = _e->str(); }
  { auto _e = byte_len(); _o->byte_len = _e; }
  { auto _e = content_type(); if (_e) _o->content_type = _e->str(); }
  { auto _e = state(); if (_e) _o->state = _e->str(); }
}

inline ::flatbuffers::Offset<Payload> Payload::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PayloadT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreatePayload(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Payload> CreatePayload(::flatbuffers::FlatBufferBuilder &_fbb, const PayloadT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const PayloadT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _encoding = _o->encoding;
  auto _data = _o->data.size() ? _fbb.CreateVector(_o->data) : 0;
  auto _hash_algorithm = _o->hash_algorithm.empty() ? 0 : _fbb.CreateString(_o->hash_algorithm);
  auto _hash = _o->hash.empty() ? 0 : _fbb.CreateString(_o->hash);
  auto _byte_len = _o->byte_len;
  auto _content_type = _o->content_type.empty() ? 0 : _fbb.CreateString(_o->content_type);
  auto _state = _o->state.empty() ? 0 : _fbb.CreateString(_o->state);
  return kungfu::action::fb::CreatePayload(
      _fbb,
      _encoding,
      _data,
      _hash_algorithm,
      _hash,
      _byte_len,
      _content_type,
      _state);
}

inline ActionEnvelopeT::ActionEnvelopeT(const ActionEnvelopeT &o)
      : version(o.version),
        action_type(o.action_type),
        schema_ref((o.schema_ref) ? new kungfu::action::fb::SchemaRefT(*o.schema_ref) : nullptr),
        actor((o.actor) ? new kungfu::action::fb::ActorT(*o.actor) : nullptr),
        session((o.session) ? new kungfu::action::fb::SessionT(*o.session) : nullptr),
        source((o.source) ? new kungfu::action::fb::SourceT(*o.source) : nullptr),
        batch((o.batch) ? new kungfu::action::fb::BatchT(*o.batch) : nullptr),
        journal((o.journal) ? new kungfu::action::fb::JournalT(*o.journal) : nullptr),
        payload((o.payload) ? new kungfu::action::fb::PayloadT(*o.payload) : nullptr) {
}

inline ActionEnvelopeT &ActionEnvelopeT::operator=(ActionEnvelopeT o) FLATBUFFERS_NOEXCEPT {
  std::swap(version, o.version);
  std::swap(action_type, o.action_type);
  std::swap(schema_ref, o.schema_ref);
  std::swap(actor, o.actor);
  std::swap(session, o.session);
  std::swap(source, o.source);
  std::swap(batch, o.batch);
  std::swap(journal, o.journal);
  std::swap(payload, o.payload);
  return *this;
}

inline ActionEnvelopeT *ActionEnvelope::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ActionEnvelopeT>(new ActionEnvelopeT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ActionEnvelope::UnPackTo(ActionEnvelopeT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = version(); _o->version = _e; }
  { auto _e = action_type(); if (_e) _o->action_type = _e->str(); }
  { auto _e = schema_ref(); if (_e) { if(_o->schema_ref) { _e->UnPackTo(_o->schema_ref.get(), _resolver); } else { _o->schema_ref = std::unique_ptr<kungfu::action::fb::SchemaRefT>(_e->UnPack(_resolver)); } } else if (_o->schema_ref) { _o->schema_ref.reset(); } }
  { auto _e = actor(); if (_e) { if(_o->actor) { _e->UnPackTo(_o->actor.get(), _resolver); } else { _o->actor = std::unique_ptr<kungfu::action::fb::ActorT>(_e->UnPack(_resolver)); } } else if (_o->actor) { _o->actor.reset(); } }
  { auto _e = session(); if (_e) { if(_o->session) { _e->UnPackTo(_o->session.get(), _resolver); } else { _o->session = std::unique_ptr<kungfu::action::fb::SessionT>(_e->UnPack(_resolver)); } } else if (_o->session) { _o->session.reset(); } }
  { auto _e = source(); if (_e) { if(_o->source) { _e->UnPackTo(_o->source.get(), _resolver); } else { _o->source = std::unique_ptr<kungfu::action::fb::SourceT>(_e->UnPack(_resolver)); } } else if (_o->source) { _o->source.reset(); } }
  { auto _e = batch(); if (_e) { if(_o->batch) { _e->UnPackTo(_o->batch.get(), _resolver); } else { _o->batch = std::unique_ptr<kungfu::action::fb::BatchT>(_e->UnPack(_resolver)); } } else if (_o->batch) { _o->batch.reset(); } }
  { auto _e = journal(); if (_e) { if(_o->journal) { _e->UnPackTo(_o->journal.get(), _resolver); } else { _o->journal = std::unique_ptr<kungfu::action::fb::JournalT>(_e->UnPack(_resolver)); } } else if (_o->journal) { _o->journal.reset(); } }
  { auto _e = payload(); if (_e) { if(_o->payload) { _e->UnPackTo(_o->payload.get(), _resolver); } else { _o->payload = std::unique_ptr<kungfu::action::fb::PayloadT>(_e->UnPack(_resolver)); } } else if (_o->payload) { _o->payload.reset(); } }
}

inline ::flatbuffers::Offset<ActionEnvelope> ActionEnvelope::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ActionEnvelopeT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateActionEnvelope(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ActionEnvelope> CreateActionEnvelope(::flatbuffers::FlatBufferBuilder &_fbb, const ActionEnvelopeT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ActionEnvelopeT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _version = _o->version;
  auto _action_type = _fbb.CreateString(_o->action_type);
  auto _schema_ref = _o->schema_ref ? CreateSchemaRef(_fbb, _o->schema_ref.get(), _rehasher) : 0;
  auto _actor = _o->actor ? CreateActor(_fbb, _o->actor.get(), _rehasher) : 0;
  auto _session = _o->session ? CreateSession(_fbb, _o->session.get(), _rehasher) : 0;
  auto _source = _o->source ? CreateSource(_fbb, _o->source.get(), _rehasher) : 0;
  auto _batch = _o->batch ? CreateBatch(_fbb, _o->batch.get(), _rehasher) : 0;
  auto _journal = _o->journal ? CreateJournal(_fbb, _o->journal.get(), _rehasher) : 0;
  auto _payload = _o->payload ? CreatePayload(_fbb, _o->payload.get(), _rehasher) : 0;
  return kungfu::action::fb::CreateActionEnvelope(
      _fbb,
      _version,
      _action_type,
      _schema_ref,
      _actor,
      _session,
      _source,
      _batch,
      _journal,
      _payload);
}

inline const kungfu::action::fb::ActionEnvelope *GetActionEnvelope(const void *buf) {
  return ::flatbuffers::GetRoot<kungfu::action::fb::ActionEnvelope>(buf);
}

inline const kungfu::action::fb::ActionEnvelope *GetSizePrefixedActionEnvelope(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<kungfu::action::fb::ActionEnvelope>(buf);
}

inline const char *ActionEnvelopeIdentifier() {
  return "KFAE";
}

inline bool ActionEnvelopeBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, ActionEnvelopeIdentifier());
}

inline bool SizePrefixedActionEnvelopeBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, ActionEnvelopeIdentifier(), true);
}

inline bool VerifyActionEnvelopeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<kungfu::action::fb::ActionEnvelope>(ActionEnvelopeIdentifier());
}

inline bool VerifySizePrefixedActionEnvelopeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<kungfu::action::fb::ActionEnvelope>(ActionEnvelopeIdentifier());
}

inline const char *ActionEnvelopeExtension() {
  return "kfae";
}

inline void FinishActionEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<kungfu::action::fb::ActionEnvelope> root) {
  fbb.Finish(root, ActionEnvelopeIdentifier());
}

inline void FinishSizePrefixedActionEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<kungfu::action::fb::ActionEnvelope> root) {
  fbb.FinishSizePrefixed(root, ActionEnvelopeIdentifier());
}

inline std::unique_ptr<kungfu::action::fb::ActionEnvelopeT> UnPackActionEnvelope(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<kungfu::action::fb::ActionEnvelopeT>(GetActionEnvelope(buf)->UnPack(res));
}

inline std::unique_ptr<kungfu::action::fb::ActionEnvelopeT> UnPackSizePrefixedActionEnvelope(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<kungfu::action::fb::ActionEnvelopeT>(GetSizePrefixedActionEnvelope(buf)->UnPack(res));
}

}  // namespace fb
}  // namespace action
}  // namespace kungfu

#endif  // FLATBUFFERS_GENERATED_ACTIONENVELOPE_KUNGFU_ACTION_FB_H_
