# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ArtifactRecorded(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ArtifactRecorded()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsArtifactRecorded(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ArtifactRecorded
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ArtifactRecorded
    def WorkId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ArtifactRecorded
    def Ref(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ArtifactRecorded
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ArtifactRecordedStart(builder):
    builder.StartObject(3)

def Start(builder):
    ArtifactRecordedStart(builder)

def ArtifactRecordedAddWorkId(builder, workId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(workId), 0)

def AddWorkId(builder, workId):
    ArtifactRecordedAddWorkId(builder, workId)

def ArtifactRecordedAddRef(builder, ref):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(ref), 0)

def AddRef(builder, ref):
    ArtifactRecordedAddRef(builder, ref)

def ArtifactRecordedAddKind(builder, kind):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(kind), 0)

def AddKind(builder, kind):
    ArtifactRecordedAddKind(builder, kind)

def ArtifactRecordedEnd(builder):
    return builder.EndObject()

def End(builder):
    return ArtifactRecordedEnd(builder)
