# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CheckpointRecorded(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CheckpointRecorded()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCheckpointRecorded(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CheckpointRecorded
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CheckpointRecorded
    def WorkId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CheckpointRecorded
    def Note(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def CheckpointRecordedStart(builder):
    builder.StartObject(2)

def Start(builder):
    CheckpointRecordedStart(builder)

def CheckpointRecordedAddWorkId(builder, workId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(workId), 0)

def AddWorkId(builder, workId):
    CheckpointRecordedAddWorkId(builder, workId)

def CheckpointRecordedAddNote(builder, note):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(note), 0)

def AddNote(builder, note):
    CheckpointRecordedAddNote(builder, note)

def CheckpointRecordedEnd(builder):
    return builder.EndObject()

def End(builder):
    return CheckpointRecordedEnd(builder)
