# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DecisionRecorded(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DecisionRecorded()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDecisionRecorded(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DecisionRecorded
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DecisionRecorded
    def WorkId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DecisionRecorded
    def Decision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DecisionRecorded
    def DecidedBy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def DecisionRecordedStart(builder):
    builder.StartObject(3)

def Start(builder):
    DecisionRecordedStart(builder)

def DecisionRecordedAddWorkId(builder, workId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(workId), 0)

def AddWorkId(builder, workId):
    DecisionRecordedAddWorkId(builder, workId)

def DecisionRecordedAddDecision(builder, decision):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(decision), 0)

def AddDecision(builder, decision):
    DecisionRecordedAddDecision(builder, decision)

def DecisionRecordedAddDecidedBy(builder, decidedBy):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(decidedBy), 0)

def AddDecidedBy(builder, decidedBy):
    DecisionRecordedAddDecidedBy(builder, decidedBy)

def DecisionRecordedEnd(builder):
    return builder.EndObject()

def End(builder):
    return DecisionRecordedEnd(builder)
