# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class NextActionSet(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NextActionSet()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNextActionSet(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # NextActionSet
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NextActionSet
    def WorkId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # NextActionSet
    def NextAction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def NextActionSetStart(builder):
    builder.StartObject(2)

def Start(builder):
    NextActionSetStart(builder)

def NextActionSetAddWorkId(builder, workId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(workId), 0)

def AddWorkId(builder, workId):
    NextActionSetAddWorkId(builder, workId)

def NextActionSetAddNextAction(builder, nextAction):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(nextAction), 0)

def AddNextAction(builder, nextAction):
    NextActionSetAddNextAction(builder, nextAction)

def NextActionSetEnd(builder):
    return builder.EndObject()

def End(builder):
    return NextActionSetEnd(builder)
