# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RunLinked(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RunLinked()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRunLinked(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RunLinked
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RunLinked
    def WorkId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunLinked
    def RunId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def RunLinkedStart(builder):
    builder.StartObject(2)

def Start(builder):
    RunLinkedStart(builder)

def RunLinkedAddWorkId(builder, workId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(workId), 0)

def AddWorkId(builder, workId):
    RunLinkedAddWorkId(builder, workId)

def RunLinkedAddRunId(builder, runId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(runId), 0)

def AddRunId(builder, runId):
    RunLinkedAddRunId(builder, runId)

def RunLinkedEnd(builder):
    return builder.EndObject()

def End(builder):
    return RunLinkedEnd(builder)
