# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ValidationRecorded(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ValidationRecorded()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsValidationRecorded(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ValidationRecorded
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ValidationRecorded
    def WorkId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ValidationRecorded
    def Result(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ValidationRecorded
    def Command(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ValidationRecorded
    def Note(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ValidationRecordedStart(builder):
    builder.StartObject(4)

def Start(builder):
    ValidationRecordedStart(builder)

def ValidationRecordedAddWorkId(builder, workId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(workId), 0)

def AddWorkId(builder, workId):
    ValidationRecordedAddWorkId(builder, workId)

def ValidationRecordedAddResult(builder, result):
    builder.PrependInt8Slot(1, result, 0)

def AddResult(builder, result):
    ValidationRecordedAddResult(builder, result)

def ValidationRecordedAddCommand(builder, command):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(command), 0)

def AddCommand(builder, command):
    ValidationRecordedAddCommand(builder, command)

def ValidationRecordedAddNote(builder, note):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(note), 0)

def AddNote(builder, note):
    ValidationRecordedAddNote(builder, note)

def ValidationRecordedEnd(builder):
    return builder.EndObject()

def End(builder):
    return ValidationRecordedEnd(builder)
