# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WorkStatusChanged(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorkStatusChanged()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorkStatusChanged(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WorkStatusChanged
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorkStatusChanged
    def WorkId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WorkStatusChanged
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # WorkStatusChanged
    def Reason(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def WorkStatusChangedStart(builder):
    builder.StartObject(3)

def Start(builder):
    WorkStatusChangedStart(builder)

def WorkStatusChangedAddWorkId(builder, workId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(workId), 0)

def AddWorkId(builder, workId):
    WorkStatusChangedAddWorkId(builder, workId)

def WorkStatusChangedAddStatus(builder, status):
    builder.PrependInt8Slot(1, status, 0)

def AddStatus(builder, status):
    WorkStatusChangedAddStatus(builder, status)

def WorkStatusChangedAddReason(builder, reason):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(reason), 0)

def AddReason(builder, reason):
    WorkStatusChangedAddReason(builder, reason)

def WorkStatusChangedEnd(builder):
    return builder.EndObject()

def End(builder):
    return WorkStatusChangedEnd(builder)
