# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WorkItemCreated(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorkItemCreated()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorkItemCreated(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WorkItemCreated
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorkItemCreated
    def WorkId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WorkItemCreated
    def Title(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WorkItemCreated
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WorkItemCreated
    def Summary(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WorkItemCreated
    def SchemaVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def WorkItemCreatedStart(builder):
    builder.StartObject(5)

def Start(builder):
    WorkItemCreatedStart(builder)

def WorkItemCreatedAddWorkId(builder, workId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(workId), 0)

def AddWorkId(builder, workId):
    WorkItemCreatedAddWorkId(builder, workId)

def WorkItemCreatedAddTitle(builder, title):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(title), 0)

def AddTitle(builder, title):
    WorkItemCreatedAddTitle(builder, title)

def WorkItemCreatedAddKind(builder, kind):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(kind), 0)

def AddKind(builder, kind):
    WorkItemCreatedAddKind(builder, kind)

def WorkItemCreatedAddSummary(builder, summary):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(summary), 0)

def AddSummary(builder, summary):
    WorkItemCreatedAddSummary(builder, summary)

def WorkItemCreatedAddSchemaVersion(builder, schemaVersion):
    builder.PrependUint32Slot(4, schemaVersion, 0)

def AddSchemaVersion(builder, schemaVersion):
    WorkItemCreatedAddSchemaVersion(builder, schemaVersion)

def WorkItemCreatedEnd(builder):
    return builder.EndObject()

def End(builder):
    return WorkItemCreatedEnd(builder)
