// @generated by scripts/generate-kfx-authoring-kit.mjs source_path=framework/api/src/capability/service-authz.ts
import type { KfLocator, KfNativeBinding } from './types.js';
export type KfxHost = 'gui' | 'tui' | 'cli' | 'agent';
export type KfxNodeState = 'active' | 'dormant' | 'degraded';
export type KfxRuntimeHost =
  | 'gui'
  | 'wasm'
  | 'adapter-node'
  | 'adapter-python'
  | 'service-node'
  | 'service-python'
  | 'service-cpp'
  | 'profile';
export type KfxHostContribution = {
  state: KfxNodeState;
  contributionRoot: string;
  ownerProviderRoot: string;
  ownerTrustRoot: string;
  capabilityRoot: string;
  facetRoot: string;
  capabilities: string[];
  authorization: {
    schema: 'kungfu.kfx.host-authorization/v2';
    packageKey: string;
    packageRoot: string;
    manifestRoot: string;
    ownerProviderRoot: string;
    trustRoot: string;
    runtimeTier: 'isolated' | 'integrated-explicit' | 'metadata-only';
    admissionGrade: 'unverified' | 'identity-verified' | 'kfd-attested';
    placement: string;
    requiredCapabilities: string[];
    grantedCapabilities: string[];
    reportRoot: string | null;
    admissionPlanRoot: string | null;
    corePolicyRoot: string | null;
    requestedPolicyRoot: string | null;
    policyRoot: string | null;
    authorizationPlanRoot: string | null;
    capabilityDeclarationRoot: string | null;
    capabilityGrantRoot: string | null;
    warrantRoot: string | null;
    cutRoot: string | null;
    revision: number;
    generationRoot: string;
    executionAllowed: boolean;
    authorizationRoot: string;
  };
  presentation?: {
    optional?: boolean;
    hosts?: KfxHost[];
  };
  [key: string]: unknown;
};
export type KfxExperienceFlowDescriptor = {
  schema: 'kungfu.kfx.experience-flow-host/v3';
  descriptorRoot: string;
  registryRoot: string;
  graphRoot: string;
  planRoot: string;
  receiptDependencyRoot: string;
  cutRoot: string | null;
  revision: number;
  generation: {
    schema: 'kungfu.kfx.host-generation/v2';
    registryRoot: string;
    graphRoot: string;
    cutRoot: string | null;
    revision: number;
  };
  generationRoot: string;
  admission: {
    schema: 'kungfu.kfx.host-admission/v2';
    state: 'admitted' | 'preview-only';
    exactRootRequired: true;
    registryRoot: string;
    graphRoot: string;
    planRoot: string;
    cutRoot: string | null;
    revision: number;
    generationRoot: string;
    contributionRoots: string[];
    facetRoots: string[];
    capabilityRoots: string[];
    authorizationRoots: string[];
    runtimeAuthorizationRoots: string[];
  };
  runtimeAuthorizations: Array<
    KfxHostContribution['authorization'] & {
      host: KfxRuntimeHost;
    }
  >;
  contributions: KfxHostContribution[];
};
export type KfxHostProjection = {
  schema: 'kungfu.kfx.host-projection/v1';
  host: KfxHost;
  descriptorRoot: string;
  graphRoot: string;
  planRoot: string;
  receiptDependencyRoot: string;
  cutRoot: string | null;
  revision: number;
  generationRoot: string;
  admissionState: 'admitted' | 'preview-only';
  diagnostics: Array<{
    code: 'KF_KFX_HOST_NOT_ADMITTED' | 'KF_KFX_PRESENTATION_DORMANT';
    contributionRoot?: string;
    recoveryGuidance: string[];
  }>;
  contributions: Array<
    KfxHostContribution & {
      semanticState: KfxNodeState;
      presentationState: KfxNodeState;
      executionEligible: boolean;
    }
  >;
};
export declare function projectKfxExperienceFlowHost(
  descriptor: KfxExperienceFlowDescriptor,
  host: KfxHost,
): KfxHostProjection;
export declare function authorizeKfxHostLaunch(
  descriptor: KfxExperienceFlowDescriptor,
  packageKey: string,
  host: KfxRuntimeHost,
  expectedAuthorizationRoot: string,
): KfxHostContribution['authorization'] & {
  host: KfxRuntimeHost;
};
export type KfxRuntimeWarrantAuthorization =
  KfxExperienceFlowDescriptor['runtimeAuthorizations'][number];
export type KfxRuntimeWarrantAdoption = {
  schema: 'kungfu.kfx.runtime-warrant-adoption/v1';
  executionAllowed: true;
  runtimeWarrant: {
    schema: 'kungfu.kfx.runtime-warrant/v1';
    warrantRoot: string;
    packageKey: string;
    host: KfxRuntimeHost;
    holder: string;
    capabilityGrantRoot: string;
    hostAuthorizationRoot: string;
    mutationWarrantRoot: string;
    expiresAt: number;
    heartbeatTtl: number;
  };
  leaseState: {
    schema: 'kungfu.kfx.runtime-lease-state-fact/v1';
    warrantRoot: string;
    packageKey: string;
    host: KfxRuntimeHost;
    holder: string;
    generation: number;
    fencingToken: string;
    state: 'active';
    heartbeatAt: number;
    heartbeatDeadline: number;
    expiresAt: number;
  };
  recovery: null | {
    schema: 'kungfu.kfx.runtime-warrant-transition/v1';
    event: 'lease-expired' | 'heartbeat-expired';
    leaseState: {
      state: 'recovered';
    } & Record<string, unknown>;
    receipt: Record<string, unknown>;
  };
  receipt: Record<string, unknown>;
};
export type KfxRuntimeWarrantTransition = {
  schema: 'kungfu.kfx.runtime-warrant-transition/v1';
  event: string;
  leaseState: Record<string, unknown> & {
    state: string;
  };
  receipt: Record<string, unknown>;
};
export type KfxRuntimeWarrant = {
  adopt: (
    authorization: KfxRuntimeWarrantAuthorization,
    request: {
      holder: string;
      purpose: string;
      leaseNonce: string;
      issuedAt: number;
      expiresAt: number;
      heartbeatTtl: number;
      residualResponsibility: string;
      requestedCapabilities: string[];
    },
  ) => KfxRuntimeWarrantAdoption;
  heartbeat: (
    adoption: KfxRuntimeWarrantAdoption,
    recordedAt: number,
  ) => KfxRuntimeWarrantTransition;
  settle: (
    adoption: KfxRuntimeWarrantAdoption,
    request: {
      recordedAt: number;
      outcome: string;
      residualResponsibilityDisposition: string;
    },
  ) => KfxRuntimeWarrantTransition;
};
export type OpenKfxRuntimeWarrantOptions = {
  binding: KfNativeBinding;
  locator: KfLocator;
};
export declare function openKfxRuntimeWarrant(
  options: OpenKfxRuntimeWarrantOptions,
): KfxRuntimeWarrant;
export type KfxControlRoot = {
  kind: 'product';
  path: string;
};
export type KfxControlAuthority = Record<string, unknown>;
export type KfxControlStatus = {
  schema: 'kungfu.kfx.control-suite-status/v1';
  controllerId: 'kungfu-kfx-control-suite';
  statusRoot: string;
  cutRoot: string | null;
  revision: number;
  mode: 'active' | 'safe-mode';
  executionAllowed: boolean;
  active: null | {
    packageRoot: string;
    manifestRoot: string;
    version: string;
  };
  lastKnownGood: null | {
    packageRoot: string;
    manifestRoot: string;
    version: string;
    sourcePath: string;
  };
  diagnostics: Array<{
    code: 'KF_KFX_CONTROL_SAFE_MODE';
    recoveryGuidance: string[];
  }>;
};
export type KfxControlPlan = {
  schema: 'kungfu.kfx.control-suite-plan/v1';
  controllerId: 'kungfu-kfx-control-suite';
  operation: 'install' | 'update';
  packageKey: 'kfx-manager';
  controlPlanRoot: string;
  bootstrapPolicyRoot: string;
  authorizationPlanRoot: string;
  capabilityGrantRoot: string;
  warrantRoot: string;
  allowed: true;
  requiresAuthorization: true;
  candidate: {
    packageRoot: string;
    manifestRoot: string;
    version: string;
  };
  loadPlan: {
    cutRoot: string | null;
    revision: number;
    registryRoot: string;
    graphRoot: string;
    planRoot: string;
    packages: Array<{
      key: string;
      packageRoot: string;
      trustRoot: string;
    }>;
  };
};
export type KfxControlApplication = {
  schema: 'kungfu.kfx.control-suite-application/v1';
  controllerId: 'kungfu-kfx-control-suite';
  controlPlanRoot: string;
  bootstrapPolicyRoot: string;
  authorizationPlanRoot: string;
  capabilityGrantRoot: string;
  warrantRoot: string;
  verified: true;
  status: KfxControlStatus;
  application: Record<string, unknown>;
};
export type KfxControlHostProjection = {
  schema: 'kungfu.kfx.control-host-projection/v1';
  host: KfxHost;
  controllerId: 'kungfu-kfx-control-suite';
  statusRoot: string;
  cutRoot: string | null;
  revision: number;
  mode: 'active' | 'safe-mode';
  executionAllowed: boolean;
  diagnostics: KfxControlStatus['diagnostics'];
};
export declare function projectKfxControlSuiteHost(
  status: KfxControlStatus,
  host: KfxHost,
): KfxControlHostProjection;
export type KfxControl = {
  status: () => KfxControlStatus;
  plan: (
    operation: 'install' | 'update',
    candidate: KfxControlRoot,
    authority: KfxControlAuthority,
  ) => KfxControlPlan;
  apply: (
    operation: 'install' | 'update',
    candidate: KfxControlRoot,
    plan: KfxControlPlan,
    authority: KfxControlAuthority,
    auditActor: string,
  ) => KfxControlApplication;
};
export type OpenKfxControlOptions = {
  binding: KfNativeBinding;
  locator: KfLocator;
};
export declare function openKfxControl(
  options: OpenKfxControlOptions,
): KfxControl;
