# SPDX-License-Identifier: Apache-2.0

import base64
import json
import subprocess
from pathlib import Path

import pytest
from click.testing import CliRunner

from kungfu import kfx_authoring, kfx_contract
from kungfu.cli.commands import __registry__  # noqa: F401
from kungfu.cli.commands import kfc


def scaffold(tmp_path: Path, key: str = "ordinary-webhook") -> Path:
    source = tmp_path / key
    plan = kfx_authoring.scaffold_plan(key, source)
    assert plan["willWrite"] is False
    assert not source.exists()
    receipt = kfx_authoring.apply_scaffold(plan)
    assert receipt["verified"] is True
    return source


def test_capabilities_bind_exact_installed_sdk_and_authority_boundary():
    capabilities = kfx_authoring.capabilities()
    repository_root = Path(__file__).resolve().parents[4]
    kfx_package = json.loads(
        (repository_root / "framework/kfx/package.json").read_text(encoding="utf-8")
    )

    assert capabilities["status"] == "available"
    assert capabilities["productVersion"] == kfx_package["version"]
    assert capabilities["sdk"]["source"].endswith("service-authz.ts")
    assert capabilities["sdk"]["root"].startswith("sha256:")
    assert capabilities["lifecycle"][:6] == [
        "inspect",
        "scaffold",
        "validate",
        "build",
        "qualify",
        "package",
    ]
    assert "authoring-does-not-grant-capabilities" in capabilities["nonClaims"]
    assert "source checkout" not in kfx_authoring.brief().lower()


def test_scaffold_is_plan_first_deterministic_and_rooted(tmp_path):
    title = 'Quoted "Webhook" 中文'
    left = kfx_authoring.scaffold_plan(
        "ordinary-webhook", tmp_path / "source", title=title
    )
    right = kfx_authoring.scaffold_plan(
        "ordinary-webhook", tmp_path / "source", title=title
    )

    assert left == right
    receipt = kfx_authoring.apply_scaffold(left)
    inspection = kfx_authoring.inspect_source(tmp_path / "source")

    assert receipt["sourceRoot"] == inspection["sourceRoot"]
    assert inspection["offline"] is True
    assert inspection["sourceFallback"] is False
    manifest = json.loads((tmp_path / "source" / "kungfu.kfx.json").read_text())
    package = json.loads((tmp_path / "source" / "package.json").read_text())
    assert kfx_contract.package_key(manifest) == "ordinary-webhook"
    assert package["description"] == (
        f"{title} - generated by the installed Kungfu KFX authoring kit"
    )
    assert manifest["kungfuConfig"]["config"]["service"]["host"]["schema"] == (
        "kungfu.kfx.service-host/v1"
    )


def test_sdk_drift_and_non_loopback_starter_fail_closed(tmp_path):
    source = scaffold(tmp_path)
    sdk = source / "sdk" / "service-webhook-host.mjs"
    sdk.write_text(sdk.read_text() + "\n// drift\n")
    with pytest.raises(kfx_authoring.KfxAuthoringError) as captured:
        kfx_authoring.inspect_source(source)
    assert captured.value.diagnosis["code"] == "sdk-root-mismatch"

    source = scaffold(tmp_path, "second-webhook")
    manifest_path = source / "kungfu.kfx.json"
    manifest = json.loads(manifest_path.read_text())
    manifest["kungfuConfig"]["config"]["service"]["host"]["webhook"]["listener"][
        "mode"
    ] = "explicit"
    manifest["kungfuConfig"]["config"]["service"]["host"]["webhook"]["listener"][
        "bindAddress"
    ] = "0.0.0.0"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")
    with pytest.raises(kfx_authoring.KfxAuthoringError) as captured:
        kfx_authoring.inspect_source(source)
    assert captured.value.diagnosis["code"] == "starter-listener-not-loopback"


def test_installed_only_webhook_lifecycle_build_qualification_and_package(tmp_path):
    source = scaffold(tmp_path)
    build = tmp_path / "build"
    build_plan = kfx_authoring.build_plan(source, build)
    assert build_plan["willWrite"] is False
    build_receipt = kfx_authoring.apply_build(build_plan)
    assert build_receipt["sourceRoot"] == build_receipt["artifactRoot"]

    qualification = kfx_authoring.qualify(build)
    assert qualification["status"] == "passed"
    assert qualification["installedOnly"] is True
    assert qualification["sourceFallback"] is False
    assert qualification["receiver"] == {
        "bindAddress": "127.0.0.1",
        "credentialMaterial": False,
        "externalNetwork": False,
    }
    assert qualification["intake"]["invalidCode"] == (
        "KF_KFX_WEBHOOK_AUTHENTICATION_FAILED"
    )
    assert qualification["intake"]["replayCode"] == "KF_KFX_WEBHOOK_REPLAYED"
    operations = [row["operation"] for row in qualification["lifecycle"]]
    for operation in (
        "start",
        "ready",
        "drain",
        "stop",
        "restart",
        "crash",
        "upgrade",
        "rollback",
        "deactivate",
        "uninstall",
    ):
        assert operation in operations

    package = tmp_path / "ordinary-webhook.tgz"
    package_plan = kfx_authoring.package_plan(build, package)
    assert package_plan["willWrite"] is False
    package_receipt = kfx_authoring.apply_package(package_plan)
    assert package_receipt["verified"] is True
    assert package_receipt["qualificationRoot"].startswith("sha256:")
    assert kfx_contract.package_key(kfx_contract.read_manifest_from_tgz(package)) == (
        "ordinary-webhook"
    )


def test_package_rejects_recomputed_traversal_and_qualification_is_bounded(
    tmp_path, monkeypatch
):
    source = scaffold(tmp_path)
    package = tmp_path / "ordinary-webhook.tgz"
    plan = kfx_authoring.package_plan(source, package)
    payload = b"escape"
    plan["material"]["../escape"] = base64.b64encode(payload).decode("ascii")
    plan["files"].append(
        {
            "path": "../escape",
            "sha256": kfx_authoring._sha256(payload),
            "bytes": len(payload),
        }
    )
    unsigned = {key: value for key, value in plan.items() if key != "planRoot"}
    plan["planRoot"] = kfx_authoring._root(unsigned)
    with pytest.raises(kfx_authoring.KfxAuthoringError) as captured:
        kfx_authoring.apply_package(plan)
    assert captured.value.diagnosis["code"] == "package-path-invalid"
    assert not package.exists()

    def timeout(*args, **kwargs):
        raise subprocess.TimeoutExpired(args[0], kwargs["timeout"])

    monkeypatch.setattr(kfx_authoring.subprocess, "run", timeout)
    with pytest.raises(kfx_authoring.KfxAuthoringError) as captured:
        kfx_authoring.qualify(source)
    assert captured.value.diagnosis == {
        "schema": "kungfu.kfx-authoring-diagnosis/v1",
        "code": "qualification-timeout",
        "message": "installed-only qualification exceeded its bounded runtime",
        "timeoutSeconds": 30,
    }


def test_cli_exposes_brief_plan_execute_and_stable_diagnosis(tmp_path):
    runner = CliRunner()
    capabilities = runner.invoke(kfc, ["kfx", "author", "capabilities", "--json"])
    assert capabilities.exit_code == 0, capabilities.output
    assert json.loads(capabilities.output)["status"] == "available"

    brief = runner.invoke(kfc, ["kfx", "author", "brief"])
    assert brief.exit_code == 0, brief.output
    assert "Installed KFX Authoring Brief" in brief.output

    source = tmp_path / "cli-webhook"
    preview = runner.invoke(
        kfc,
        [
            "kfx",
            "author",
            "scaffold",
            "cli-webhook",
            "--out",
            str(source),
            "--json",
        ],
    )
    assert preview.exit_code == 0, preview.output
    assert json.loads(preview.output)["willWrite"] is False
    assert not source.exists()

    applied = runner.invoke(
        kfc,
        [
            "kfx",
            "author",
            "scaffold",
            "cli-webhook",
            "--out",
            str(source),
            "--execute",
            "--json",
        ],
    )
    assert applied.exit_code == 0, applied.output
    assert json.loads(applied.output)["verified"] is True

    (source / "sdk" / "service-webhook-host.mjs").write_text("tampered\n")
    refused = runner.invoke(kfc, ["kfx", "author", "validate", str(source), "--json"])
    assert refused.exit_code == 1
    assert json.loads(refused.output)["code"] == "sdk-root-mismatch"
