# SPDX-License-Identifier: Apache-2.0
"""Stable collection facade for Assignment orchestration responsibilities."""
# ruff: noqa: F401,F403

from _assignment_orchestration_support import _bind_work_control_profile
from _assignment_orchestration_admission_cases import (
    test_assignment_atomic_paths_use_windows_extended_namespace,
    test_assignment_admit_defers_request_path_validation_to_orchestration,
    test_assignment_admit_omits_retired_atlas_root,
    test_captured_request_reads_all_paths_through_filesystem_namespace,
)
from _assignment_orchestration_family_cases import (
    test_initiative_family_state_is_rooted_bounded_and_parent_inert,
    test_retained_wave_0_v1_fixture_preserves_exact_bytes_and_root,
    test_initiative_family_rejects_invalid_membership_and_dependencies,
    test_family_transitions_bind_terminal_evidence_and_residual_only_successor,
    test_family_transition_fails_closed_on_scope_growth_and_invalid_coverage,
    test_family_deferred_terminal_requires_an_exact_decision_root,
    test_family_cli_writes_successor_without_overwriting_prior_state,
    test_family_v2_upgrade_is_explicit_and_projects_exact_v1_state,
    test_family_v2_cli_upgrade_writes_only_the_successor_state,
    test_family_v2_transition_requires_typed_settlement_and_exposes_publication_lag,
    test_family_v2_completion_requires_all_merged_accepted_and_published,
    test_family_v2_rejects_stale_or_revoked_warrant,
    test_family_v2_merged_settlement_requires_decision_and_admission,
    test_family_v2_rejects_self_consistent_settlement_from_another_cut,
    test_family_v2_settlement_requires_exact_authority_status,
    test_family_v2_assignment_state_status_must_match_v1_lifecycle,
    test_family_v2_work_definition_identity_must_match_child,
    test_family_v2_rejects_swapped_or_misbound_semantic_references,
    test_family_v2_rejects_hidden_publication_lag,
)
from _assignment_orchestration_admission_cases import (
    test_cli_run_preserves_an_intentional_machine_readable_exit,
    test_initiative_admission_requires_exact_content_root,
    test_exact_initiative_identity_uses_the_open_record_without_schema_drift,
    test_cli_runtime_refreshes_a_new_workspace_identity,
    test_source_root_recovers_checkout_from_assembled_binding,
    test_binding_provenance_accepts_platform_bound_installed_product,
    test_binding_provenance_rejects_platform_mismatched_manifest_entrypoint,
    test_installed_runtime_accepts_a_filesystem_alias_root,
    test_installed_capture_matches_source_contract_without_runtime,
    test_family_initiative_child_parent_stays_advisory_at_assignment_admission,
    test_captured_request_admits_losslessly_and_drives_bounded_execution,
)
from _assignment_orchestration_lifecycle_cases import (
    test_work_resume_prepare_rebinds_stale_profile_without_losing_assignment,
    test_nonterminal_continuation_decision_starts_a_new_completion_cycle,
    test_next_actions_defers_to_incomplete_work_semantics,
    test_next_actions_keeps_completion_after_work_semantics_settle,
    test_gate_field_equivalence_and_runtime_independent_seal,
    test_sealed_state_survives_git_worktree_deletion,
    test_sealed_state_index_retains_exact_work_coordinate,
)
from _assignment_orchestration_federation_cases import (
    test_assignment_relation_handshake_is_workspace_routed_and_fact_backed,
    test_external_initiative_ref_owns_no_duplicate_project_initiative,
    test_local_parent_shorthand_is_frozen_as_workspace_qualified_ref,
    test_unresolved_dependency_shorthand_remains_visible_without_fake_work_ref,
    test_sealed_state_verification_survives_path_free_transfer,
    test_home_sealed_state_uses_home_storage_without_embedding_its_path,
    test_cross_workspace_binding_has_two_local_receipts_and_verifies_offline,
)
