# SPDX-License-Identifier: Apache-2.0

import ast
import hashlib
from pathlib import Path

from kungfu.rewind import reflection_fb


_REWIND_ROOT = Path(__file__).parents[2] / "src/python/kungfu/rewind"
_GENERATED_ROOT = _REWIND_ROOT / "reflection"
_GENERATED_MODULES = (
    "AdvancedFeatures.py",
    "BaseType.py",
    "Enum.py",
    "EnumVal.py",
    "Field.py",
    "KeyValue.py",
    "Object.py",
    "RPCCall.py",
    "Schema.py",
    "SchemaFile.py",
    "Service.py",
    "Type.py",
)
_LEGACY_DEFINITION_ROOT = (
    "1a572433c3dc7a458582fa531b1740a34c07e3e0c3410643dae36f933e4ce4d0"
)
_REFLECTION_SCHEMA_ROOT = (
    "353463a046c61e6266698ad4b33b06e748ccb23c13b8bcbb051fc60e276384fa"
)


def _definitions(path: Path) -> set[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    return {
        node.name
        for node in tree.body
        if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef))
    }


def test_reflection_projection_is_split_without_hiding_generated_code() -> None:
    paths = [_REWIND_ROOT / "reflection_fb.py"] + [
        _GENERATED_ROOT / name for name in _GENERATED_MODULES
    ]
    assert all(path.read_text(encoding="utf-8").count("\n") < 1000 for path in paths)
    assert all(
        path.read_text(encoding="utf-8").startswith(
            "# automatically generated by the FlatBuffers compiler, do not modify"
        )
        for path in paths[1:]
    )


def test_split_projection_conserves_the_legacy_public_definition_set() -> None:
    names = set()
    for name in _GENERATED_MODULES:
        prefix = name.removesuffix(".py")
        names.update(
            definition
            for definition in _definitions(_GENERATED_ROOT / name)
            if definition == prefix or definition.startswith(prefix)
        )
    root = hashlib.sha256("\n".join(sorted(names)).encode()).hexdigest()
    assert len(names) == 114
    assert root == _LEGACY_DEFINITION_ROOT
    assert all(hasattr(reflection_fb, name) for name in names)
    assert all(
        getattr(reflection_fb, name).__module__ == reflection_fb.__name__
        for name in names
    )


def test_checked_in_reflection_schema_is_the_pinned_generation_authority() -> None:
    schema = (_REWIND_ROOT / "reflection.fbs").read_bytes()
    assert hashlib.sha256(schema).hexdigest() == _REFLECTION_SCHEMA_ROOT
    assert b"namespace reflection;" in schema
    assert b'file_identifier "BFBS";' in schema


def test_split_projection_decodes_the_checked_in_rewind_bfbs() -> None:
    bfbs = (_REWIND_ROOT / "rewind_events.bfbs").read_bytes()
    schema = reflection_fb.Schema.GetRootAs(bfbs, 0)
    assert schema.ObjectsLength() == 10
    assert schema.EnumsLength() == 5
    assert schema.ServicesLength() == 0
    assert schema.FbsFilesLength() == 1
    assert [schema.Objects(index).Name().decode() for index in range(10)] == [
        "kungfu.rewind.fb.ApprovalDecision",
        "kungfu.rewind.fb.CostSnapshot",
        "kungfu.rewind.fb.ModelRequest",
        "kungfu.rewind.fb.ModelResponse",
        "kungfu.rewind.fb.RetryMarker",
        "kungfu.rewind.fb.RunBegin",
        "kungfu.rewind.fb.RunEnd",
        "kungfu.rewind.fb.RunProgress",
        "kungfu.rewind.fb.ToolCall",
        "kungfu.rewind.fb.ToolResult",
    ]
