# SPDX-License-Identifier: Apache-2.0

name: Release - Verify
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - alpha/*/*
      - release/*/*
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  try:
    uses: kungfu-systems/workflows/.github/workflows/.release-verify.yml@dev/v1/v1.2
    with:
      build-runner-linux-labels: ${{ github.repository == 'kungfu-systems/kungfu' && '["self-hosted","Linux","X64","agent-120","kungfu-build","linux-x64"]' || '' }}
      build-runner-macos-labels: ${{ github.repository == 'kungfu-systems/kungfu' && '["self-hosted","macOS","ARM64","mac-studio","kungfu-build","macos-arm64"]' || '' }}
      build-runner-windows-labels: ${{ github.repository == 'kungfu-systems/kungfu' && '["self-hosted","Windows","X64","darkhero","kungfu-build","windows-x64"]' || '' }}
      use-pipenv: true
      build-timeout-minutes: 150
      max-build-attempts: 3
      enable-linux: true
      enable-macos: true
      enable-windows: true
    secrets:
      AWS_CI_ACCESS_KEY_ID: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
      AWS_CI_SECRET_ACCESS_KEY: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}
      AWS_USER_ACCESS_KEY_ID: ${{ secrets.AWS_USER_ACCESS_KEY_ID }}
      AWS_USER_SECRET_ACCESS_KEY: ${{ secrets.AWS_USER_SECRET_ACCESS_KEY }}

  verify:
    needs: try
    runs-on: ubuntu-22.04
    steps:
      - name: report
        run: echo verified
