# SPDX-License-Identifier: Apache-2.0

name: Source Acceptance

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  source-acceptance:
    name: Source acceptance
    uses: kungfu-systems/buildchain/.github/workflows/check.yml@9e904de2c85dbea7c799780ee166510b3336d812 # v3.0.0
    with:
      buildchain-ref: v3
      mode: source
      upload-artifacts: true
