# SPDX-License-Identifier: Apache-2.0

name: Source Acceptance

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  source-acceptance:
    name: Source acceptance
    uses: kungfu-systems/buildchain/.github/workflows/public-build-check.yml@v4-alpha
    with:
      buildchain-ref: v4-alpha
      mode: source
      upload-artifacts: true
